### ISSUE TITLE
`null` in svg icon id's

### ISSUE THREAD

**Issue by darkwebdev** [eBay/skin#1028]
What's with those [SVG icons](https://raw.githubusercontent.com/eBay/skin/master/src/svg/ds6/icons.svg) that have ids with `null`s in them:
```
	<symbol id="null-cart" viewBox="0 0 57 57">...
    <symbol id="null-search" viewBox="0 0 57 57">...
    <symbol id="null-wallet" viewBox="0 0 59 55">...
    <symbol id="null-watch" viewBox="0 0 63 45">...
```
All other icons have id's starting with `icon`. Is that correct or a bug?

**Comment by ianmcburnie** [comment]
Null icons are legacy from DS4. I'm not sure how they crept in here. It's a shame we didn't spot these and remove them before v10 release. I guess they'll stay here until v11 for now. I'll keep this issue open to track it. Thanks!

**Comment by agliga** [comment]
Null had been added in DS6 because these new large icons were used for the null state, which is why they were named like this. 
If we want to change it, we should change it to large and not remove them because they are the new ds6.5 icons.

**Comment by ianmcburnie** [comment]
Interesting, I don't see them documented anywhere on the website, but thanks for clarifying. We will be getting an entirely new icon set soon, we can do some cleanup then.

**Comment by darkwebdev** [comment]
@agliga what's a null state and why does it require large icons?

**Comment by ianmcburnie** [comment]
Seems like the "null" terminology is being dropped in favour of "large". 

<img width="686" alt="Screen Shot 2020-02-26 at 8 46 25 AM" src="https://user-images.githubusercontent.com/38065/75367063-8f309d80-5874-11ea-945a-b422e9923e08.png">

The null names can be deprected as part of #1039.

**Comment by agliga** [comment]
We will keep null icons and then remove them in the next major version in case people are not using them. For now `10.2.0` will have large icons which people should start to use.

**Comment by ianmcburnie** [comment]
Done in 11.0.0. Closing
