### ISSUE TITLE
typography-small-secondary mixin is using an undefined color variable

### ISSUE THREAD

**Issue by PrashantAshok** [eBay/skin#1031]
https://github.com/eBay/skin/blob/v9.5.4/src/less/mixins/typography/base/typography-mixins.less#L95

```
color: @color-text-secondary-small;
```

The above should be 

```
color: @color-text-secondary;
```

**Comment by agliga** [comment]
Fixed in `@ebay/skin@9.5.5`
Also upgraded `@ebay/ebayui-core@4.5.12` to consume that skin version.
