### ISSUE TITLE
Menu-Button: overlay width changes as menu-items are added/removed

### ISSUE THREAD

**Issue by swathip88** [eBay/skin#1033]
## Description
While using `menu` , on adding every menu item, width of the menu increases.
To reproduce the issue: Try adding/removing the menu-item elements in browser debugger(width increases or decreases respectively)

## Workaround
Need to add `display: flex` and `flex-direction: column` to parent container

##Screenshots
Three menu items
![Screen Shot 2020-02-18 at 3 58 08 PM](https://user-images.githubusercontent.com/15898444/74788787-9568bd80-5267-11ea-9d1e-10110e3732d6.png)

Two
![Screen Shot 2020-02-18 at 3 58 30 PM](https://user-images.githubusercontent.com/15898444/74788807-a1547f80-5267-11ea-99f2-2f762e2681af.png)
 menu items

**Comment by agliga** [comment]
Original issue on ebayui https://github.com/eBay/ebayui-core/issues/1066

**Comment by ianmcburnie** [comment]
Sounds like a new modifier. We already have a `menu-button__menu--fix-width` though, which works a little differently to what is required here.

**Comment by agliga** [comment]
I don't think this is an issue anymore. I checked it on ebayui core and I cannot reproduce it. 
If you can reproduce it, please reopen.
