### ISSUE TITLE
Menu: custom icons are being hidden

### ISSUE THREAD

**Issue by agliga** [eBay/skin#1034]
Custom icons are not showing because they are being treated like the tick and get `opacity: 0;` inside both menu and menu-button. 

We should change the selector for the status icon to be `icon--tick` or `menu-status` … something that indicates it is the status icon and not another nested icon.

Current selector is:
`.menu__item svg.icon, .fake-menu__item svg.icon` in https://github.com/eBay/skin/blob/master/src/less/menu/base/menu.less#L24-L25
and
`.menu-button__item svg.icon, .fake-menu-button__item svg.icon` in https://github.com/eBay/skin/blob/master/src/less/menu-button/base/menu-button.less#L37-L38

**Comment by ianmcburnie** [comment]
Good catch @agliga . Solution seems sound. Not urgent as I don't think anyone is using custom icons (tempted to remove this feature, actually), but it's an easy fix so may aswell do it.

**Comment by ianmcburnie** [comment]
Fixed in 11.0.0 branch. Closing.
