### ISSUE TITLE
Spinner: spinner.svg is retrieved from non-secure url

### ISSUE THREAD

**Issue by dkallus** [eBay/skin#1036]
I see spinner.svg being downloaded from http:// instead of https://. As a result, browsers show my page as "Not Secure".

The following code appears to be the root cause: 
* https://github.com/eBay/skin/blob/7f1a426c2f4085196efd55953ecacd2ce1b0ac5f/src/less/spinner/ds6/spinner.less#L7
* https://github.com/eBay/skin/blob/7f1a426c2f4085196efd55953ecacd2ce1b0ac5f/src/less/spinner/ds4/spinner.less#L7

**Comment by ianmcburnie** [comment]
Fixed in 9.5.6 and 10.1.0

**Comment by dkallus** [comment]
Thank you!
