### ISSUE TITLE
Button: type "small" should change font size to 14px

### ISSUE THREAD

**Issue by seangates** [eBay/skin#106]
When the class `btn--small` is applied, only the paddings change. It should also change the font size to `14px`.

**Note:** We need design to confirm this font size before proceeding.

**Comment by JeffNixonCreative** [comment]
Yes. The symbol currently in the Sketch Library that designers are leveraging has the label font spec set to 14px on small buttons.

**Comment by seangates** [comment]
Closed through #148.
