### ISSUE TITLE
Scripts cleanup

### ISSUE THREAD

**Issue by agliga** [eBay/skin#1069]
As we have more scripts, we need to organize them better

* Create entry with `yargs` to call into each individual script. We can do commands like `script/runner generateImages --args` or `script/runner code-gen --id=newModule` 
* Add js linting
* Extract common portions in a helper

**Comment by ianmcburnie** [comment]
Good plan @agliga ! Is this something you want to take on yourself?

**Comment by agliga** [comment]
Yes planning on it. However if someone else is interested they can take it on

**Comment by ianmcburnie** [comment]
I think it's all yours :-)
