### ISSUE TITLE
DS4 fake/faux link is underlined always, instead of on hover

### ISSUE THREAD

**Issue by sendlo** [eBay/skin#107]
https://github.com/eBay/skin/blob/master/src/less/utility/ds4/utility.less#L73

**Comment by seangates** [comment]
@sendlo Can you add a little more insight into what's not correct here? This has likely been this way a while, so changing it might be disruptive. Therefore, I'd like to know more about what's driving the change.

**Comment by ianmcburnie** [comment]
By default we wanted buttons that look like links to always have an underline, because they may be surrounded by text. I guess we *could* change this to:

```css
p button.fake-link,
button.fake-link:hover {
  text-decoration: underline;
}
```

**Comment by sendlo** [comment]
Sorry.  I thought it was just an oversight.  

My understanding is that the eBay standard for links is that they're only underlined on hover.  But I see now that this is coming from the global header rather than skin.

So skin and the global header are in conflict. Skin says all links should always be underlined. But the global header is saying all links should only be underlined on hover. Maybe this is something that should be discussed for the next major skin release?

For now I'll override this fake-link behavior in my components so they behave similar to the link styles applied to the page from global header.

**Comment by ianmcburnie** [comment]
Links should always be underlined when surrounded/inline with text. If links are standalone, away from any text, and have enough affordance that they *do something*, then they do not need the underline.

**Comment by sendlo** [comment]
@ianmcburnie   So the default behavior on eBay is to NOT have links underlined.  This is coming from global header.  

```
a:active,a:link {
    color: #0654ba;
    text-decoration: none
}

a:visited {
    color: #6a29b9;
    text-decoration: none
}

a:hover {
    text-decoration: underline
}
```

But if we know its surrounded by text (inline) then we need to override the default behavior to give it an underline.

I guess the better solution would be to have the global header be consistent and override the fake-link behavior, like it does with standard links.  I'll bring it up to them.  In the meantime I'll override it myself for my components.

**Comment by ianmcburnie** [comment]
@sendlo To try and clarify, global header may be doing this but it should not be the default behaviour. Design team and accessibility team are both in agreement that links should always be underlined by default. This default behaviour may be overridden if the links are not surrounded by text. 

So we should never, ever do this as a global rule:

```css
a {
  text-decoration: none;
}
```

But we may do this, for example:

```css
a.refinement-link {
  text-decoration: none;
}
```

**Comment by sendlo** [comment]
Yep.  Thanks.  I understand.  But what you say should "never ever" be done is exactly what global header is doing.  See my previous comment with the code snippet from global header.  (And I think they've always done it this way.)
