### ISSUE TITLE
Mixed content warning on Skin website

### ISSUE THREAD

**Issue by senthilp** [eBay/skin#1073]
The Skin documentation [website](https://ebay.github.io/skin/) throws mixed content warning due to two references to a non-secure image – [http://i2.ebayimg.com/images/g/e0oAAOSwsN9W~YBY/s-l200.jpg](http://i2.ebayimg.com/images/g/e0oAAOSwsN9W~YBY/s-l200.jpg). 

The fix is to update the resource to HTTPS, which is already available [https://i2.ebayimg.com/images/g/e0oAAOSwsN9W~YBY/s-l200.jpg](https://i2.ebayimg.com/images/g/e0oAAOSwsN9W~YBY/s-l200.jpg)

![image](https://user-images.githubusercontent.com/453878/78461401-61adef80-767d-11ea-86bd-e9744a459cbc.png)

**Comment by ianmcburnie** [comment]
Fixed in production/master.
