### ISSUE TITLE
svg  has two elements with the same id attribute "icon-clear"

### ISSUE THREAD

**Issue by montoya332** [eBay/skin#1102]
![Screen Shot 2020-05-08 at 7 17 42 PM](https://user-images.githubusercontent.com/8145951/81461436-9cb1b000-9160-11ea-9f14-bb1c59588d77.png)

https://github.com/eBay/skin/blob/master/src/svg/ds6/icons.svg
svg  has two elements with the same id attribute "icon-clear"

**Comment by ianmcburnie** [comment]
Done in 10.4.0
