### ISSUE TITLE
New Module: Tooltip

### ISSUE THREAD

**Issue by seangates** [eBay/skin#111]
![screen shot 2018-11-02 at 10 46 24 am](https://user-images.githubusercontent.com/38065/47931631-9ae09f80-de8c-11e8-8328-58c18a521ffa.png)

Related: https://github.com/eBay/ebayui-core/issues/67

https://ebay.invisionapp.com/share/CWN9X1JF6MA#/screens/299234476

**Comment by ianmcburnie** [comment]
I don't think small screens got accounted for in this pattern. They look modal to me:

![screen shot 2018-11-02 at 10 47 12 am](https://user-images.githubusercontent.com/38065/47931689-ca8fa780-de8c-11e8-9330-31540927ecf8.png)

Maybe best creating a separate issue for this?

**Comment by seangates** [comment]
I say yes. Although, this should be the default experience on screen sizes sub 600px.

**Comment by seangates** [comment]
Separate PR is fine, we should create an issue to track, though.

**Comment by ianmcburnie** [comment]
Merged to 7.0.0 branch.
