### ISSUE TITLE
Stepper: add spaces between items

### ISSUE THREAD

**Issue by ianmcburnie** [eBay/skin#1110]
Not sure if this just got updated or we missed it, either way we need to add spaces between the dots if we can, for both types of layout:

<img width="459" alt="Screen Shot 2020-05-15 at 12 31 51 PM" src="https://user-images.githubusercontent.com/38065/82089221-13423680-96a8-11ea-9403-9955fa6a4ad8.png">

**Comment by rajkumarsrk** [comment]
Also font color for upcoming events label should be `#767676` as well

**Comment by ianmcburnie** [comment]
Done in 10.5.0 branch.
