### ISSUE TITLE
Webpack support is not working due to changes on top level entries

### ISSUE THREAD

**Issue by abiyasa** [eBay/skin#1125]
Since the top level entries are not less file anymore (see https://github.com/eBay/skin/pull/1095) the webpack support for Skin is not working anymore. The following are the problems.

## Outdated Documentation

On the current readme, it's still state:

```
import "@ebay/skin/button.less";
```

This will not work anymore as we don't have top-level less files.

## Webpack Config 

I tried to import Skin with webpack but still cannot make it work. Maybe it's my problem but this is what I did:
  * I called `import '@ebay/skin/button'` inside my `tsx` file but the webpack bundle failed due to:

```
uncaughtException Unexpected token '{'
/Users/isuhardi/works/sample-app-react-typescript-ebay/node_modules/@ebay/skin/dist/button/ds6/button.css:2
a.fake-btn {
           ^
```

  * I think now you need to have `css-loader` and not `less-loader` anymore on the webpack config since the top level `button.js` is just `require("./dist/button/ds6/button.css");` .

## Other

@DylanPiercey  One of the benefits of having top entries in `.less` file is you can import those eBay skin dependencies directly from other less file. 

Use case: imagine you are implementing a custom dialog. The `CustomDialog.jsx` will need to import 1 style file, the local `style.less`. Inside the `style.less` you put all the Skin dependencies (e.g Button, Dialog, and Icon in order the dialog to work). 
Now with the top level as JS file, you have to import all Skin dependencies inside the `CustomDialog.jsx`. I think it's ok considering you get better deduping but would be cleaner to put all the style related files inside `style.less`.

Thoughts?

**Comment by abiyasa** [comment]
I see. I guess that would be the case on webpack as well on compiling `.less` file. 
The tradeoff is now on your UI component, you have to import the all Skin depencies as well:

```jsx
// CustomDialog.jsx
import React from 'react';
import '@ebay/skin/button';
import '@ebay/skin/dialog';
import '@ebay/skin/icon';
import './style.less';  // UI component custom style 

...
```

I'm fine with this since you will get better deduping.

**Comment by ianmcburnie** [comment]
Sorry, didn't keep up with this convo. Is it resolved? Or do we need any additional changes or documentation?

**Comment by ianmcburnie** [comment]
Closing. Thanks @abiyasa and @DylanPiercey !
