### ISSUE TITLE
Support for Bottom only border Select

### ISSUE THREAD

**Issue by ohmirocks** [eBay/skin#1132]
Can we add support for the bottom only border select component? There are many uses in payments which has drop-down only with the bottom border. This is to align the design with the 
![image](https://user-images.githubusercontent.com/2748065/84050872-2d97c900-a963-11ea-828c-4598330b636c.png)
rest of the fields, especially with floating labels.

**Comment by ianmcburnie** [comment]
Thanks. Looks like we missed this playbook use case.

![Screen Shot 2020-06-08 at 8 14 45 AM](https://user-images.githubusercontent.com/38065/84090662-44600f00-a9a7-11ea-817d-eb211be2a318.png)
![Screen Shot 2020-06-08 at 8 14 55 AM](https://user-images.githubusercontent.com/38065/84090666-44f8a580-a9a7-11ea-8c7e-803be37f784e.png)

We'll take a look for next release. Should be fairly straightforward and similar to textbox underline:

https://ebay.github.io/skin/#textbox-underline

**Comment by ohmirocks** [comment]
thanks @ianmcburnie

**Comment by ianmcburnie** [comment]
Done in 10.6.0

**Comment by ohmirocks** [comment]
@ianmcburnie whats the modifier we need to use?

**Comment by ianmcburnie** [comment]
`select--underline`

**Comment by ohmirocks** [comment]
Awesome. Thanks. Will wait for the module get published
