### ISSUE TITLE
wizard-stepper: Handling use case of "information" followed by "upcoming" events

### ISSUE THREAD

**Issue by rajkumarsrk** [eBay/skin#1138]
## Screenshot: 
![Exception](https://user-images.githubusercontent.com/691176/84829126-18aedb80-afdc-11ea-90d0-470ee6017736.jpg)

## Issue:
When there is any exception use case `wizard-stepper__item--transition-information` followed by upcoming events `wizard-stepper__item--upcoming` we don't see transition line between these 2 events. In above screen shot you can see "out for delivery" is not connected with "Estimated delivery" use  case. Currently skin supports only "information" followed by "attention" but we need support for "information" followed by "upcoming"

## Expected:
There should be separator between "information" and "upcoming" with separator line color of `#c7c7c7`

**Comment by agliga** [comment]
As a workaround, this works fine:
`wizard-stepper__item wizard-stepper__item--current wizard-stepper__item--information`
and shows up properly. Should be in that order so the styles don't override.
However, will add a transition class to keep it clean in `5.5.0`

**Comment by rajkumarsrk** [comment]
Thanks @agliga . Changes that you have made for `.stepper__item--transition-upcoming` helps

**Comment by agliga** [comment]
Released in `10.5.0`

**Comment by agliga** [comment]
Released in `10.5.0`
