### ISSUE TITLE
Dialog: clickable "dead zone" in mask

### ISSUE THREAD

**Issue by hramakumar** [eBay/skin#1142]
# Bug Report

## Description
clicking below the dialog border in the grey area does not close the dialog.
Dialog closes when clicked on the top or on the sides but not in the bottom grey area.

## Screenshots
https://www.loom.com/share/5ba97e149e844bcb8d1302048427e463

**Comment by ianmcburnie** [comment]
Blocked by #1082 (makes sense to do that one first)

**Comment by ianmcburnie** [comment]
@agliga to verify this one again when changes pushed to coreui.

**Comment by ianmcburnie** [comment]
Seems like this got fixed as a result of the refactoring by @agliga. Tested in CoreUI. Closing.
