### ISSUE TITLE
BUG: DS6 dialog selector is not specific enough

### ISSUE THREAD

**Issue by seangates** [eBay/skin#115]
Even using a scoped selector we still run into an issue with the specificity when DS6 dialog is used on a DS4 page. In other words, the current selector for DS4 is more specific than the DS6 selector. This means we will have issues when using scoped CSS.

## Example

```
// scoped ds6 selector for the dialog
.ds6 dialog {
    ...
}

// DS4 selector
.dialog[role="dialog"] {
    ...
}
```

## Screenshot

![scoped CSS selector specificity](https://user-images.githubusercontent.com/105656/38116960-c530cb98-336f-11e8-9c9b-f5a639b43817.png)

>Reported by @CestDiego

**Comment by ianmcburnie** [comment]
Good spot, but shouldn't this go in https://github.com/eBay/skin/pull/113?

**Comment by DylanPiercey** [comment]
Probably should have `[role="dialog"]` on there anyways. I can fix that and update my PR.

**Comment by seangates** [comment]
@ianmcburnie Doh!

Let me close this and move it.
