### ISSUE TITLE
Website: replace Lasso with Webpack (or Vite?)

### ISSUE THREAD

**Issue by ianmcburnie** [eBay/skin#1151]
Website is still using Lasso:

https://github.com/eBay/skin/blob/master/docs/ds6.browser.json

Let's update to use Webpack (or Vite, maybe?)

**Comment by ianmcburnie** [comment]
As part of this we can also remove the ds4/ds6 js folders and files:

https://github.com/eBay/skin/tree/master/docs/src/js

They are redundant now that ds4 and ds6 pages use the exact same js.

**Comment by austingardner** [comment]
I would like to take this on... might need some guidance at some points but I think it would be helpful for me to know

**Comment by ianmcburnie** [comment]
It's all yours. Thanks!

**Comment by ianmcburnie** [comment]
Javascript portion is done. All that remains is the LESS/CSS.

https://github.com/eBay/skin/commit/86f7e1a2b5f39c768e29747e4f654564bd0e71a8

**Comment by ianmcburnie** [comment]
Closing. We don't really need webpack for the LESS piece. The LESS compiler alone should be sufficient.
