### ISSUE TITLE
SVG Icons: icon-chevron-down-extra-small & icon-chevron-up-extra-small

### ISSUE THREAD

**Issue by sskmek** [eBay/skin#1184]
SVG Icons: 
Icon: icon-chevron-down-extra-small & icon-chevron-up-extra-small uses same path. Because of that we are always getting same arrow icon while using it.
<path d="M8.813.184a.656.656 0 00-.906 0l-3.406 3.31-3.4-3.31a.658.658 0 00-.912 0 .615.615 0 000 .887l3.856 3.747c.25.243.655.243.906 0l3.856-3.747a.616.616 0 00.006-.887z"></path>

Source Code: 
view-source:https://raw.githubusercontent.com/eBay/skin/54c1ebc09bbd436dfa4af28d986ca0fd867aa20f/dist/svg/ds6/icons.svg

**Comment by ianmcburnie** [comment]
@sskmek Which version are you using?

**Comment by sskmek** [comment]
@ianmcburnie, I haven't used these icon. For a new feature in View Item page, I have started implementing icon-chevron-down-extra-small / icon-chevron-up-extra-small and found this issue. We have upgraded skin to v10.2.0 from v9.4.2

**Comment by ianmcburnie** [comment]
@sskmek are you able to upgrade to 10.6.x? I'm planning on patching this in 10.6.1.

**Comment by sskmek** [comment]
sure @ianmcburnie. thank you!!

**Comment by ianmcburnie** [comment]
Fixed and published in v10.6.1
