### ISSUE TITLE
Textbox: icon-btn svg color is taking precedence over textbox svg color

### ISSUE THREAD

**Issue by melquan** [eBay/skin#1190]
v5.6.1 of @ebay/ebayui-core now supports a postfix icon button for `ebay-textbox`, but it seems the icon-btn svg color (#111820) is taking precedence over the textbox svg color (#c7c7c7).

From [eBayUI Storybook](https://ebay.github.io/ebayui-core/?path=/story/ebay-textbox--both-icons):
![image](https://user-images.githubusercontent.com/19419138/88330774-c2227480-cce0-11ea-84c8-388f7620eb6a.png)

**Comment by melquan** [comment]
Also what should the hover color be?  I didn't see any specs on that in the Playbook.

Currently it's blue and I'm guessing it's inheriting it from icon-btn also.

**Comment by ianmcburnie** [comment]
Blue seems correct, that is what the system defines for hover actions, so I guess we should go with that.

**Comment by ianmcburnie** [comment]
Looks like they are trying to darken up the textbox icons in 6.5:

![Screen Shot 2020-07-28 at 10 01 51 AM](https://user-images.githubusercontent.com/38065/88697605-b278a680-d0b9-11ea-81b5-5db8aa63f308.png)

I'll try and get some clarification of what we should do here.

**Comment by ianmcburnie** [comment]
Guidance from design is to go with #767676 for the interactive icon for now.

Also, the example should be updated to use the clear icon instead of the close icon.
