### ISSUE TITLE
Market Sans

### ISSUE THREAD

**Issue by typex-code** [eBay/skin#1199]
Hey, is Market Sans free to use for commercial purposes?

**Comment by ianmcburnie** [comment]
@typex-code Thank you for your question. I'm sorry to inform you that Market Sans is not free to use for commercial purposes.

**Comment by typex-code** [comment]
What are some free alternatives that look like Market Sans?

**Comment by ianmcburnie** [comment]
Sorry, I would love to help - but I don't really know enough about type faces & fonts to even point you in the right direction. Maybe reach out to designers or a design forum? Good luck! Closing ticket.

**Comment by typex-code** [comment]
okay.

**Comment by typex-code** [comment]
Can I buy the license to use it for commercial purposes, I really like it
