### ISSUE TITLE
Button: Multi-line CTA wraps outside of button area

### ISSUE THREAD

**Issue by seangates** [eBay/skin#122]
As reported by @abiyasa:

### Current multiline button

![Current multiline button](https://user-images.githubusercontent.com/105656/38261115-8cf358b2-3726-11e8-8f44-226353972a61.png)

### DS6 multiline button

![DS6 multiline button](https://user-images.githubusercontent.com/105656/38261144-a6b1556a-3726-11e8-8897-9800e19443a2.png)

### Use a BEM modifier

```
.cta-btn {
  &.cta-btn--multilines {
    height: auto;
    line-height: 1.4;
    text-align: left;

    .cta-btn__cell {
      align-items: center;
      padding: 12px 0;
    }

    .cta-btn__icon {
      flex-shrink: 0;
    }
  }
}
```

### Directly change `.btn` or `.cta-btn` behavior

```
.cta-btn__cell {
    height: auto;
}
.cta-btn__cell > span {
    line-height: 20px;
    padding: 12px 0;
    text-align: left;
}
.cta-btn__icon {
    flex-shrink: 0;
}
```

**Comment by ianmcburnie** [comment]
Let's verify this use case with design system first, as it was never approved by them.

**Comment by seangates** [comment]
Yup. I am simply writing it down so we can prioritize looking into it.

**Comment by JeffNixonCreative** [comment]
Hello. To address the button "wrapping" issue, the label should always remain on one line.
If the button label happens to exceed the width of the button, the button label should truncate (three ellipsis).
However, a buttons label should be a quick read which would be accommodated by a short call to action. if there is a need for an actionable element to be in sentence form, and exceed one or two words, I would suggest either another component be leveraged, or the treatment/design accommodate the component. Meaning, either revise the cta, or place the cta in close proximity to the button with a one or two word cta that reinforces the sentence as the button label.
