### ISSUE TITLE
Icon: Extra small icon mixin and variables missing

### ISSUE THREAD

**Issue by PrashantAshok** [eBay/skin#1243]
When rendering the ```<ebay-arrow-right-extra-small-icon/>``` - it does not render with the css class associated with the extra small icon. That's because it is missing the relevant [mixin](https://github.com/eBay/skin/blob/ed5a4f925aaaa10aa959b81c198b69e36b086af4/src/less/icon/ds6/icon.less#L21) and [variables](https://github.com/eBay/skin/blob/ed5a4f925aaaa10aa959b81c198b69e36b086af4/src/less/variables/ds6/icon-variables.less#L20).

<img width="763" alt="Screen Shot 2020-09-10 at 4 20 26 PM" src="https://user-images.githubusercontent.com/5200733/92974541-584e5d80-f43b-11ea-946c-42d7c136ba85.png">

**Comment by ianmcburnie** [comment]
Fixed in 11. Closing.
