### ISSUE TITLE
Menu Button: Cutting off at the corner

### ISSUE THREAD

**Issue by PrashantAshok** [eBay/skin#1251]
`@ebay/skin": "^11.0.0-3`

When the `menu-button` gets rendered at the corner of the screen, the expanded section gets cut off. 

<img width="191" alt="Screen Shot 2020-09-17 at 4 22 22 PM" src="https://user-images.githubusercontent.com/5200733/93541400-35282000-f90b-11ea-9b4d-79d3e16db66f.png">

Looks like the new skin is adding these 2 additional styles

```
span.menu-button, span.fake-menu-button {
    display: inline-block;
    vertical-align: bottom;
}
```

This issue can be reproduced by adding a high enough margin to bring the menu-button closer to the end of the viewport and opening the menu - the expander part used to adjust fine in earlier versions.

**Comment by PrashantAshok** [comment]
Looks like this [commit](https://github.com/eBay/skin/commit/cf5edb8008ead33803586d761a5bcfb6c17928bb#diff-b1b5179d03de5c920653d2082dbaecf7R21) made this change.

**Comment by ianmcburnie** [comment]
Thanks @PrashantAshok . I added these rules for alignment of buttons on the same line, but will investigate. Can you do a quick check to see if it's the `inline-block`, `vertical-align`, or both causing the issue?

**Comment by PrashantAshok** [comment]
`inline-block` is doing the cut-off. As you can see in the above screenshot, `vertical-align` is causing the menu label `Filter:` to shift as well.

**Comment by ianmcburnie** [comment]
Reverted the change that caused this regression, but now we have to solve the alignment issue here:

https://github.com/eBay/skin/commit/cf5edb8008ead33803586d761a5bcfb6c17928bb#diff-b1b5179d03de5c920653d2082dbaecf7R21

I'll create a new ticket.
