### ISSUE TITLE
NEW: Marketing Banners

### ISSUE THREAD

**Issue by ianmcburnie** [eBay/skin#1255]
More info and screenshots to follow.

![Screen Shot 2020-09-25 at 12 01 21 PM](https://user-images.githubusercontent.com/38065/94306174-526e7700-ff27-11ea-8e49-64f188e13fd2.png)

**Comment by austingardner** [comment]
Is this component still necessary? Or did it get folded into an existing component?

**Comment by ianmcburnie** [comment]
It's still necessary, but low priority.

**Comment by ianmcburnie** [comment]
Moving to super backlog.
