### ISSUE TITLE
Button: secondary button does not match DSL

### ISSUE THREAD

**Issue by zzhan223** [eBay/skin#127]
http://ebay.github.io/skin/ds6/#button
https://dsl.ebay.com/ds6/buttons
text for secondary button is black instead of blue

**Comment by ianmcburnie** [comment]
We need to verify if this is true. Somebody mentioned that:

`marketing buttons are the only ones that get to be colored`

**Comment by ianmcburnie** [comment]
Ok, this is legit. Will fix in 4.0.0

**Comment by ianmcburnie** [comment]
Need to re-verify this with design. We used to have blue secondary buttons in v3.2

http://ebay.github.io/skin/archive/v3.2/ds6/#button

Then we changed them to black in v3.4:

http://ebay.github.io/skin/archive/v3.4/ds6/#button

**Comment by JeffNixonCreative** [comment]
Please reference the Secondary Sizes section of the Button page on DSL:
https://dsl.ebay.com/ds6/buttons#button__secondary--size

Currently, the secondary button should have a blue label with a blue outline. It appears there are two color builds of blue for the secondary button .P002 & .P003

If it is an "Action Button" or button containing a CTA (Call To Action), then there is a treatment that has black label with black border:
https://dsl.ebay.com/ds6/buttons#button__action--sizes

I hope that helps.  Let me know if you have any outstanding questions.

Cheers.

Jeff

**Comment by seangates** [comment]
Closed through #148.
