### ISSUE TITLE
Combo: Remove iconfont and icon dependencies

### ISSUE THREAD

**Issue by ianmcburnie** [eBay/skin#13]
Skin is moving away from icon fonts towards SVG. When the time is right, we should remove icon and iconfont modules out of the combo bundle, as we do not want to continue promoting the icon font.

This will be a breaking change for skin-inception though.

I wonder whether we should just retire the combo bundle altogether. I know inception uses it, but I'm not entirely sure I see the benefit anymore of this bundle...

https://ebay.github.io/skin/#bundles

**Comment by seangates** [comment]
@ianmcburnie Is this still useful? Should we close it given the way we've done icons for DS6?

**Comment by ianmcburnie** [comment]
I think we can close this now. Closing.
