### ISSUE TITLE
Breadcrumbs: Entire text is not showing up and not scrollable, if the text is long

### ISSUE THREAD

**Issue by deenabay** [eBay/skin#1303]
# Bug Report

## eBayUI Version: 
    "@ebay/ebayui-core": "^6.0.0-4",
    "@ebay/skin": "^11.0.0-4",

## Description
The breadcrumb is not showing the complete text, if the text is long.
Only the last portion of the breadcrumb is visible.
CC: @agliga @ianmcburnie 

## Screenshots
![image](https://user-images.githubusercontent.com/71992704/96768658-e8fd4f00-1392-11eb-937a-3e77de937b5f.png)

**Comment by ianmcburnie** [comment]
Fixed in 12.6.0
