### ISSUE TITLE
Infotip: close button size issue

### ISSUE THREAD

**Issue by edvardsniedre** [eBay/skin#1306]
Skin v11.0.0 Infotip close button shrink when more content added.
![button](https://user-images.githubusercontent.com/7050068/101378006-74329580-38aa-11eb-822f-506eedb70947.gif)

Comparing code with Skin v10 it looks like `flex-shrink: 0;` on the close button is missing.
![Dec-07-2020 16-33-03](https://user-images.githubusercontent.com/7050068/101378480-0c307f00-38ab-11eb-8f49-6d4f1ea4aa23.gif)

**Comment by agliga** [comment]
Fix is released in skin `11.0.1`
