### ISSUE TITLE
Getting Warning in console Invalid DOM property `viewbox`. Did you mean `viewBox`

### ISSUE THREAD

**Issue by montoya332** [eBay/skin#1317]
Match viewBox naming for new photo icons
   
 
    <symbol viewbox="0 0 20 20" id="icon-photo-contrast">
    <symbol viewbox="0 0 16 22" id="icon-photo-flash">
    <symbol viewbox="0 0 24 20" id="icon-photo-flip-camera">
    <symbol viewbox="0 0 21 20" id="icon-photo-sharpen">

**Comment by ianmcburnie** [comment]
Thanks @montoya332.  Is this just for the website, or the actual SVG module too?

**Comment by ianmcburnie** [comment]
Fixed in 11.0.2 branch
