### ISSUE TITLE
Button: flexbox issues in IE11

### ISSUE THREAD

**Issue by ianmcburnie** [eBay/skin#1322]
![Screen Shot 2021-01-05 at 6 26 19 PM](https://user-images.githubusercontent.com/38065/103721872-9be94c00-4f83-11eb-933b-eed0ec2b9fc2.png)

**Comment by austingardner** [comment]
Should we close this yet? I mean it doesn't seem like this will ever be done.

**Comment by ianmcburnie** [comment]
Fix merged to 12.5.0
