### ISSUE TITLE
Button: Add min-width

### ISSUE THREAD

**Issue by PrashantAshok** [eBay/skin#1335]
I noticed the button’s min-width is not present in Skin ^11.0.1 but is present in Skin 12 - can the change be back ported to 11?

https://github.com/eBay/skin/blob/master/src/less/button/base/button.less#L16
https://github.com/eBay/skin/blob/11.0.2/src/less/button/base/button.less#L4

**Comment by ianmcburnie** [comment]
Min width was introduced in v12 to match design system updates (rounded buttons). I'm not sure if it makes sense to back port it to v11.

**Comment by ianmcburnie** [comment]
Closing as per comments

**Comment by PrashantAshok** [comment]
@ianmcburnie - shouldn't button have a `min-width` by default?

**Comment by ianmcburnie** [comment]
The button tag (or input type=button) does not have a min width by default. Buttons should grow with the content. The only reason we are now adding it is because the new rounded buttons don't look good at small widths. I'm not a big fan of the rounded buttons tbh, but let's see how it goes...
