### ISSUE TITLE
Pagination: add ellipses/truncation 

### ISSUE THREAD

**Issue by ianmcburnie** [eBay/skin#1337]
Let's scope out the work involved to add a story for ellipses/truncation

![Screen Shot 2021-01-22 at 1 12 08 PM](https://user-images.githubusercontent.com/38065/105547623-82e6d780-5cb3-11eb-9e23-4f0b6e203254.png)

This one might need backporting to v10 or v11.

**Comment by agliga** [comment]
I don't think there is any work on the skin side, other than showing an example with this, correct? 
For the `...` are we doing an icon or just the keyboard `...`. 
There is an ascii … code for that too

**Comment by agliga** [comment]
For skin version will only need to add an example. For ebayui there will be a more in depth feature.

**Comment by ianmcburnie** [comment]
Done in 12.2.0
