### ISSUE TITLE
Remove dist folder when doing build

### ISSUE THREAD

**Issue by agliga** [eBay/skin#1338]
When doing builds, no files are removed. If you add a file and run the build, but later remove it, it will still be there unless you manually remove it.
It would be good to clean the dist folder in case files that are removed are no longer there.

**Comment by ianmcburnie** [comment]
I just remembered that in the past we have removed some src files, but left the dist files and browser.json files around for backwards compatibility. It was probably a bad practice, but just a heads up incase you do run into any orphan dist files you're not sure about.
