### ISSUE TITLE
Carousel: a11y color contrast issue for pause/play control

### ISSUE THREAD

**Issue by msendlakowski** [eBay/skin#1344]
If the carousel item background is dark, the color of the pause/play control may not meet a11y contrast requirements.

FYI, since carousel backgrounds could be different colors per slide, it would be great if the design team could come up with a single pattern that handled any background color, so the applications don't have to switch the colors as the items change.

![Screen Shot 2021-02-01 at 3 15 14 PM](https://user-images.githubusercontent.com/1562843/106530026-61020780-64a0-11eb-9a60-cc3694d2c337.png)

**Comment by ianmcburnie** [comment]
Fixed in 10.x
