### ISSUE TITLE
Fake-button with icon-only is misaligned vertically

### ISSUE THREAD

**Issue by darkwebdev** [eBay/skin#1345]
*Skin 12*

Fake button with icon:
```
<a class="fake-btn fake-btn--secondary fake-btn--icon-only" href="#">
  <span class="fake-btn__cell">
    <svg height="24px" width="24px" class="icon icon--settings " xmlns="http://www.w3.org/2000/svg" focusable="false" aria-hidden="true">
      <use xlink:href="#icon-settings"></use>
    </svg>
  </span>
</a>
```

<img width="44" alt="image" src="https://user-images.githubusercontent.com/2737310/106626198-bceb8f80-6577-11eb-94dd-49e052cdd3fa.png">

Real button looks fine:
<img width="43" alt="image" src="https://user-images.githubusercontent.com/2737310/106626500-105ddd80-6578-11eb-80ed-15b9d6f8115d.png">

**Comment by ianmcburnie** [comment]
Fixed in 12.2.0
