### ISSUE TITLE
Details: irregular keyboard focus outline (Safari)

### ISSUE THREAD

**Issue by jramani** [eBay/skin#1370]
## Description
On Safari Version 13.1.3 (15609.4.1) there is an irregular shaped outline on the Details module.
https://ebay.github.io/skin/index.html#details

![image](https://user-images.githubusercontent.com/7613529/108381623-e2c39600-71ff-11eb-8fbc-c232b2f62f88.png)

**Comment by ianmcburnie** [comment]
Moving to super backlog based on priority.
