### ISSUE TITLE
Floating Label: long label overlaps the input

### ISSUE THREAD

**Issue by darkwebdev** [eBay/skin#1372]
1. max width of the label is only 75% of the input
2. when label wraps it overlaps the input

![image](https://user-images.githubusercontent.com/2737310/108760633-31e62f80-754e-11eb-9e35-9bb2538c0ee9.png)

**Comment by ianmcburnie** [comment]
@austingardner I guess we'll have to do single line text truncation here.

https://ishadeed.com/article/css-short-long-content/#text-truncation

The element will also need a width I think. something like `calc(100% - horizontal_padding)`
