### ISSUE TITLE
Button: bottom border inherited from parent so gets overridden

### ISSUE THREAD

**Issue by melquan** [eBay/skin#1384]
# SKIN: v12.0.2

Due to button's `border-color` being inherited, if you set the border colors on the parent element, it will change the button's border colors.

Example:
```
<div style="
    border-bottom-color: red;
    border-top-color: green;
    border-left-color: blue;
    border-right-color: orange;
"><button class="btn btn--large" data-ebayui="" type="button">text</button></div>
```

![image](https://user-images.githubusercontent.com/19419138/112064879-eb6dfb80-8b20-11eb-8ad6-3ec4795f89b1.png)

**Comment by ianmcburnie** [comment]
Fixed in 12.3.0 branch
