### ISSUE TITLE
Infotip: no space between content and close button

### ISSUE THREAD

**Issue by edvardsniedre** [eBay/skin#1385]
Tested on Skin v12.2.0

<img width="482" alt="Screenshot 2021-03-22 at 23 16 30" src="https://user-images.githubusercontent.com/7050068/112069933-ae2b5d00-8b64-11eb-8455-44b06c025e3b.png">

<img width="366" alt="Screenshot 2021-03-22 at 23 16 35" src="https://user-images.githubusercontent.com/7050068/112069939-b388a780-8b64-11eb-8254-2c26ac5aa200.png">

Playbook guidelines suggests having 16 pixels between content and close button.

<img width="348" alt="Screenshot 2021-03-21 at 00 30 55" src="https://user-images.githubusercontent.com/7050068/112069997-c602e100-8b64-11eb-9107-85c6b77329f9.png">

**Comment by ianmcburnie** [comment]
Fixed in 12.3.0. Releasing soon!
