### ISSUE TITLE
Infotip host misaligned

### ISSUE THREAD

**Issue by edvardsniedre** [eBay/skin#1390]
Tested on v12.3.0

#1386 caused side effect to infotip host. Margin left was added for both close button and infotip host, but meant to be added only for close button.
<img width="394" alt="Screenshot 2021-03-29 at 11 31 05" src="https://user-images.githubusercontent.com/7050068/112824288-456f4380-9082-11eb-9e84-e0ee80bd6ddf.png">

**Comment by ianmcburnie** [comment]
Oops. @austingardner We should have gone with `infotip__close` after all. Let's put out a quick patch and ensure this class is also present in coreui.
