### ISSUE TITLE
progress-stepper `complete` icons

### ISSUE THREAD

**Issue by darkwebdev** [eBay/skin#1392]
Icon used for `complete` state of the Progress Stepper cannot be found inside SVG file.

Screenshots from the Skin 12 `Progress Stepper` documentation:
<img width="336" alt="image" src="https://user-images.githubusercontent.com/2737310/113122343-d295d200-9213-11eb-95f9-e952638a363e.png">
<img width="408" alt="image" src="https://user-images.githubusercontent.com/2737310/113122506-fce78f80-9213-11eb-987e-11b0e5713f79.png">

Screenshot from the Skin 12 `Icon` documentation (black `confirmation` icon, green `confirmation-filled`):
<img width="652" alt="image" src="https://user-images.githubusercontent.com/2737310/113122201-ada15f00-9213-11eb-821f-9eca373c9783.png">

Now let's look inside SVG:
- `stepper-confirmation` doesn't exist
- blue `confirmation-filled` doesn't exist
- green `confirmation-filled` exists
- blue `confirmation` exists

But somehow eBayUI marko `progress-stepper` component works: https://ebay.github.io/ebayui-core/?path=/story/ebay-progress-stepper-step-type--all-complete

**Comment by austingardner** [comment]
The icon can be found at https://github.com/eBay/skin/blob/93380b4cf40c3c8fdc5bcc98379f61d1e024445b/src/svg/ds6/icons.svg#L595.

So the stepper-confirmation does exist.

**Comment by austingardner** [comment]
You might have to click on the "source" tab, because the "blob" tab doesn't display things correctly in this case

**Comment by darkwebdev** [comment]
thanks, upgrade to the latest skin helped!
