### ISSUE TITLE
Module not found: Error: Can't resolve './dist/svg/ds6/icons.svg.css' 

### ISSUE THREAD

**Issue by montoya332** [eBay/skin#1394]
it looks like the file extension could be generated wrong (   “@ebay/skin”: “12.3.1",)
ERR! Module not found: Error: Can’t resolve ‘./dist/svg/ds6/icons.svg.css’

<img width="928" alt="Screen Shot 2021-04-05 at 11 11 44 AM" src="https://user-images.githubusercontent.com/8145951/113609786-1e27f180-9601-11eb-9f46-ddda876d0c7a.png">

**Comment by ianmcburnie** [comment]
@agliga Could this be something to do with the changes you made that cleaned up the files in the root folder?

**Comment by ianmcburnie** [comment]
Andrew says "We just probably need to skip the extension in the config"

https://github.com/eBay/skin/blob/master/scripts/generate-imports/config.json

**Comment by ianmcburnie** [comment]
Done in 12.4.0
