### ISSUE TITLE
Notice: new DS6 styles

### ISSUE THREAD

**Issue by ianmcburnie** [eBay/skin#14]
EDITED: Latest spec in Jeff's comment below.

**Comment by ianmcburnie** [comment]
Some new design updates are being "rushed through", hot off the press:

![ds6_alertsmessaging_02](https://user-images.githubusercontent.com/38065/35708414-db87e176-0762-11e8-9dc8-109cdcdda6e3.png)

**Comment by JeffNixonCreative** [comment]
[DS6_alerts_v2.pdf](https://github.com/eBay/skin/files/1733297/DS6_alerts_v2.pdf)

**Comment by ianmcburnie** [comment]
Available in 3.4.0
