### ISSUE TITLE
Docs: update the icon creation guide

### ISSUE THREAD

**Issue by ianmcburnie** [eBay/skin#1423]
It's getting a little out of date now: https://github.com/eBay/skin/blob/master/ICON-CREATION.md

We no longer used background SVGs. We should document how to take icon SVG from figma and get it into the relevant place in skin.

**Comment by ianmcburnie** [comment]
Done in 14.0.0 branch.

**Comment by ianmcburnie** [comment]
I guess we should delete the `ICON-CREATION.md` and the section from `CONTRIBUTING.md` too.

**Comment by agliga** [comment]
> I guess we should delete the `ICON-CREATION.md` and the section from `CONTRIBUTING.md` too.

We should keep it around, there is still some info there that's useful, especially the manual process.
I will update it
