### ISSUE TITLE
pagination: design system updates Part 1 of 2 (EVO)

### ISSUE THREAD

**Issue by rbascue** [eBay/skin#1435]
Pagination will be simplified to use styling similar to new tabs. The controls will use the new icon button styling. Overflow variants account for pages between the first set and the last page. First and last page will always be visible.

Part 1 (this ticket) updates the styles only. Part 2 (https://github.com/eBay/skin/issues/1519) adds the overflow interaction and new states.

[Documentation](https://www.figma.com/file/IaJpngfyTXoM0wDid0MkkI/?node-id=1%3A43)

![Desktop example](https://user-images.githubusercontent.com/35155833/117870986-b4c77e00-b251-11eb-80c1-8e39164479a6.png)
![Delta](https://user-images.githubusercontent.com/35155833/117870995-b7c26e80-b251-11eb-83f6-4e35c94d1445.png)
![Specs](https://user-images.githubusercontent.com/35155833/117870996-b85b0500-b251-11eb-9119-64917ad049a6.png)
![Variants](https://user-images.githubusercontent.com/35155833/117870997-b85b0500-b251-11eb-8a3a-ce182b3d7de2.png)

**Comment by agliga** [comment]
Looks great!
One question, what about the case where we have pages 1 thru 80 and the user is on page 50 lets say. What does it look like with the dots? Do we show: `1 ... 50 ... 80`?

**Comment by rbascue** [comment]
Took a more thorough pass regarding the rules around overflow. Feel free to review the Figma file for better detail. And let me know if you have any questions about the proposed logic.

![Delta](https://user-images.githubusercontent.com/35155833/118337494-cb2b3f00-b4c8-11eb-8293-0143860d6007.png)
![Specs](https://user-images.githubusercontent.com/35155833/118337502-cebec600-b4c8-11eb-98e4-26b1c8bfef0b.png)
![Variants](https://user-images.githubusercontent.com/35155833/118337504-cf575c80-b4c8-11eb-8bfc-60bb73f76053.png)
![Desktop example](https://user-images.githubusercontent.com/35155833/118337498-cc5c6c00-b4c8-11eb-82d8-7521c077be02.png)

**Comment by ianmcburnie** [comment]
First part is done in 13.0.0 branch. Closing.
