### ISSUE TITLE
tabs: design system updates (EVO)

### ISSUE THREAD

**Issue by rbascue** [eBay/skin#1436]
We’re updating tabs to be lightweight and friendly. The two-line tab design will be deprecated and active state will go from blue to primary text grey.

[Documentation](https://www.figma.com/file/IaJpngfyTXoM0wDid0MkkI/?node-id=1%3A42)

![Delta](https://user-images.githubusercontent.com/35155833/117872144-2f44cd80-b253-11eb-9580-155dac7e9ca6.png)
![Specs](https://user-images.githubusercontent.com/35155833/117872151-323fbe00-b253-11eb-9efd-0b1c1a8df74c.png)
![Variants](https://user-images.githubusercontent.com/35155833/117872155-32d85480-b253-11eb-9413-4a4a71baa8f3.png)
![iOS Tab example](https://user-images.githubusercontent.com/35155833/117872148-3075fa80-b253-11eb-8f9c-9cf2d2739b77.png)
![Tablet Tab example](https://user-images.githubusercontent.com/35155833/117872152-323fbe00-b253-11eb-8643-f4d733d4aa0c.png)
![Large screen Tab example](https://user-images.githubusercontent.com/35155833/117872150-310e9100-b253-11eb-8ccb-35ef12e38644.png)

**Comment by ianmcburnie** [comment]
Changes merged to 13.0.0 branch.
