### ISSUE TITLE
typography: design system updates (EVO)

### ISSUE THREAD

**Issue by rbascue** [eBay/skin#1446]
We’ve added an additional type size for marketing banners on large screens.

46px with 52px line-height

![dWeb example](https://user-images.githubusercontent.com/35155833/118538570-37918280-b703-11eb-832d-68130734ee5a.png)
![Specs](https://user-images.githubusercontent.com/35155833/118538578-3a8c7300-b703-11eb-8a4e-b0e145606511.png)

**Comment by ianmcburnie** [comment]
Changes merged to 13.0.0 branch. Closing.
