### ISSUE TITLE
notices: design system updates (EVO)

### ISSUE THREAD

**Issue by rbascue** [eBay/skin#1447]
We’re updating alerts and guidance to simplify their appearance. We’re removing 6.5 variants with secondary buttons and aligning all to use a text-only action style. The entire alert is actionable and should strive for a single action per alert. Icons are encouraged but not required.

[Source file](https://www.figma.com/file/IaJpngfyTXoM0wDid0MkkI/?node-id=20%3A2)

![Delta](https://user-images.githubusercontent.com/35155833/118563381-4e47d180-b723-11eb-9d22-17abaa4ae52f.png)
![Specs](https://user-images.githubusercontent.com/35155833/118563394-5273ef00-b723-11eb-828f-80527aba8ae5.png)
![Variants](https://user-images.githubusercontent.com/35155833/118563397-53a51c00-b723-11eb-8123-dc17ec1ccf1b.png)
![Android](https://user-images.githubusercontent.com/35155833/118563407-56077600-b723-11eb-97ec-c37354f3474b.png)
![iOS](https://user-images.githubusercontent.com/35155833/118563411-57d13980-b723-11eb-99a3-0743ae23693d.png)
![dWeb](https://user-images.githubusercontent.com/35155833/118563413-59026680-b723-11eb-902e-57bed52224b8.png)

**Comment by ianmcburnie** [comment]
Most of the work is done, just need a follow up PR that will clean up & clarify titles.

**Comment by ianmcburnie** [comment]
Changes merged to 13.0.0
