### ISSUE TITLE
section-title: design system updates (EVO)

### ISSUE THREAD

**Issue by rbascue** [eBay/skin#1454]
We’re increasing the size of section headers to improve separation between sections. Small screens (below 600) will use large1 and larger screens(600+) will use large2.

[Documentation](https://www.figma.com/file/IaJpngfyTXoM0wDid0MkkI/?node-id=1856%3A13031)

![Delta](https://user-images.githubusercontent.com/35155833/119707572-271e8d80-be10-11eb-8e20-c46bb327c65f.png)
![Specs](https://user-images.githubusercontent.com/35155833/119707574-271e8d80-be10-11eb-9b71-eaf44d350866.png) 
![Home - Android - GS](https://user-images.githubusercontent.com/35155833/119707551-21c14300-be10-11eb-8604-9a8093984e33.png)
![Home - iOS - GS](https://user-images.githubusercontent.com/35155833/119707565-24bc3380-be10-11eb-8db4-44fed62db408.png)
![Home Portrait](https://user-images.githubusercontent.com/35155833/119707566-2554ca00-be10-11eb-834a-07f6ca1f5c9d.png)
![Galaxy Tab S6 Example](https://user-images.githubusercontent.com/35155833/119707570-2685f700-be10-11eb-8438-b7bffc2a94ef.png)

**Comment by ianmcburnie** [comment]
Changes merged to 13.2.0 branch.
