### ISSUE TITLE
icon: update rating star (EVO)

### ISSUE THREAD

**Issue by rbascue** [eBay/skin#1473]
UPDATE: The scope of this issue is for existing individual star icon updates only. For the new star rating module, go here: #1599 

### The star icon is being updated to provide a sharper, cleaner look.

[Source](https://www.figma.com/file/IaJpngfyTXoM0wDid0MkkI/?node-id=33%3A0)

[Rating stars.zip](https://github.com/eBay/skin/files/6666024/Rating.stars.zip)

![image](https://user-images.githubusercontent.com/35155833/122298940-36927300-ceb2-11eb-8421-fd03c099aeb9.png)

![image](https://user-images.githubusercontent.com/35155833/122303709-cfc48800-ceb8-11eb-9b36-33b896c2e3c7.png)

![image](https://user-images.githubusercontent.com/35155833/122303313-385f3500-ceb8-11eb-8fcd-feb50dd9b509.png)

![image](https://user-images.githubusercontent.com/35155833/122303364-4614ba80-ceb8-11eb-9ed9-701edc66e64c.png)

**Comment by ianmcburnie** [comment]
Changes merged to 13.2.0 branch.
