### ISSUE TITLE
using floating-label in ebay-textbox adds margin-top: 14px

### ISSUE THREAD

**Issue by BhavinPatel04** [eBay/skin#1481]
using floating label in ebay-textbox adds margin-top: 14px
![image](https://user-images.githubusercontent.com/6559211/122828567-d9ccf900-d2b3-11eb-8c19-fba2cb597264.png)

**Comment by austingardner** [comment]
I'm not quite understanding what the issue is here. The example with `floatin-label--large` and `textbox__control--large` has `margin-top: 14px` already.

**Comment by BhavinPatel04** [comment]
Yeah, it shouldn't have `margin-top: 14px`.

**Comment by ianmcburnie** [comment]
Hm, this margin-top is possibly a leftover from the previous incarnation of floating-label that floated above the textbox. @agliga?

**Comment by austingardner** [comment]
Had to revert the fix, caused issues with ebay-ui. We will have to look into this more

**Comment by ianmcburnie** [comment]
This is fixed in 12.x
