### ISSUE TITLE
Update color of quick filter selected state

### ISSUE THREAD

**Issue by rbascue** [eBay/skin#1502]
To improve accessibility and consistency moving forward with Evolution, we're updating the selected state of quick filters to use grey 2 instead of the bespoke purple. This will also help simplify our color palette by removing this bespoke purple.

![Delta](https://user-images.githubusercontent.com/35155833/124170338-2656c800-da5c-11eb-8e65-e9eddb2feb5d.png)
![Specs](https://user-images.githubusercontent.com/35155833/124170346-28208b80-da5c-11eb-8926-1aae13403bb3.png)
![Variants](https://user-images.githubusercontent.com/35155833/124170349-28b92200-da5c-11eb-95b0-15e92ba6bdbf.png)

**Comment by ianmcburnie** [comment]
Merged to 13.0.0
