### ISSUE TITLE
Update dropdown list button to include inline label

### ISSUE THREAD

**Issue by rbascue** [eBay/skin#1504]
We are updating the dropdown button to provide a label within the container.

[Figma reference](https://www.figma.com/file/IaJpngfyTXoM0wDid0MkkI/?node-id=2219%3A23359)

![Delta](https://user-images.githubusercontent.com/35155833/124995537-5ffb7600-dffc-11eb-85b5-93c9ba4a2409.png)

![Variants](https://user-images.githubusercontent.com/35155833/124995401-2dea1400-dffc-11eb-859d-12efa4f848c9.png)

![Mobile](https://user-images.githubusercontent.com/35155833/124984928-a4801500-dfee-11eb-9204-82474c299b3b.png)

![Desktop](https://user-images.githubusercontent.com/35155833/124985000-c11c4d00-dfee-11eb-9d2e-a19cc6494f76.png)

**Comment by ianmcburnie** [comment]
One step ahead of you :-) But I guess we can make this the defacto/default now. Cheers!

![Screen Shot 2021-07-08 at 3 00 34 PM](https://user-images.githubusercontent.com/38065/124996155-5292bb80-dffd-11eb-9b5d-4be6384a4bd0.png)

**Comment by rbascue** [comment]
Excellent! Sounds like this can be closed then.

**Comment by ianmcburnie** [comment]
Merged to 13.0.0
