### ISSUE TITLE
Darken stroke on form fields to improve contrast

### ISSUE THREAD

**Issue by rbascue** [eBay/skin#1507]
We're updating the stroke on form fields to improve contrast and visibility. The current stroke color is using grey 2 (#E5E5E5) and will be updated to #949494. The color is bespoke but will only be used for form strokes at this point in time.

![Delta](https://user-images.githubusercontent.com/35155833/125334771-9ee14280-e300-11eb-81cf-014d1db3d3ea.png)

**Comment by ianmcburnie** [comment]
Changed merged to 13.0.0 branch
