### ISSUE TITLE
pagination: design system updates Part 2 of 3 (EVO)

### ISSUE THREAD

**Issue by ianmcburnie** [eBay/skin#1519]
Part 2 adds the overflow interaction and documentation of new states/use-cases.

Part 1 here: https://github.com/eBay/skin/issues/1435

![Specs](https://user-images.githubusercontent.com/35155833/117870996-b85b0500-b251-11eb-9119-64917ad049a6.png)

**Comment by rbascue** [comment]
Noticed the overflow specs here need to be updated. Documentation has been filled out with more examples.
![image](https://user-images.githubusercontent.com/35155833/127071580-bfb06338-6274-410a-b243-193a0b35fd80.png)

**Comment by rbascue** [comment]
![image](https://user-images.githubusercontent.com/35155833/127071645-59fa7a98-94f4-4547-87c3-d8ae3acdd8fe.png)

**Comment by ianmcburnie** [comment]
Changes merged to 13.0.0
