### ISSUE TITLE
Update all to Market Sans

### ISSUE THREAD

**Issue by rbascue** [eBay/skin#1544]
All part of the Market Sans saga. MS Redux.

We've identified three cases so far:
- Text using light, regular, medium weight will convert to MS Reg.
- Text using semibold weight will convert to MS Bold.
- Text using italics will need to fall back to system font still (primary use: converted currency on SRP, VI).

[New mappings](https://www.figma.com/file/jckQW9jV5sEtoZSoR9pHly/?node-id=0%3A1)

**Comment by ianmcburnie** [comment]
Done.
