### ISSUE TITLE
Add payment option icons

### ISSUE THREAD

**Issue by rbascue** [eBay/skin#1554]
The global icon assets used for payment methods will need to be added to the library to ensure consistency across domains.

Attachment with optimized icons coming soon.

**Comment by rbascue** [comment]
[payment_icons_202116090859.zip](https://github.com/eBay/skin/files/7179286/payment_icons_202116090859.zip)

**Comment by rbascue** [comment]
Also located in the [library](https://www.figma.com/file/zEBdEhbonrBOGzZ0fXzWvM/eBay-Design-System?node-id=34669%3A40529)

**Comment by ianmcburnie** [comment]
This is put on hold for legal reasons.
