### ISSUE TITLE
New Module: Searchbox

### ISSUE THREAD

**Issue by ianmcburnie** [eBay/skin#1565]
Seen this "search box" appearing a few times in recent mocks (apologies for bad image quality/capture from zoom). It's basically a search specific version of our combobox with list autocomplete, with extra rounded corners. Probably worthy of being its own standalone module.

![Screen Shot 2021-09-29 at 4 00 41 PM](https://user-images.githubusercontent.com/38065/135360057-9addb53e-a832-45e8-83e5-0a909bb3f58e.png)

![Screen Shot 2021-09-29 at 4 06 19 PM](https://user-images.githubusercontent.com/38065/135360429-b96d6075-15c5-4420-886d-98ab08de5a6f.png)

NOTE: search icon should remain visible at all times, even when it has focus.

UPDATE: here's another mock I've seen recently (note those + icons seem highly redundant in terms of ux):
 
<img width="581" alt="Screenshot 2023-11-30 at 2 48 44 PM" src="https://github.com/eBay/skin/assets/38065/e77e5075-1377-4965-ba55-c336b4bb67fe">

**Comment by PrashantAshok** [comment]
@ianmcburnie - Curious, since we are already building this as part of our project(even met you for a11y), wondering if we can include it as part of eBayUI/Skin?

**Comment by ianmcburnie** [comment]
Yes, we can check in with design team to see where they are at with this on their side.
