### ISSUE TITLE
Listbox-Button: add modifier to show compact label at top instead of on left

### ISSUE THREAD

**Issue by ianmcburnie** [eBay/skin#1571]
This will help bifurcate form dropdowns from non-form dropdown

**Comment by rbascue** [comment]
I'm working on getting this on Playbook, but I've updated the [dropdown documentation](https://www.figma.com/file/zEBdEhbonrBOGzZ0fXzWvM/eBay-Design-System?node-id=37272%3A40019) and [stickersheet](https://www.figma.com/file/zEBdEhbonrBOGzZ0fXzWvM/eBay-Design-System?node-id=40884%3A48665) to add a variant with the label floating.

**Comment by rbascue** [comment]
![image](https://user-images.githubusercontent.com/35155833/144112343-1f4b6935-4d86-4ca6-9874-a6956e6c0a10.png)

**Comment by rbascue** [comment]
![image](https://user-images.githubusercontent.com/35155833/144282419-ad55f39a-2241-4f38-86bb-6ea89df5e365.png)

**Comment by agliga** [comment]
Duplicate issue https://github.com/eBay/skin/issues/1555
This has been fixed in `13.2.0`
