### ISSUE TITLE
Validate website on PR fails

### ISSUE THREAD

**Issue by agliga** [eBay/skin#1574]
<img width="1634" alt="Screen Shot 2021-10-08 at 9 10 04 AM" src="https://user-images.githubusercontent.com/1755269/136589211-462f4bd6-5ad3-4a0e-adf5-3e50f8a10a1c.png">

**Comment by ianmcburnie** [comment]
Looks like a new automated build & deploy action was added recently:

https://github.com/eBay/skin/actions/workflows/pages/pages-build-deployment

Seems like we can replace the bulk of our workflow script with this pre-made/official one:

https://github.com/actions/jekyll-build-pages

Example run:

https://github.com/eBay/skin/runs/5149873717?check_suite_focus=true

**Comment by ianmcburnie** [comment]
Fixed in 13.5.0 branch.
