### ISSUE TITLE
Tech Debt: remove various stylelint overrides

### ISSUE THREAD

**Issue by ianmcburnie** [eBay/skin#1591]
We have a fair few of these building up now. To improve the hygiene of the code, we should try and remove as many as we can. Some of them are little hairier than others (button, for example) and so those might be best left for a major release.

![Screen Shot 2021-10-26 at 2 04 04 PM](https://user-images.githubusercontent.com/38065/138960859-00780448-5f19-4c2a-94fa-0a92eec43d95.png)

**Comment by ianmcburnie** [comment]
Related ticket: https://github.com/eBay/skin/issues/1611

**Comment by agliga** [comment]
> With the last dev deps update there were multiple rules in stylelint that were activated by default. I turned them off, but we should probably revisit our rules and clean up our code to follow standards.
> List of rules:
```
    "at-rule-empty-line-before": null,
    "comment-empty-line-before": null,
    "indentation": null,
    "no-descending-specificity": null,
    "no-duplicate-selectors": null,
    "declaration-block-no-duplicate-properties": null,
    "rule-empty-line-before": null,
    "color-function-notation": null,
    "declaration-block-no-redundant-longhand-properties": null,
    "number-max-precision": null,
    "shorthand-property-no-redundant-values": null,
    "property-no-vendor-prefix": null,
    "selector-no-vendor-prefix": null,
    "selector-class-pattern": null,
    "alpha-value-notation": null,
    "value-no-vendor-prefix": null
```
> Some conflict with the CSS but we can turn on/off them for css/less files as needed using the overrides key

**Comment by ianmcburnie** [comment]
This might come in useful for the "selector-class-pattern" violation:

https://www.npmjs.com/package/stylelint-selector-bem-pattern

**Comment by ianmcburnie** [comment]
Closing. I think we are in good shape.
