### ISSUE TITLE
star-rating: new module (interactive & non-interactive)

### ISSUE THREAD

**Issue by rbascue** [eBay/skin#1599]
As a user, I want to be able to leave a rating out of 5 stars quickly and easily.

Currently, teams are rolling their own star rating components. Some are using the grey or empty star asset for an unselected state, which is neither accessible nor correct. We have explorations using the inactive undetermined asset at black for an unselected state. This is accessible and common throughout other apps. We should finalize, document, and hand this off to eBayUI to standardize throughout the experience.

[PLATUX Jira ticket](https://jirap.corp.ebay.com/browse/PLATUX-626)

![image](https://user-images.githubusercontent.com/35155833/142288873-e4c0ef7b-9998-49d3-a91d-3ad312be53ea.png)

**Comment by rbascue** [comment]
This pattern needs documentation and further exploration for interaction design. Creating issue now to track.

**Comment by ianmcburnie** [comment]
We have some guidance here: https://ebay.github.io/mindpatterns/input/star-rating/

**Comment by ianmcburnie** [comment]
The non-interactive portion will be available in 13.2.0. We'll tackle the interactive bit in a future release.

![Screen Shot 2021-12-03 at 1 49 36 PM](https://user-images.githubusercontent.com/38065/144677360-f4b9cdcc-9b8f-4791-b6fa-8878295ba20e.png)

**Comment by ianmcburnie** [comment]
Going to close this issue and create another issue for the remaining interactive portion. Helps us to track better.
