### ISSUE TITLE
progress-stepper: updates to "current" state

### ISSUE THREAD

**Issue by rbascue** [eBay/skin#1600]
We have received feedback about the progress stepper's _current_ state being confusing. The state uses a filled visual indicator that appears similar to the _complete_ state. We have revisited and will be updating the visual style to only fill on completion. In-progress, insufficient, and blocked statuses will use outlined indicators instead. We will also remove the numbered labels.

**Comment by rbascue** [comment]
[Reference](https://www.figma.com/file/zEBdEhbonrBOGzZ0fXzWvM/eBay-Design-System?node-id=40587%3A74805)

### Variant matrix
![image](https://user-images.githubusercontent.com/35155833/142339368-831f6e14-8c9e-4d58-9d9a-46d2ae4dd781.png)

**Comment by rbascue** [comment]
![image](https://user-images.githubusercontent.com/35155833/142339439-b3c30234-af79-4005-a774-3b0ea8b20b9f.png)

**Comment by agliga** [comment]
Done in 13.2.0
