### ISSUE TITLE
infotip/tooltip: icon has a gray background color

### ISSUE THREAD

**Issue by PrashantAshok** [eBay/skin#1604]
Now that Skin 13 has background-color and focus/hover state https://github.com/eBay/skin/blob/v13.1.1/src/less/icon-button/base/icon-button.less#L32-L33 - is causing a background to show up for infotip and tooltip - reproducible in storybook. Looks like a bug?

<img width="106" alt="Screen Shot 2021-11-23 at 11 03 59 AM" src="https://user-images.githubusercontent.com/5200733/143087626-4df72a82-daad-499f-9ede-5454350b89df.png">

**Comment by ianmcburnie** [comment]
Ah yes. We forgot to update the Skin storybook with the `icon-btn--transparent` class. Will fix.
