### ISSUE TITLE
Dialog: reduced outline when the title is long

### ISSUE THREAD

**Issue by PrashantAshok** [eBay/skin#1612]
<img width="650" alt="Screen Shot 2021-12-08 at 14 44 34" src="https://user-images.githubusercontent.com/5200733/145493208-b87f7fc2-4c5e-45a3-b163-ee7ba1fdad39.png">
<img width="552" alt="Screen Shot 2021-12-09 at 3 07 22 PM" src="https://user-images.githubusercontent.com/5200733/145493212-f029860b-a2df-4f2c-9df1-02186374aad1.png">

looks like something to do with `outline-offet` on close icon.

**Comment by agliga** [comment]
This seems to be the same issue as https://github.com/eBay/skin/issues/1632 and https://github.com/eBay/skin/issues/1636 combined. 
Closing as duplicate. https://github.com/eBay/skin/issues/1636 has been fixed and https://github.com/eBay/skin/issues/1632 will be fixed soon.
