### ISSUE TITLE
primitives: update spacing tokens to use proportional labeling

### ISSUE THREAD

**Issue by rbascue** [eBay/skin#1623]
The design system team is starting to integrate tokens into the system, starting at the source Figma file. 

The current token system in Skin uses a "t-shirt sizing" labeling style. Unfortunately, this style isn't scalable, especially when adding values between others. 

Instead, we can move to a proportional labeling style anchored to our base 8px grid, where 8px is 100% and is represented as `spacing-100` in the system. All of the other spacing values can be derived from there.

Example
![image](https://user-images.githubusercontent.com/35155833/146845203-953763a9-c285-49af-a43d-4bb8c4510d4d.png)

**Comment by ianmcburnie** [comment]
A subset of issue https://github.com/eBay/skin/issues/1646 which has latest specs/links.

**Comment by ianmcburnie** [comment]
Done in 13.6.0 branch
