### ISSUE TITLE
textbox: postfix-icon has incorrect sizing

### ISSUE THREAD

**Issue by agliga** [eBay/skin#1624]
Original issue stated here: https://github.com/eBay/ebayui-core/issues/1580

Seems like on skin site textbox examples shows the non transparent icon button:
<img width="261" alt="Screen Shot 2021-12-21 at 3 21 40 PM" src="https://user-images.githubusercontent.com/1755269/147010644-489d430c-0ad2-4688-88a4-5cab8c10252c.png">

Also the outline seems a bit big. Might want to do `outline-offset: -6px;`
<img width="246" alt="Screen Shot 2021-12-21 at 3 23 32 PM" src="https://user-images.githubusercontent.com/1755269/147010687-b470d4ca-50e8-4428-a76b-02533736e66a.png">

**Comment by ianmcburnie** [comment]
I believe both issues are addressed in #1626. Austin can confirm and close.

**Comment by agliga** [comment]
Austin confirmed we can close. Should be resolved by other issue
