### ISSUE TITLE
spinner (Firefox only): keeps making request to fetch spinner-<size>.svg

### ISSUE THREAD

**Issue by PrashantAshok** [eBay/skin#1628]
If you load a page with the spinner, Firefox keeps making network requests to fetch the `spinner-<size>.svg` file, you can repro this issue in Skin https://ebay.github.io/skin/ or have a plain component like this
```
class {
    onCreate() {
        this.state = {
            show: false
        };
    }
    toggle() {
        this.state.show = !this.state.show;
    }
}

<button on-click("toggle")>Toggle</button>

<if(state.show)>
    <ebay-progress-spinner aria-label="Busy"/>
</if>
```

<img width="991" alt="Screen Shot 2022-01-04 at 5 16 43 PM" src="https://user-images.githubusercontent.com/5200733/148145441-006e2b94-1f94-4d6c-97ef-f4aa2d8281b6.png">

**Comment by agliga** [comment]
Should be fixed now in in `13.4.0-0` https://github.com/eBay/skin/issues/1648
