### ISSUE TITLE
button: partially disabled still shows hover color changes

### ISSUE THREAD

**Issue by agliga** [eBay/skin#1637]
Old versions of skin had partially disabled buttons not show color changes and background changes on hover.
Seems like it's due to this line: https://github.com/eBay/skin/blob/master/src/less/button/base/button.less#L82

Is `aria-live=polite` required when `aria-disabled` is true? If so this needs to be documented in skin site (and changed in ebayui).
Or should we change the not to only include `aria-disabled`?

## Screenshot
<img width="1150" alt="Screen Shot 2022-01-13 at 12 05 51 PM" src="https://user-images.githubusercontent.com/1755269/149401541-2ae1917a-cab4-4d17-8189-d22ab9b5a310.png">

**Comment by agliga** [comment]
Assigning to @ianmcburnie for more information

**Comment by ianmcburnie** [comment]
Hover states should not be showing for partially disabled buttons. Aria-live polite is not required for a partially disabled button (it is only relevant to loading buttons).

It's certainly getting a little confusing, I know. So I tried to keep track of the rules here: 

https://github.com/eBay/skin/blob/master/src/less/button/base/button.less#L3

Feel free to update.

**Comment by agliga** [comment]
So for this selector:
```
button.btn--primary:not([disabled]):not([aria-live="polite"][aria-disabled="true"]),
```
We can remove aria-live polite? Or split it up and do `:not(aria-live=polite):not(aria-disabled=true)`?
