### ISSUE TITLE
Drawer Dialog: Drawer Dialog Footer, should we bring it back?

### ISSUE THREAD

**Issue by abiyasa** [eBay/skin#1639]
I noticed that the Drawer Dialog Footer has been removed from Skin 13 (see https://github.com/eBay/skin/pull/1531). 

My question or concern is, how should we do an expanded Drawer dialog on mweb (95% screen height) which shows action buttons sticked on the bottom? Does this mean we have to put everything inside Drawer's main and layout everything manually with flexbox?

I just check that ebayui-core still have [`@footer` for Drawer Dialog](https://github.com/eBay/ebayui-core/tree/v8.3.0/src/components/ebay-drawer-dialog). The component renders class `drawer-dialog__footer` which I think does not work properly on mweb. The footer button has spacing problem as seen on the [storybook](https://ebay.github.io/ebayui-core/?path=/story/ebay-drawer-dialog--standard)):

![drawer-dialog-footer](https://user-images.githubusercontent.com/1072047/150108910-fcc81123-7642-4e11-bd24-0e4d2a3eeb86.png)

![Screenshot 2022-01-19 at 11 04 52](https://user-images.githubusercontent.com/1072047/150108930-474bd7d0-f5ff-42b3-a6a8-9ec337f99dda.png)

**Comment by agliga** [comment]
We will check to see if we can readd it. 
Looks like this spec has it https://www.figma.com/file/t7ru32OPWEtLWjM7L8XgYe/Modality?node-id=2237%3A53194

**Comment by abiyasa** [comment]
Thanks a lot all for fixing this issue 🎉
