### ISSUE TITLE
SKIN issue -  progress spinner svg url is broken (https://jirap.corp.ebay.com/browse/MESHOVW-3870)

### ISSUE THREAD

**Issue by charank337** [eBay/skin#1651]
https://jirap.corp.ebay.com/browse/MESHOVW-3870

The progress spinner svg url is broken on prod but working fine on local
refer to screen shots 
 
broken url : data:image/svg xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIGZpbGw9Im5vbmUiIHZpZXdCb3g9IjAgMCA1NiA1NiI+PHBhdGggZmlsbD0iI0U1RTVFNSIgZD0iTTU2IDI4YzAgMTUuNDY0LTEyLjUzNiAyOC0yOCAyOFMwIDQzLjQ2NCAwIDI4IDEyLjUzNiAwIDI4IDBzMjggMTIuNTM2IDI4IDI4ek00LjAwNCAyOGMwIDEzLjI1MjYgMTAuNzQzNCAyMy45OTYgMjMuOTk2IDIzLjk5NlM1MS45OTYgNDEuMjUyNiA1MS45OTYgMjggNDEuMjUyNiA0LjAwNCAyOCA0LjAwNCA0LjAwNCAxNC43NDc0IDQuMDA0IDI4eiIvPjxtYXNrIGlkPSJhIiB3aWR0aD0iNTYiIGhlaWdodD0iNTYiIHg9IjAiIHk9IjAiIG1hc2tVbml0cz0idXNlclNwYWNlT25Vc2UiPjxwYXRoIGZpbGw9IiNFNUU1RTUiIGQ9Ik01NiAyOGMwIDE1LjQ2NC0xMi41MzYgMjgtMjggMjhTMCA0My40NjQgMCAyOCAxMi41MzYgMCAyOCAwczI4IDEyLjUzNiAyOCAyOHpNNC4wMDQgMjhjMCAxMy4yNTI2IDEwLjc0MzQgMjMuOTk2IDIzLjk5NiAyMy45OTZTNTEuOTk2IDQxLjI1MjYgNTEuOTk2IDI4IDQxLjI1MjYgNC4wMDQgMjggNC4wMDQgNC4wMDQgMTQuNzQ3NCA0LjAwNCAyOHoiLz48L21hc2s+PGcgZmlsdGVyPSJ1cmwoI2ZpbHRlcjBfZCkiIG1hc2s9InVybCgjYSkiPjxwYXRoIGZpbGw9IiMzNjY1RjMiIGQ9Ik01My45MzQ3IDI5LjgxMzVjMS4xMDMuMDc3MiAyLjA2NzEtLjc1NTEgMi4wNjUzLTEuODYwOEEyOC4wMDA5IDI4LjAwMDkgMCAwMDMxLjcwMzIuMjQ2YTI4IDI4IDAgMDAtMTEuOTM3OC45OTIzYy0xLjA1NjguMzI1MS0xLjU2NjcgMS40OTIzLTEuMTY2OSAyLjUyMzEuMzk5OCAxLjAzMDkgMS41NTggMS41MzM4IDIuNjE4NSAxLjIyMTJhMjMuOTk2MyAyMy45OTYzIDAgMDEzMC43NzY4IDIyLjY5MDZjLjAxNSAxLjEwNTYuODM3OSAyLjA2MzIgMS45NDA5IDIuMTQwM3oiLz48L2c+PGRlZnM+PGZpbHRlciBpZD0iZmlsdGVyMF9kIiB3aWR0aD0iNTUuNTM3NCIgaGVpZ2h0PSI0Ny44MTg1IiB4PSI5LjQ2MjYiIHk9Ii05IiBjb2xvci1pbnRlcnBvbGF0aW9uLWZpbHRlcnM9InNSR0IiIGZpbHRlclVuaXRzPSJ1c2VyU3BhY2VPblVzZSI+PGZlRmxvb2QgZmxvb2Qtb3BhY2l0eT0iMCIgcmVzdWx0PSJCYWNrZ3JvdW5kSW1hZ2VGaXgiLz48ZmVDb2xvck1hdHJpeCBpbj0iU291cmNlQWxwaGEiIHZhbHVlcz0iMCAwIDAgMCAwIDAgMCAwIDAgMCAwIDAgMCAwIDAgMCAwIDAgMTI3IDAiLz48ZmVPZmZzZXQvPjxmZUdhdXNzaWFuQmx1ciBzdGREZXZpYXRpb249IjQuNSIvPjxmZUNvbG9yTWF0cml4IHZhbHVlcz0iMCAwIDAgMCAwIDAgMCAwIDAgMCAwIDAgMCAwIDAgMCAwIDAgMC4xNCAwIi8+PGZlQmxlbmQgaW4yPSJCYWNrZ3JvdW5kSW1hZ2VGaXgiIHJlc3VsdD0iZWZmZWN0MV9kcm9wU2hhZG93Ii8+PGZlQmxlbmQgaW49IlNvdXJjZUdyYXBoaWMiIGluMj0iZWZmZWN0MV9kcm9wU2hhZG93IiByZXN1bHQ9InNoYXBlIi8+PC9maWx0ZXI+PC9kZWZzPjwvc3ZnPg==

working url: data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIGZpbGw9Im5vbmUiIHZpZXdCb3g9IjAgMCA1NiA1NiI+PHBhdGggZmlsbD0iI0U1RTVFNSIgZD0iTTU2IDI4YzAgMTUuNDY0LTEyLjUzNiAyOC0yOCAyOFMwIDQzLjQ2NCAwIDI4IDEyLjUzNiAwIDI4IDBzMjggMTIuNTM2IDI4IDI4ek00LjAwNCAyOGMwIDEzLjI1MjYgMTAuNzQzNCAyMy45OTYgMjMuOTk2IDIzLjk5NlM1MS45OTYgNDEuMjUyNiA1MS45OTYgMjggNDEuMjUyNiA0LjAwNCAyOCA0LjAwNCA0LjAwNCAxNC43NDc0IDQuMDA0IDI4eiIvPjxtYXNrIGlkPSJhIiB3aWR0aD0iNTYiIGhlaWdodD0iNTYiIHg9IjAiIHk9IjAiIG1hc2tVbml0cz0idXNlclNwYWNlT25Vc2UiPjxwYXRoIGZpbGw9IiNFNUU1RTUiIGQ9Ik01NiAyOGMwIDE1LjQ2NC0xMi41MzYgMjgtMjggMjhTMCA0My40NjQgMCAyOCAxMi41MzYgMCAyOCAwczI4IDEyLjUzNiAyOCAyOHpNNC4wMDQgMjhjMCAxMy4yNTI2IDEwLjc0MzQgMjMuOTk2IDIzLjk5NiAyMy45OTZTNTEuOTk2IDQxLjI1MjYgNTEuOTk2IDI4IDQxLjI1MjYgNC4wMDQgMjggNC4wMDQgNC4wMDQgMTQuNzQ3NCA0LjAwNCAyOHoiLz48L21hc2s+PGcgZmlsdGVyPSJ1cmwoI2ZpbHRlcjBfZCkiIG1hc2s9InVybCgjYSkiPjxwYXRoIGZpbGw9IiMzNjY1RjMiIGQ9Ik01My45MzQ3IDI5LjgxMzVjMS4xMDMuMDc3MiAyLjA2NzEtLjc1NTEgMi4wNjUzLTEuODYwOEEyOC4wMDA5IDI4LjAwMDkgMCAwMDMxLjcwMzIuMjQ2YTI4IDI4IDAgMDAtMTEuOTM3OC45OTIzYy0xLjA1NjguMzI1MS0xLjU2NjcgMS40OTIzLTEuMTY2OSAyLjUyMzEuMzk5OCAxLjAzMDkgMS41NTggMS41MzM4IDIuNjE4NSAxLjIyMTJhMjMuOTk2MyAyMy45OTYzIDAgMDEzMC43NzY4IDIyLjY5MDZjLjAxNSAxLjEwNTYuODM3OSAyLjA2MzIgMS45NDA5IDIuMTQwM3oiLz48L2c+PGRlZnM+PGZpbHRlciBpZD0iZmlsdGVyMF9kIiB3aWR0aD0iNTUuNTM3NCIgaGVpZ2h0PSI0Ny44MTg1IiB4PSI5LjQ2MjYiIHk9Ii05IiBjb2xvci1pbnRlcnBvbGF0aW9uLWZpbHRlcnM9InNSR0IiIGZpbHRlclVuaXRzPSJ1c2VyU3BhY2VPblVzZSI+PGZlRmxvb2QgZmxvb2Qtb3BhY2l0eT0iMCIgcmVzdWx0PSJCYWNrZ3JvdW5kSW1hZ2VGaXgiLz48ZmVDb2xvck1hdHJpeCBpbj0iU291cmNlQWxwaGEiIHZhbHVlcz0iMCAwIDAgMCAwIDAgMCAwIDAgMCAwIDAgMCAwIDAgMCAwIDAgMTI3IDAiLz48ZmVPZmZzZXQvPjxmZUdhdXNzaWFuQmx1ciBzdGREZXZpYXRpb249IjQuNSIvPjxmZUNvbG9yTWF0cml4IHZhbHVlcz0iMCAwIDAgMCAwIDAgMCAwIDAgMCAwIDAgMCAwIDAgMCAwIDAgMC4xNCAwIi8+PGZlQmxlbmQgaW4yPSJCYWNrZ3JvdW5kSW1hZ2VGaXgiIHJlc3VsdD0iZWZmZWN0MV9kcm9wU2hhZG93Ii8+PGZlQmxlbmQgaW49IlNvdXJjZUdyYXBoaWMiIGluMj0iZWZmZWN0MV9kcm9wU2hhZG93IiByZXN1bHQ9InNoYXBlIi8+PC9maWx0ZXI+PC9kZWZzPjwvc3ZnPg==

broken on prod screenshot
Screen Shot 2022-01-19 at 11.36.54 AM.png

**Comment by agliga** [comment]
Duplicate issue

https://github.com/eBay/skin/issues/1648
