### ISSUE TITLE
Buttons: Update secondary button background color to transparent

### ISSUE THREAD

**Issue by abiyasa** [eBay/skin#1657]
Based on [discussion with Design team](https://ebay-eng.slack.com/archives/C72MEP885/p1643241658076300) and [Figma file](https://www.figma.com/file/c9dVJUvu9B9nT4uzXnfBXf/DS%2FEvolution?node-id=49%3A27312), the background color for secondary button should be transparent. 

<img width="502" alt="secondary-buttons" src="https://user-images.githubusercontent.com/1072047/151839145-aea1bac2-bb6c-4479-b4e7-36fe315b103b.png">

On Skin v13.3.0, the background color is currently set to white `#fff`, at least confirmed on the document page.

I check the code  on https://github.com/eBay/skin/blob/v13.3.1/src/less/button/base/button.less#L132, and it uses `color-background-default` since the token `btn-secondary-background-color` is not defined yet.

**Comment by agliga** [comment]
We want to confirm with design that this won't lead to color contrast issues
