### ISSUE TITLE
Select with aria-invalid=true doesn't show the border

### ISSUE THREAD

**Issue by HenriqueLimas** [eBay/skin#1674]
Invalid select elements (aria-invalid=true) are not showing the border

Example:

```html
<select aria-label="Select demo" name="options" aria-invalid="true">
  <option value="item1">Option 1</option>
  <option value="item2" selected="">Option 2</option>
  <option value="item3">Option 3</option>
</select>
```

**Expected** (same as textbox):

<img width="214" alt="Screen Shot 2022-02-17 at 4 47 08 PM" src="https://user-images.githubusercontent.com/2222191/154596159-6c31d7ed-4d16-47d6-ae37-a9d360623a1e.png">

**Actual**:

<img width="214" alt="Screen Shot 2022-02-17 at 4 33 37 PM" src="https://user-images.githubusercontent.com/2222191/154595937-4cc1d84a-81a0-436d-b37f-550be10b329f.png">

**Comment by agliga** [comment]
Need to change this line: https://github.com/eBay/skin/blob/master/src/less/select/base/select.less#L89
`color-status-invalid` to `color-status-attention`
