### ISSUE TITLE
split-button: fixes when integrating ebayui

### ISSUE THREAD

**Issue by agliga** [eBay/skin#1690]
Split button has some bugs found when integrating component

* Layout is wrong (markup the same, but I think it's due to the parent being a flexible container)
<img width="208" alt="Screen Shot 2022-03-08 at 7 44 33 AM" src="https://user-images.githubusercontent.com/1755269/157272827-fea92757-fe1b-4ced-9d58-856112ef044f.png">
Fix would be to do the following:
Add `.split-button { display: inline-flex; }` style and change negative margin on split-end to be only `-1px` (so it doesn't have the thicker border)
* Dropdown shows starting from the button.
<img width="452" alt="Screen Shot 2022-03-08 at 7 40 22 AM" src="https://user-images.githubusercontent.com/1755269/157273085-d1d5f9c1-d682-4a99-8ab3-c2262a2e5d4b.png">
Fix would be to set the dropdown to be reversed (will need doc changes in skin for this)

**Comment by agliga** [comment]
Also split button does not work when the first split is a an achor tag with `href`.
Will need to make `split-start` to support anchor tag as well as button. 
<img width="221" alt="Screen Shot 2022-03-15 at 11 02 01 AM" src="https://user-images.githubusercontent.com/1755269/158442587-da4e729d-d4a2-4876-8105-cbbeb49596a7.png">

**Comment by ianmcburnie** [comment]
Merged to 13.6.0. Closing
