### ISSUE TITLE
textarea: floating label overlaps with textarea value on scroll

### ISSUE THREAD

**Issue by Vaishnavi-Thiyagaraj** [eBay/skin#1698]
Textarea value text overlaps with floating label on scroll(refer screen recording below). The design should have a mask to prevent text overlaps.

https://user-images.githubusercontent.com/49796069/158453798-2c041088-9b4e-4742-9006-cb83ffd6c3d3.mov

**Comment by agliga** [comment]
Reopening, this fix needs to be reverted because it's causing a lot of problems in edge cases (like autocomplete fields)

We will need to probably add a `floating-label--textarea` class or something to fix this only on text area (since this is a shared component)
