### ISSUE TITLE
Text Using Market Sans Displays Fallback Font

### ISSUE THREAD

**Issue by tian-li** [eBay/skin#1699]
Hi ebay skin team,

Our team is using Market Sans font and noticing the text is displayed with the fallback font pretty often. We learned that `font-display: optional` does not wait for the font and swap. But this happens even when the next time loading without clear cache. Is there any solution or at least make it happen less often?

The text displayed in Times New Roman are supposed to be Market Sans.

![image](https://user-images.githubusercontent.com/11455447/158896342-cd683848-dc45-49da-97bf-1f4c37b1f230.png)

**Comment by uachladi** [comment]
Hi Team, We see this issue frequently. Do we have any solution for this?
