### ISSUE TITLE
Panel-Dialog: Design Updates

### ISSUE THREAD

**Issue by rbascue** [eBay/skin#1708]
The panel is a sheet that presents from the right. We are codifying a component for use throughout the product for input and read-only content. Panels are used on larger screens (>600px) and convert to fullscreen dialog layout on smaller screens (<600px).
Variants of the main component and its elements are located to the right of the documentation in Figma.

[Guidelines in library staging branch](https://www.figma.com/file/qsHoAF69J7I85JPOAsnjkR/%5BUpdate%5D-Panel-pattern?node-id=52817%3A79828)

![image-2022-03-29-17-48-54-314](https://user-images.githubusercontent.com/35155833/160887690-86b55716-f3c1-47b3-a1b2-0331292ccf5c.png)

![image-2022-03-29-17-50-47-034](https://user-images.githubusercontent.com/35155833/160887696-5927c6d2-fbfb-471a-af83-4a454ceca5d0.png)

![image-2022-03-29-17-50-56-109](https://user-images.githubusercontent.com/35155833/160887698-d718ca44-df6c-470a-936b-f02382654393.png)

**Comment by ianmcburnie** [comment]
Hmm, just caught this:

> and convert to bottom sheets on smaller screens (<600px).

@rbascue I think this will require more discussion for responsive on desktop. We can't dynamically convert to a different _component_, we can only change layout.

**Comment by agliga** [comment]
> Hmm, just caught this:
> 
> 
> 
> > and convert to bottom sheets on smaller screens (<600px).
> 
> 
> 
> @rbascue I think this will require more discussion for responsive on desktop. We can't dynamically convert to a different _component_, we can only change layout.

I think it probably should be fine technically yes they're two components but they're very similar. Basically only the layout changes. 
It can be called something like panel dialog or we can think of another name. 
If its large we put it on the right side and animate from right
If its small we animate from bottom
I think the rest is pretty much the same. 
These can be done with media queries very easily. 
If there are other differences between then we can discuss but if not then i don't see why this should be a problem

**Comment by rbascue** [comment]
Yeah, I didn't intend to say a bottom sheet. It's a fullscreen dialog layout on smaller screens.

**Comment by agliga** [comment]
Non breaking code change. (possible visual breaking change) Should repurpose panel dialog to be fullscreen on mweb and smaller on dweb.
