### ISSUE TITLE
button: incorrect icon color for secondary disabled buttons (dark mode)

### ISSUE THREAD

**Issue by ArtBlue** [eBay/skin#1712]
When in dark mode, icons for disabled buttons don't have the correct color.

Actual:
<img width="552" alt="image" src="https://user-images.githubusercontent.com/1675667/161817879-3523b2f1-a4c5-4e4a-9d10-a996eb41d159.png">

Expected:
<img width="391" alt="image" src="https://user-images.githubusercontent.com/1675667/161818231-c9adf58f-6b01-4a4d-b0a4-651ba4de0448.png">

This issue is currently reproducible in prod.

**Comment by agliga** [comment]
Closing seems to be working:
https://opensource.ebay.com/skin/storybook/?path=/story/button-secondary--disabled
<img width="480" alt="Screen Shot 2022-10-19 at 3 04 31 PM" src="https://user-images.githubusercontent.com/1755269/196813426-eb2e7d48-075b-4b93-b183-6a06743beb82.png">
