### ISSUE TITLE
Focus Header: New Module

### ISSUE THREAD

**Issue by randybascue** [eBay/skin#1716]
We have finalized a simplified header component that can be used in particular focused experiences. The header links and structure may change, but the overall guidelines and reduction principles should remain the same.

The focus header keeps the logo aligned left and provides space on the right for up to 3 accessory actions. These actions can be icon buttons or tertiary buttons with text labels. It is not a modal element and should only be placed on a page. It can persist across multiple pages, but returns to the primary header component with the search bar upon exiting the focus experience.

The "Stand-alone page" component will be deprecated and removed.

[Guidelines](https://www.figma.com/file/ybqfN5SP7NZoTcmxBMzHik/?node-id=53874%3A81423)
[Specs](https://www.figma.com/file/ybqfN5SP7NZoTcmxBMzHik/?node-id=53874%3A81717)
[Master component](https://www.figma.com/file/ybqfN5SP7NZoTcmxBMzHik/?node-id=53874%3A80019)

![image](https://user-images.githubusercontent.com/35155833/162276585-f290043c-7d57-4e87-9c70-4775461815c0.png)
![image](https://user-images.githubusercontent.com/35155833/162276613-a7def594-4848-4578-afc6-eecfac08a4fc.png)

**Comment by ianmcburnie** [comment]
Could be a good candidate to use our [Page Grid](https://opensource.ebay.com/skin/#page-grid)! I guess we might want to provide working examples of it sitting on our grid, and not sitting on our grid.

**Comment by agliga** [comment]
Had a discussion offline
We need to figure out what the desired outcome should be
On mobile three icon buttons plus a tertiary button can truncate and overlap. 
So since we are mobile first we need to revisit this design to see what the right solution and usecases for these buttons are.

**Comment by ArtBlue** [comment]
Just to add to Andrew's comment, for fully responsive solutions, the mobile first approach would be helpful. Also the pessimistic approach that pushes layouts to its limits (layouts with worst-case scenarios). That should help inform our decision making for designs that stretch the interface (both literally and figuratively). 😄  Scaling down busy interfaces is much easier than scaling up interfaces that may already be at their limits.

**Comment by agliga** [comment]
Closing issue
