### ISSUE TITLE
icons: ebay-icons is not showing up when place inside @item of ebay-fake-menu-button

### ISSUE THREAD

**Issue by ZZS77** [eBay/skin#1717]
`<ebay-fake-menu-button
        a11y-text=content.get('moreOptions')
        borderless
        class="header-links__group"
        no-toggle-icon
        reverse
        variant="overflow" >
        <@icon><ebay-overflow-small-icon/></@icon>
        <@item type="button">
                <ebay-settings-icon a11y-text="Settings"/>
                ${content.get('settings')}
           </@item>
    </ebay-fake-menu-button>`
![Screen Shot 2022-04-07 at 12 01 18 PM](https://user-images.githubusercontent.com/42783072/162294038-6deba38e-f13f-4896-bdfe-7d2b59502e52.png)

**Comment by agliga** [comment]
Released in `13.6.1`
