### ISSUE TITLE
Switch: improved contrast between on/off states (non-breaking)

### ISSUE THREAD

**Issue by rbascue** [eBay/skin#1723]
We're updating the style of the switch to improve the contrast between on and off states. The fill will lighten and a stroke will be added.

[Figma link](https://www.figma.com/file/zEBdEhbonrBOGzZ0fXzWvM/?node-id=49971%3A79116)

Previous:
![image](https://user-images.githubusercontent.com/35155833/163052715-083f852b-cc5a-41be-b3ce-a0efd4a57132.png)

New:
![image](https://user-images.githubusercontent.com/35155833/163052830-567c0de2-298f-40b4-a469-5e0d02d58ab6.png)

**Comment by rbascue** [comment]
Hi team, reporting back in to add a small change to the request above. After further testing, it has been shown that the blue accent color performs better. We'd like to revert the active state to use blue. Attached is the updated visual treatment. 
![image](https://user-images.githubusercontent.com/35155833/169586638-7b9f3f49-413f-4b36-8865-281eb046c855.png)

**Comment by ArtBlue** [comment]
There have been additional updates to Figma, so this is the latest of what switch should look like. 
<img width="684" alt="image" src="https://user-images.githubusercontent.com/1675667/172717890-12251d2c-449f-4b3b-805b-df73dbb8f3f2.png">

**Comment by ianmcburnie** [comment]
Done in 14.0.0 branch.
