### ISSUE TITLE
snackbar-dialog: color and layout updates

### ISSUE THREAD

**Issue by rbascue** [eBay/skin#1727]
We've updated the snackbar styling to increase contrast against the background. We've also updated the placement guidelines on larger screens.

[Figma page](https://www.figma.com/file/zEBdEhbonrBOGzZ0fXzWvM/?node-id=54706%3A82169)
[Playbook page](https://playbook.corp.ebay.com/PlaybookApp#/executional-guidelines/product-design-system/patterns/snackbars)

![image](https://user-images.githubusercontent.com/35155833/164052232-cb0c7b6a-2148-4cb4-a253-cba37e0c9d0d.png)
![image](https://user-images.githubusercontent.com/35155833/164052251-b905f95a-a969-4dab-ae06-1af76958230b.png)
![image](https://user-images.githubusercontent.com/35155833/164052273-ff335492-fa15-4afe-b6ad-d5b03f5cbfd7.png)

**Comment by ianmcburnie** [comment]
Dev note: Possible markup change required here to accommodate positioning of that info icon, which could mean a small breaking change. Therefore v14 release might make sense.
