### ISSUE TITLE
Icon: confirm-icon-filled change color

### ISSUE THREAD

**Issue by agliga** [eBay/skin#1729]
confirm filled icon should be `color-g4` but it's currently `color-g6`
Will probably need a new token for since it's relying on `color-status-confirmation`

**Comment by ianmcburnie** [comment]
To ease merge conflicts in v14 (which has completely redone tokens) perhaps we can just hardcode the value or just use color-g6 directly, then we can align with new tokens in v14

**Comment by ianmcburnie** [comment]
Oops, sorry. I thought this was specifically for page-notice module. But I now see it is across the board. Please ignore my comment above.

**Comment by ianmcburnie** [comment]
Done in 13.7.0 branch.
