### ISSUE TITLE
Website: update DS6 info with a link to the CDN

### ISSUE THREAD

**Issue by seangates** [eBay/skin#173]
As the title says, we need a link to the CDN version of skin in the documentation.

**Comment by ianmcburnie** [comment]
Here's the URL:

`http://ir.ebaystatic.com/cr/v/c1/skin/v4.0.0/ds6/skin.min.css`

**Comment by seangates** [comment]
Yup. We need it to be part of the build, though, right?

**Comment by ianmcburnie** [comment]
It already is part of the build. A `_cdn` folder is created on every build with ds4 and ds6 versions.

**Comment by seangates** [comment]
But, the link would need to be updated when we version, correct?

**Comment by ianmcburnie** [comment]
Yep. It's just done by hand for now. I don't feel an urgent need to automate that bit yet.
