### ISSUE TITLE
dialogs: pattern updates

### ISSUE THREAD

**Issue by rbascue** [eBay/skin#1734]
We've recently updated the modal dialog pattern with some small visual tweaks and overhauled guidelines for use. Properties have also been more thoroughly documented.

DOD: Modal overlay component matches [Figma](https://www.figma.com/file/zEBdEhbonrBOGzZ0fXzWvM/eBay-Design-System?node-id=54786%3A86730)

[The ticket to update Playbook ](https://ebay.monday.com/boards/1932639446/pulses/2590959745)has been submitted to DT.

![image](https://user-images.githubusercontent.com/35155833/165182109-0e1537e1-5213-4406-b52e-f9fa09e542ea.png)

![image](https://user-images.githubusercontent.com/35155833/165182122-f6b6c401-b2a3-4961-b896-bdc678e905e9.png)

**Comment by agliga** [comment]
This should be for all dialogs. Will be possibly breaking for fullscreen dialog since we need to move the close button to the right. 
Should be next version if we can. 
Footer should be only lightbox, fullscreen, and panel dialogs. Drawer no footer.
