### ISSUE TITLE
field: word wrap problem for text with radio button

### ISSUE THREAD

**Issue by jlayak** [eBay/skin#1740]
Hi,
We are seeing issue of word wrap when used with below code
<ebay-radio
          ...input
          class="field__control"
          id="radio"
          value="1"  />
    <label class="field__label field__label--end" for="radio">
        Option
    </label>

We want the second line to begin below the first line beginning and not below the radio button.

**Comment by agliga** [comment]
Closing issue. If we need to fix this need updated designs.
