### ISSUE TITLE
The website layout rendering is broken in Firefox

### ISSUE THREAD

**Issue by congstr** [eBay/skin#1741]
Please fix the issue on the main documentation page: https://ebay.github.io/skin

I'm on Firefox 99.0.1 (64-bit) Windows 10

This is how it looks like now:

![image](https://user-images.githubusercontent.com/84945884/165746339-f971a978-43f3-40a1-a9ab-5f508922e399.png)

**Comment by ianmcburnie** [comment]
Working for via browserstack, Firefox 99, WIndows 10.

![Screen Shot 2022-04-28 at 9 45 24 AM](https://user-images.githubusercontent.com/38065/165803250-01714c0a-4e22-44f8-834c-8951f977f22d.png)

![Screen Shot 2022-04-28 at 9 45 44 AM](https://user-images.githubusercontent.com/38065/165803249-3e15f40d-3034-4adf-afe0-4ddcae90ab98.png)

**Comment by congstr** [comment]
I still confirm the original issue. Now tested on LibreWolf:

![image](https://user-images.githubusercontent.com/84945884/165808709-1f6c0d56-4439-4a17-bb3f-b222d3aee436.png)

Am I the last person who is using Firefox ? :) 

And, yeah, it works just fine on the Chrome-based Microsoft Edge
Version 100.0.1185.50 (Official build) (64-bit)

**Comment by ianmcburnie** [comment]
Thanks @congstr . We appreciate you filing the ticket :-) Just might be a little low on our priorities for now. We will try and take a look when we get the chance.

**Comment by congstr** [comment]
sure, thank you

I bit of update:

![image](https://user-images.githubusercontent.com/84945884/165813571-db0abe16-be70-4951-98a9-50024a888197.png)

As you see there is a Tracking rule which blocked CSS. Now we know where the issue comes from. 

The control of it is in the Settings. Having it set on Standard will help.

**Comment by agliga** [comment]
Closing, seems like it was resolved.
