### ISSUE TITLE
Drawer Dialog: visual updates

### ISSUE THREAD

**Issue by randybascue** [eBay/skin#1743]
We're making small updates to the style of the bottom sheet header and improving usage guidelines for greater clarity.

DOD -> Bottom sheet matches Figma and [Playbook](https://playbook.corp.ebay.com/PlaybookApp#/executional-guidelines/product-design-system/patterns/bottom-sheet) specs

![image](https://user-images.githubusercontent.com/35155833/166570174-dd14f75e-e3cc-4261-a661-04fa7555fbac.png)

![image](https://user-images.githubusercontent.com/35155833/166570198-3d95890c-6337-4453-aff1-06700f9ce4c5.png)

**Comment by ianmcburnie** [comment]
@rbascue There needs to be a method for a keyboard users and speech control users to dismiss the sheet when in small mode too. Currently on dweb/mweb we display an 'X' button in top right corner to meet this criteria.

**Comment by agliga** [comment]
In the currency screenshot, we can add the X as in the other screenshots. 

This feature will be done together with other dialog header. 
The only thing needed for this is to add the `Apply` button, but we need to discuss if we are okay to remove the close button to replace it with the `Apply` button.

**Comment by agliga** [comment]
Might have design revisit and add a cancel together with apply.

**Comment by katcarboy** [comment]
Confirming that @rbascue will follow up shortly with a version with close button. Sorry for the oversight there!

**Comment by rbascue** [comment]
![](https://ir.ebaystatic.com/cr/v/c1/playbook-20220816-56fcd5a/images/bottom-sheet-documentation_705-9567.png)

**Comment by agliga** [comment]
The text version in the upper right corner will always be a close action. 
Need an example in skin with that. Should document that the text should correspond with a close action, like `apply`. Apply is the recommended option. Otherwise they just use the X.
