### ISSUE TITLE
Tourtip: add optional index and "next" button

### ISSUE THREAD

**Issue by randybascue** [eBay/skin#1744]
We've updated the tour tip component with more properties, flexibility, and guidelines. An idea is being added, the title is being increased in size, and actions are added along with a smaller close icon.

DOD: Tourtip component matches [Playbook](https://playbook.corp.ebay.com/PlaybookApp#/executional-guidelines/product-design-system/patterns/tourtips) and [Figma](https://www.figma.com/file/zEBdEhbonrBOGzZ0fXzWvM/?node-id=54797%3A88595)

![image](https://user-images.githubusercontent.com/35155833/166834520-c2896515-0e40-450d-856b-9c413567481d.png)
![image](https://user-images.githubusercontent.com/35155833/166834532-2673098c-2b7f-4f63-8b74-c65914b33d73.png)

**Comment by ianmcburnie** [comment]
Thanks @rbascue 

This seems a bit of a departure from the current Tour Tip - which is more geared towards a simple "one off" kind of tip (with no index or back/next button). This new iteration seems like it is part of a Product Tour type system. Do we still want to keep the old, simpler style around as an option?

**Comment by rbascue** [comment]
The index and actions are properties that can be toggled off for simple non-actionable messages.

**Comment by rbascue** [comment]
![image](https://user-images.githubusercontent.com/35155833/173903759-12da7707-6989-47ae-9b46-a732405625be.png)

**Comment by ArtBlue** [comment]
Was it settled that this is to be a new component? If so, we should change the title of the issue to avoid confusion,

**Comment by agliga** [comment]
This issue will only add footer and index in existing tourtip
We will open a `spotlight` issue to cover the masking tourtip part.
