### ISSUE TITLE
Tooltip: design updates

### ISSUE THREAD

**Issue by rbascue** [eBay/skin#1745]
We've made small updates to the tooltip pattern to make a clearer separation between tooltips and tourtips, improve guidelines, and provide a higher-contrast version to capture attention on scroll or load.
DOD - Tooltip component matches [Playbook](https://playbook.corp.ebay.com/PlaybookApp#/executional-guidelines/product-design-system/patterns/tooltips) and [Figma](https://www.figma.com/file/zEBdEhbonrBOGzZ0fXzWvM/?node-id=54797%3A88326)

**Comment by rbascue** [comment]
![image-2022-05-04-15-43-44-386](https://user-images.githubusercontent.com/35155833/166837700-595d8052-1bb3-43c1-8314-1fc3fef60fb7.png)
![image-2022-05-04-15-43-56-104](https://user-images.githubusercontent.com/35155833/166837701-8db2a992-b4e6-4aab-a368-aafe6884fdf8.png)
![image-2022-05-04-15-46-25-227](https://user-images.githubusercontent.com/35155833/166837702-f6f71849-988a-4af9-9a2e-de578426b4ee.png)

**Comment by agliga** [comment]
I assume then tourtips will also have the same look and feel as tooltips just without a host element?
And now the mobile version of tooltips is a drawer instead of a lightbox correct?

**Comment by rbascue** [comment]
@agliga correct

**Comment by ianmcburnie** [comment]
@agliga @rbascue Tooltip is a hover/focus interaction. We cannot have a dialog open on focus/hover. We need to discuss this further.

**Comment by agliga** [comment]
My understanding is that tooltip will remain as is, and infotip will show dialog on click (like it is currently).

**Comment by ianmcburnie** [comment]
Yes, that's fine for Infotip. It's a click interaction as you say. Gotta be careful with our tooltip, infotip, tour tip terminology ;-)
