### ISSUE TITLE
Icon: new Social Media Instagram SVG

### ISSUE THREAD

**Issue by anjalikm** [eBay/skin#1749]
Social team is adding new channels to social products on seller hub. 

requirement: add Instagram icon to UI Library 

Jira Ticket: https://jirap.corp.ebay.com/browse/PLATUX-655

image files for Instagram icon:

![insta_white](https://user-images.githubusercontent.com/16467469/168876318-559bc2fa-58f1-4972-81df-0b91a69b9ed9.svg)
![insta_black](https://user-images.githubusercontent.com/16467469/168876321-052ca1c5-69e8-4e44-9a96-2091593e4dc6.svg)

**Comment by agliga** [comment]
So this icon uses a base64 image. We need all our icons to be normalized before we can use them. Can you please give us an instagram icon or have our design team give it to us as we had the previous ones?
