### ISSUE TITLE
Less: @ds6-typography-small-secondary is set to incorrect color

### ISSUE THREAD

**Issue by bhoomisatasiya** [eBay/skin#176]
@ds6-typography-small-secondary is set to incorrect color, 
it should be @ds6-color-g205-gray (#767676)  
not @ds6-color-g206-gray (#111820)

<img width="763" alt="screen shot 2018-04-30 at 8 31 17 pm" src="https://user-images.githubusercontent.com/11545472/39461851-832827c0-4cc2-11e8-88ab-e0e5faacbff5.png">

**Comment by ianmcburnie** [comment]
Thanks for spotting this. It's quite possible that DSL did list this as `@ds6-color-g206-gray` at one point time, or maybe was a typo on our end. Anyway, we shall update it to match latest DSL.

**Comment by ianmcburnie** [comment]
Done.
