### ISSUE TITLE
Toast Dialog: incorrect hover/focus state

### ISSUE THREAD

**Issue by PrashantAshok** [eBay/skin#1764]
`ebay-toast-dialog` has an issue when you hover over the primary button - the background and text becomes darker. 
reproducible on both skin and core UI storybook https://opensource.ebay.com/skin/#toast-dialog

<img width="501" alt="Screen Shot 2022-06-03 at 11 01 17 AM" src="https://user-images.githubusercontent.com/5200733/171921803-0e3dd839-a767-49ff-aaf0-6a7baf1fea04.png">

**Comment by agliga** [comment]
This seems to have been fixed. Closing.
