### ISSUE TITLE
Update/Add icons

### ISSUE THREAD

**Issue by ratinsl** [eBay/skin#1765]
We have updated and added a variety of icons. Please keep in mind some of the names may have changed.
We have included the icons as a batch in the folder below:

**Figma** reference [here](https://www.figma.com/file/zEBdEhbonrBOGzZ0fXzWvM/eBay-Design-System?node-id=49261%3A80050)

**Files**
[220606_Icon Batch](https://drive.google.com/drive/folders/1PGpf-XxD99ZEAmoiAFs9waPddVPQsI75?usp=sharing)

**[Update/Replace existing]**

- **Close** (24, 16)

- **Help** (24, 16)
_This new one replaces the one with the circle outline around it_

- **Home** (24)
_IOS was missing this, so including here too_

- **Home Active** (24)
_IOS was missing this, so including here too_

- **Profile** (24)
_This used to be called profile-alt, it is replacing the current profile icon that looks like a stamp_

- **Profile Active** (24)
_This used to be called profile-alt, it is replacing the current profile icon that looks like a stamp_

- **Selling** (24)
_IOS was missing this, so including here too_

- **Selling Active** (24)
_IOS was missing this, so including here too_

**[New Additions]**

- **3D Arrows** (24, 16)

- **Car** (24, 16)

- **Chevron**
(Left: 20 - Used in navigation)

- **Close** (20 - used in navigation)

- **Collections** (24, 16)

- **Copy** (24, 16)

- **Help Outline** (24, 16) 
_This is an update for the original "help" icon, it is now a new icon called help-outline_

- **Keyboard** (24, 16)

- **Overflow** (20 - used in navigation)

**Comment by agliga** [comment]
Closing, will do it as part of #1830
