### ISSUE TITLE
Icon: Re-encode the background icons with DSL black (not #000)

### ISSUE THREAD

**Issue by seangates** [eBay/skin#177]
We need to use #111820 for the background icons as it is the "black" from DSL.

**Comment by seangates** [comment]
Confirmed. Use the `#111820` color (`@ds6-color-g206-gray: #111820`) for the icons.

**Comment by ianmcburnie** [comment]
I guess Patrick's SVG CLI tool will make this easy :-)

**Comment by ianmcburnie** [comment]
We can review this again as part of DS6.5 - sprint 2 (icon, colour & type)

**Comment by msendlakowski** [comment]
There are no color changes being made for DS6.5.  So we can do this with the color mentioned by Sean.
