### ISSUE TITLE
infotip: missing pointer

### ISSUE THREAD

**Issue by melquan** [eBay/skin#1792]
# Bug Report

## Description
The pointer is not displayed.

## Workaround
None

## Screenshots
[eBayUI core Storybook](https://opensource.ebay.com/ebayui-core/?path=/story/ebay-infotip--standard)
![image](https://user-images.githubusercontent.com/19419138/177584789-47389662-2267-4f7a-ab0d-39ef26f3c484.png)

[SKIN documentation](https://opensource.ebay.com/skin/#infotip)
![image](https://user-images.githubusercontent.com/19419138/177584812-71c0ed74-38d2-469f-b47b-64d97b5afb6d.png)

**Comment by ArtBlue** [comment]
Dev note: it looks like `--bubble-top-box-shadow` (and possibly other comparable shadow vars) is not set. It may have gotten compromised during the `ess/css` swaps in `v14`.
