### ISSUE TITLE
fake-menu-button: remove min-width of borderless button

### ISSUE THREAD

**Issue by melquan** [eBay/skin#1824]
# Bug Report

## Description
There's a min-width of 88px on the borderless `fake-menu-button` so when there's no text, the icon scoots to the left and there's extra space on the right.  This is being inherited from the `.btn` class.

## Workaround
Override it to `min-width: 0` in our app in the meantime.

## Screenshots
![image](https://user-images.githubusercontent.com/19419138/181592929-6747f519-3032-4089-af58-86f7e2c29866.png)

**Comment by ianmcburnie** [comment]
Let's make sure we have a story in Skin storybook for this too.
