### ISSUE TITLE
Progress stepper - Improved state styles and guidelines

### ISSUE THREAD

**Issue by rbascue** [eBay/skin#1826]
We're making a small visual, but larger functional update to the progress stepper component. The states are simplified down to _incomplete_, _complete_, _latest_, and _blocked_. 

In essence, a step is either complete or incomplete. The most recent completed step will have a bolded label, while older completed steps will have a regular label.

[Storybook component →](https://opensource.ebay.com/ebayui-core/?path=/story/progress-ebay-progress-stepper--in-progress)

[Figma documentation →](https://www.figma.com/file/zEBdEhbonrBOGzZ0fXzWvM/eBay-Design-System?node-id=72928%3A79348)

### Examples
![image](https://user-images.githubusercontent.com/35155833/181860396-c41e031a-e80d-4bc8-b9ce-7fc032f1485d.png)

### Specs
![image](https://user-images.githubusercontent.com/35155833/181860569-ac26f586-0d8f-480a-87e5-8accdfe0fa9c.png)

![image](https://user-images.githubusercontent.com/35155833/181860588-23528ef9-8a46-4074-b532-b1728aff3b24.png)

**Comment by agliga** [comment]
@ianmcburnie 
Would there be any accessibility concerns about this? I see that with this we won't have any more aria currents

Seeing this i believe this will be a breaking change.

**Comment by ianmcburnie** [comment]
It looks like the most recent "tick" will be aria-current (?), but we can discuss offline.
