### ISSUE TITLE
menu: menus for multiple form themed menu buttons aren't displayed properly

### ISSUE THREAD

**Issue by melquan** [eBay/skin#1827]
# Bug Report

## Description
If I have multiple form themed menu buttons next to each other and I open the menu of any of the buttons other than the first one, the menu is always left aligned and the menu is as wide as the right hand side of the menu button clicked.  For example, the first screenshot is with 3 menu buttons and after clicking the 3rd button.

If I add `left: 0` to the `menu-button__menu` class, it seems to fix it (2nd screenshot).  Just checking if this is a known issue.

## Workaround
I could override it in our component but would prefer to pick up the fix from SKIN if it's available soon.

## Screenshots
_Issue when clicking the 3rd menu button_
![image](https://user-images.githubusercontent.com/19419138/182209341-eedf574b-b4ce-4ea8-ae86-e9bfa447c19a.png)

_With `left: 0` fix_
![image](https://user-images.githubusercontent.com/19419138/182209366-09b0e8d3-f167-4553-adff-df239a83b402.png)

**Comment by agliga** [comment]
Looks good overall, but two comments on this that need to be fixed
* on `ltr`, we need to do `left: unset` and `right: 0`
* on `--reverse` we need to also unset the left and set right to 0. For `ltr` we should do the opposite. 

This is whats happening on reverse menu button. 
<img width="270" alt="Screen Shot 2022-09-01 at 12 24 25 PM" src="https://user-images.githubusercontent.com/1755269/187995932-140726ad-65ec-4430-a90a-4383439bd04c.png">
But setting right to 0 and left to `unset` works: 
<img width="175" alt="Screen Shot 2022-09-01 at 12 24 58 PM" src="https://user-images.githubusercontent.com/1755269/187996000-b683a666-7a5b-4a30-b946-eeaf1aa6b851.png">

For LTR, it looks fine until you have a large item:
<img width="438" alt="Screen Shot 2022-09-01 at 12 25 35 PM" src="https://user-images.githubusercontent.com/1755269/187996136-fa2f8c95-b068-4340-8954-2999ec52976c.png">
But setting right to 0 it works fine
<img width="646" alt="Screen Shot 2022-09-01 at 12 25 42 PM" src="https://user-images.githubusercontent.com/1755269/187996187-11d594f9-5d19-47d4-90ca-96a5819aa978.png">



I think with those changes we should be good.
