### ISSUE TITLE
1830 - Update iconography based on new source of truth

### ISSUE THREAD

**Issue by ratinsl** [eBay/skin#1830]
We now have an officially sanctioned Design location for all things iconography:

https://drive.google.com/drive/folders/1lH_p0ECIWiAKbE2-N0PBhOWx8wo3S3jH?usp=sharing

 

This will be the source of truth for icons moving forward.

We should audit our icons and make sure that:

1) we have them defined
2) they are properly named

It would be good to check your current library and compare them to this folder to see if they have changed. We are here to provide a list of additional specifics and assistance if needed. This ticket may also help with other tickets like **Issue #1812**.

Please reach out with any questions.
Best,
Ryan

**Comment by agliga** [comment]
Will need to sync up to make sure the naming is in line as well as issues with clip paths and symbols are resolved.

**Comment by agliga** [comment]
https://github.com/eBay/skin/issues/1765
https://github.com/eBay/skin/issues/1861

Closing other icon issues. Will keep this one open as the source of truth once we are unblocked

**Comment by agliga** [comment]
Will review the names with design.
For this we can include the new icons as new assets since we will have new sizes on the name.

**Comment by ratinsl** [comment]
Hey @agliga, any progress on this? Or going to tackle in the new year?
