### ISSUE TITLE
listbox-button: match border & background color with other components like combobox or textbox

### ISSUE THREAD

**Issue by melquan** [eBay/skin#1842]
# Improvement

## Description
The border & background color of the default `listbox-button` is different than other components like the `combobox`, `textbox` or `select`.  The other components have the dark gray border and light gray background, while the `listbox-button` has a black border and white background.

Update the `listbox-button` border & background colors to match the other components so that when they are used together, they look consistent.

## Screenshots
`listbox-button`
![image](https://user-images.githubusercontent.com/19419138/186325990-6c55b882-77e5-4f5f-aeb3-57d7e15c6077.png)

`combobox`
![image](https://user-images.githubusercontent.com/19419138/186326194-ba07a949-b989-43c8-b9fb-1dd56ec995b8.png)

`textbox`
![image](https://user-images.githubusercontent.com/19419138/186326316-3f6e2910-6a19-44c3-b276-dcc6e76763c7.png)

`select`
![image](https://user-images.githubusercontent.com/19419138/186326258-486fa379-1b29-4940-9c37-4073346396d7.png)

**Comment by agliga** [comment]
So this might not be an issue. I believe in forms the recommended is to use select. In Figma we see "dropdowns" are white background which is what listbox is, and in forms, dropdowns are grey background. 
@ianmcburnie to comment based on history of listbox. 
If we want to support listbox in forms we would probably need a modifier to make it have a grey background.

**Comment by melquan** [comment]
We are using the listbox in a form so it would be great to have it supported and have a grey background for design consistency when used together with other form components.

**Comment by agliga** [comment]
Will add this. We will add a form variant for listbox button like we have for
