### ISSUE TITLE
220908 - Update image placeholder asset

### ISSUE THREAD

**Issue by ratinsl** [eBay/skin#1860]
We have updated the rather old "image placeholder" asset with the new image icon. This asset is used when an image is not uploaded or available to view. The asset is an svg at 300x300 and should be scaled linearly/proportionally down to any size needed since it is used at a wide variety of sizes.

The asset is attached and it is called "image-placeholder.svg".

Tyler Nugent on IOS supplied the "current" asset used and he wrote logic a while back for this asset. If you have any questions, please reach out to either of us.

Attached is guidance showing what the asset currently looks like, what the new version is in light/dark mode and in context. It includes color guidance for light/dark mode.

Best,
Ryan

![Updated_image-placeholder_guidance](https://user-images.githubusercontent.com/33495986/189262723-57545dd5-3e34-440c-8e87-2e0dc87274ac.png)

![image-placeholder](https://user-images.githubusercontent.com/33495986/219298751-c524cbd7-d12a-46c0-9c73-3029f9d4ce83.svg)

**Comment by agliga** [comment]
Might create a new "module" for this. Like a placeholder module.

**Comment by ratinsl** [comment]
I updated the comment above with the SVG asset to use. It is a 300x300 SVG, but is meant to scale proportionally to any item tile size. (This is different than how we treat traditional icons). This asset has a large amount of empty space built around it on purpose so the icon is the size/right ratio at any given size.
