### ISSUE TITLE
220908 - Update/Add (Green & Red) Trend Arrows

### ISSUE THREAD

**Issue by ratinsl** [eBay/skin#1861]
We haven't had a consistent style/size for the green and red trend arrows found in selling hubs and data visuals—until now. We'd like this added so teams have one central location to grab these because multiple teams have been reaching out for them.

You can find the icons in the global icon folder and the are titled "trend-up_24.svg" and "trend-down_24.svg":
[https://drive.google.com/drive/folders/1lH_p0ECIWiAKbE2-N0PBhOWx8wo3S3jH?usp=sharing](url)

**Here is a current reference in context**
![220908_Trend Arrow Reference (current)](https://user-images.githubusercontent.com/33495986/189266252-6c1cd159-65e4-49d3-8375-bdf15ae0d44f.png)

**New Guidance and Sample**
![220908_Trend_Arrow_Guidance](https://user-images.githubusercontent.com/33495986/189266992-2aa7d401-ddf1-45fd-a43d-9d3e8b1d14a3.png)

**Comment by agliga** [comment]
Closing, will do it as part of #1830
