### ISSUE TITLE
Notice icons alignment issue

### ISSUE THREAD

**Issue by HenriqueLimas** [eBay/skin#1868]
After latest notice changes #1790, the icon is not centered aligned anymore and when used a `p` element inside `notice__main` the icon and the text are not aligned anymore

<img width="419" alt="Screen Shot 2022-09-12 at 2 31 15 PM" src="https://user-images.githubusercontent.com/2222191/189765749-0e6c421c-7f8d-42f3-b6cf-dbf98c0d984c.png">

Expected layout:
<img width="405" alt="Screen Shot 2022-09-12 at 2 58 24 PM" src="https://user-images.githubusercontent.com/2222191/189765906-978ee621-22bb-4b87-9e9a-10e4e4eecfce.png">

**Comment by agliga** [comment]
I noticed that in section notice and inline notice the icons are still misaligned when using a paragraph element. We should try to resolve those as well in this PR.
I believe inline notice has a 4px top already set, but it seems like a bit much and looks off.
