### ISSUE TITLE
Modal Lightbox - Size options

### ISSUE THREAD

**Issue by randybascue** [eBay/skin#1874]
We've added guidance around the sizing of modal windows. This allows for a more fine-tuned experience with less whitespace or scrolling.

[Section on Playbook](https://playbook.corp.ebay.com/PlaybookApp#/product-guidelines/patterns/modals#options)

![col-1](https://user-images.githubusercontent.com/35155833/191323963-3c0759f3-83be-410b-87e8-aab61598eae8.png)

![col-2](https://user-images.githubusercontent.com/35155833/191323999-c333142d-b082-464a-9bb3-ed6e542901ef.png)

![col-1-1](https://user-images.githubusercontent.com/35155833/191324008-be638c89-50be-419f-8216-9c3011d99b9f.png)

![col-2-1](https://user-images.githubusercontent.com/35155833/191324021-cd1b1349-c38f-4536-975d-3cef43baf4d3.png)

![col-2-2](https://user-images.githubusercontent.com/35155833/191324069-fec7b617-5139-4fcc-bd10-16cc7e851580.png)

![col-2-3](https://user-images.githubusercontent.com/35155833/191324078-c4b392f8-729d-47e1-bc1d-6cf3d35deca1.png)

**Comment by agliga** [comment]
Need info about which option is response vs which one is configurable by a class/option

**Comment by randybascue** [comment]
Updated with [issue 1937](https://github.com/eBay/skin/issues/1937)
