### ISSUE TITLE
listbox - update label color

### ISSUE THREAD

**Issue by randybascue** [eBay/skin#1880]
The label color for the listbox component is current using `--color-foreground-primary` when enabled and inactive. It should be `--color-forground-secondary` in an enabled inactive state. It changes to `--color-foreground-primary` when the button is active.

[Playbook](https://playbook.corp.ebay.com/PlaybookApp#/product-guidelines/patterns/dropdowns-selection-menus)
[Storybook](https://opensource.ebay.com/ebayui-core/?path=/story/buttons-ebay-listbox-button--standard&globals=backgrounds.grid:false;backgrounds.value:transparent)
[Figma](https://www.figma.com/file/zEBdEhbonrBOGzZ0fXzWvM/eBay-Design-System?node-id=40884%3A48665&viewport=1921%2C797%2C0.67)

![image](https://user-images.githubusercontent.com/35155833/191864633-7498f477-e1ee-4411-b740-f42890e9fb7c.png)

![image](https://user-images.githubusercontent.com/35155833/191865018-9452df36-99be-4fc2-a60d-4323fd721ae9.png)
![image](https://user-images.githubusercontent.com/35155833/191868075-49aa01d3-36d8-4497-ac09-96029b38b5c1.png)

**Comment by ArtBlue** [comment]
@randybascue , this isn't called out specifically in the issue, but all the specs have the values in bold text. Did you want that applied as well?

**Comment by ArtBlue** [comment]
> @randybascue , this isn't called out specifically in the issue, but all the specs have the values in bold text. Did you want those changed as well?

I just went ahead and applied the bold to values.
