### ISSUE TITLE
CTA large alignment issue

### ISSUE THREAD

**Issue by HenriqueLimas** [eBay/skin#1890]
When using a cta-btn--large, the alignment of the content is not centered to the button:

```html
<a href="http://www.ebay.com" class="cta-btn cta-btn--large">
   <span class="cta-btn__cell">
      <span>CTA button</span>
      <svg aria-hidden="true" class="icon icon--cta" focusable="false">
         <use xlink:href="#icon-cta"></use>
      </svg>
   </span>
</a>
```

<img width="165" alt="Screen Shot 2022-10-03 at 4 35 13 PM" src="https://user-images.githubusercontent.com/2222191/193704212-3e493fd4-cced-4834-935f-8bb88ce864ed.png">

**Comment by agliga** [comment]
Adding a `display: inline-flex;` to the cta button should fix this issue.
