### ISSUE TITLE
eBay-breadcrumb: overflow functionality for longer paths

### ISSUE THREAD

**Issue by randybascue** [eBay/skin#1896]
An overflow can be used for long paths and page names. This addition cleans up the interface for longer category names while still providing access to all parent pages. 

[Storybook](https://opensource.ebay.com/ebayui-core/?path=/story/navigation-disclosure-ebay-breadcrumbs--heading)
[Playbook](https://playbook.corp.ebay.com/PlaybookApp#/product-guidelines/patterns/breadcrumbs)

### Variants
![image](https://user-images.githubusercontent.com/35155833/195144229-1b69ebb5-8748-4df4-9255-7c4c45badeaa.png)

### Overflow
![image](https://user-images.githubusercontent.com/35155833/195144424-031df1ce-1667-4ab6-aec2-15017f181753.png)

### Max characters
![image](https://user-images.githubusercontent.com/35155833/195144500-dad24497-74b0-4651-9105-97c9cfa122a5.png)

### Desktop example
![image](https://user-images.githubusercontent.com/35155833/195144669-b2caf43c-0595-4ec4-84ce-8499603431e2.png)

**Comment by agliga** [comment]
Questions for design:
1. Does this show automatically when we have too many pages (ie 3 or more), or do we want to keep this as an option. 
2. Are we adding tooltip support?

**Comment by randybascue** [comment]
Yes, we're intending for it to be automatic. 
The tooltip reveals the text overflow. We could use ours or use the browser default (example below).
<img width="522" alt="image" src="https://user-images.githubusercontent.com/35155833/197055321-3a4dea16-30c0-4333-ab72-5d69b0f35458.png">

**Comment by agliga** [comment]
On skin, will have two options. One with dropdown and one without. We won't change it automatically.
On ebayui we can change it to be automatic on 4 or more. If < 4 show all breadcrumbs, otherwise show the overflow dropdown. 
Also we won't add tooltips. Only ellipsis.
