### ISSUE TITLE
Table: New Module

### ISSUE THREAD

**Issue by hej-wesley** [eBay/skin#1900]
New data table component and pattern.

Details for options, sizes, behavior, and platform scaling. This is a V1 release that focuses on desktop & tablet with recommendations for mobile adjustments.

Please reach out to Wesley or Randy from Design Systems for questions 
 

[Figma Link ](https://www.figma.com/file/ZUjvlrpjU06EVpcOLOC6cR/Evo-data-tables?node-id=199%3A30951)

Updated Figma link (2024-08-01): https://www.figma.com/design/jFbAR0o364WhsjELfxl2SI/Playbook-2.0-%2F-Components?node-id=207-124816&t=mrjxSsw5T2P0YwBk-0

**Comment by kcarboy** [comment]
Link to notes from 1/26 Kickoff [https://ebay.enterprise.slack.com/docs/T025756QT/F06FY3ZM0MS]

**Comment by namtheho** [comment]
This is the updated and correct link for Data Tables — 
<img width="403" alt="image" src="https://github.com/user-attachments/assets/2fd90ead-3342-476e-a5c4-8c2cdc8534ca">
https://www.figma.com/design/jFbAR0o364WhsjELfxl2SI/Playbook-2.0-%2F-Components?t=Aimfc7ZXD39DUS1X-0

**Comment by ArtBlue** [comment]
I hunted around in Playbook and found the specific Data Tables Figma page:
https://www.figma.com/design/jFbAR0o364WhsjELfxl2SI/Playbook-2.0-%2F-Components?node-id=207-124816&t=mrjxSsw5T2P0YwBk-0

**Comment by agliga** [comment]
1st part is complete in `18.2.0`. Moving this to `18.3.0` for the next part.
