### ISSUE TITLE
page-grid: layout grid/margin updates

### ISSUE THREAD

**Issue by ratinsl** [eBay/skin#1901]
We recently updated our Layout Grids to reflect our Evolution/Core 15 work. In doing so, we have adjusted a couple grids and added larger-screen versions.

The main thing that has been updated is increasing the left/right margins on larger screens. This may impact tablets, hence this ticket.

**Gutters and Margins:**

> 320-599 (8px gutters, 16px margins)

> 600-1279 (16px gutters, 32px margins)

- This has been updated with the name "Medium Screen"

> 1280-1679 (16px gutters, 48px margins)

- This is where the margins increase to 48px on left/right

- This is a new grid called "Large Screen"

> 1680+ (16px gutters, layout locked center, auto margins) - Max design area excluding margins is 1584px wide.

- This is a new grid called "X-Large Screens

All of this is demonstrated in our core 15 file found [here](https://www.figma.com/file/AppbCyA4MK7s0y10VOUlYu/Evo-Core-15-(Dev)?node-id=232%3A99526).

All of the details can be seen on the [Layout Grids](https://www.figma.com/file/zEBdEhbonrBOGzZ0fXzWvM/eBay-Design-System?node-id=46819%3A77770) page in Figma

Please reach out with any questions to Ryan or Randy on the Design Systems team

**Comment by agliga** [comment]
This should be prioritized.

**Comment by stephenscaff** [comment]
### Proposed updates. 

High level, this proposal suggests 

- Moving the container’s width declaration from `.page-grid` to `.page-grid-container` 
- Setting the container’s max width to evo’s `1480px` 
- Using on CSS variables / tokens to make things more flexible and dynamic.

[Full Setup and Use Example→](https://codepen.io/StephenScaff/pen/qBMXojw)


### Details 

**Container**

A centralized container provides the system with the critical ability to create consistent layouts across our apps. 

- This container should work independent of additional CSS Grid layouts/declarations
- The container should handle max-width, outside-gutters, page centering.
- The container’s max-width should follow Evo’s spec of `1480px`, set to a CSS variable for flexibility.
- Use CSS Var for grid's outside gutter spacing to update from `8px` to `16px` above medium break.


**CSS Grid Wrapper**

- The CSS Grid wrapper should handle CSS Grid setup, so independent children to define cols / grid areas.
- Use CSS variable for number of columns, to update from `8` to `16` above medium break.


### Setup 


**Tokens**

```
// tokens.less
:root {
  --page-grid-number-cols: 8;
  --page-grid-gutter: 8px;
  --page-grid-outside-gutter: 16px;
  --page-grid-outside-gutter-: calc(var(--page-grid-outside-gutter) * -1);
  --page-grid-max-width: 1480px;
  --page-grid-total-width: calc(var(--page-grid-max-width) + (var(--page-grid-outside-gutter) * 2));

  // Update Vars at "Medium"
  @media (min-width: @breakpoint-md) {
    --page-grid-number-cols: 16; 
    --page-grid-gutter: 16px;
    --page-grid-outside-gutter: 32px;
  }
}
```

**Container** 

```
// page-grid.less
.page-grid-container {
  position: relative;
  display: block;
  margin-left: auto;
  margin-right: auto;
  padding-left: var(--page-grid-outside-gutter);
  padding-right: var(--page-grid-outside-gutter);
  width: 100%;
  max-width: var(--page-grid-total-width);

  // handle any nested instances
  & & {
    padding: 0;
    max-width: 100%;
    width: 100%;
  }
}
```

**Page Grid** 

```
.page-grid {
  display: grid;
  column-gap: var(--page-grid-gutter);
  grid-template-columns: repeat(var(--page-grid-number-cols), 1fr);
}
```


### Breakpoints

While not directly related to this proposal, centralized breakpoints will be critical for building consistent responsive components / apps. The latest Evo breaks as as follows:


```
"XS": 375px;
"SM": 512px;
"MD": 768px;
"LG": 1024px;
"XL": 1280px;
"XL2": 1440px;
"XL3": 1680px;
"XL4": 1920px;
```

**Comment by ratinsl** [comment]
Hey @stephenscaff, how did you configure the  --page-grid-max-width: 1480px? We had our max-width as 1584px.

**Comment by stephenscaff** [comment]
Sorry, missed this.

Actually, our original work with Evo was 1680. Subsequent work was then reduced to 1480 - on various Landing pages and VI. 

Honestly, you're correct to follow the current Playbook's 1680 (as the total max-width you have with outside gutters). But, saving that value to a css variable would provide the easiest path modification when need be - ie: for the 1480 instances, and new home has a wider than 1680 option on largest screens).

**Comment by ArtBlue** [comment]
Note: technically, since both `columns-gap` and `row-gap` are considered "gutters," using `--page-grid-gutter` or `--page-grid-gutter-width-small/large` are less than ideal as that nomenclature is not precise enough and could be confused with the outside gutters. I'll be using more specific css properties for those - `page-grid-column-gaps` and `page-grid-row-gaps` respectively as they offer more clarity and are more descriptive.
