### ISSUE TITLE
221017 - Favicon 2.0 Update

### ISSUE THREAD

**Issue by ratinsl** [eBay/skin#1902]
We have refined the Favicon bag and updated the bag handle to a lighter grey to be more legible across light and dark modes of different browsers. Currently, the handle disappears on most dark modes.

The new favicon can be found on bynder [here](https://assets.ebay.com/share/5C0BB547-4CE6-41E8-B8E6E86CA02F72BD/). There is a 16px svg and png - whichever one you need, as well as additional sizes.

![image](https://user-images.githubusercontent.com/33495986/196325281-50a711c0-88c8-4978-9ff5-b8f9c5aaf17c.png)

Please let me know if you have any questions.

Best,
Ryan

**Comment by agliga** [comment]
Do we handle the favicon? Will disucss

**Comment by agliga** [comment]
Not needed in skin
