### ISSUE TITLE
Token: color-magenta-4 is incorrect

### ISSUE THREAD

**Issue by randybascue** [eBay/skin#1909]
The token value for the core token `--color-magenta-4` is incorrect. It is currently the same value as `--color-magenta-6`, which is `#82187C`. It's actual value is `#D11DA4`.

### Incorrect value
<img width="220" alt="Screen Shot 2022-10-21 at 9 19 38 AM" src="https://user-images.githubusercontent.com/35155833/197242940-7f0bfb15-90aa-4353-ad1d-92f1bf81b4f7.png">

### Correct values
<img width="538" alt="Screen Shot 2022-10-21 at 9 21 28 AM" src="https://user-images.githubusercontent.com/35155833/197242957-2ad90b12-8b77-4a72-a216-ab85f9dcf32b.png">

**Comment by randybascue** [comment]
@martin-ebay Here is a ticket regarding the issue with magentas that you mentioned in a previous meeting.

**Comment by agliga** [comment]
So we will keep in magenta 3 in the code. The rest should just update the color values.
