### ISSUE TITLE
Bug(Tabs): Focus/Active indicator conflict

### ISSUE THREAD

**Issue by ArtBlue** [eBay/skin#1916]
The tabs have active/focus conflict when the tab item gains focus using the keyboard.

<img width="458" alt="image" src="https://user-images.githubusercontent.com/1675667/198392430-5479fb13-382a-4624-8ef5-96cb730f2120.png">

**Comment by ArtBlue** [comment]
I know I'm the ones who created this issue, but...looking at this a second time, I'm a bit doubtful whether this is a bug. When a keyboard user tabs into the tabs 😏 , the specific tab the user land on it both gains focus and at the same time is the active tab. Since the specific tabs the user navigates to using arrow keys immediately becomes the active tab and gains focus, it doesn't seem like the current interaction is at odds with the styling expectations.

**Comment by agliga** [comment]
Closing for now
