### ISSUE TITLE
Filtering Framework

### ISSUE THREAD

**Issue by hej-wesley** [eBay/skin#1919]
This documents our pattern & framework. Filters can help a user find something they’re looking for, see available options within a certain set of criteria, and make a decision when faced with a large number of options.
–
This pattern goes over methods of filtering, behaviors & interactions and previews a few WIP areas.

[Figma link](https://www.figma.com/file/UBPGajWeKCheSoJqsxD7gJ/Product-DNA---Filtering?node-id=2%3A30153)

**Comment by agliga** [comment]
Trying to figure out what the changes for this issue are? Could we have a bit of direction what changes are needed for ths?

**Comment by agliga** [comment]
Closing as dup of https://github.com/eBay/skin/issues/1927
