### ISSUE TITLE
Website: replace xlink:href example references with href

### ISSUE THREAD

**Issue by ianmcburnie** [eBay/skin#1922]
The example code is littered with examples showing `xlink:href`. The `xlink:`portion is no longer needed.

![Screen Shot 2022-11-04 at 12 25 00 PM](https://user-images.githubusercontent.com/38065/200059109-6b0dfa63-2b01-44a2-820e-83498651771d.png)

https://developer.mozilla.org/en-US/docs/Web/SVG/Element/use
https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/xlink:href

**Comment by codewithfan** [comment]
Hi @ianmcburnie, I would love to help out with this issue.
