### ISSUE TITLE
eBay-carousel: new layout for xl screens

### ISSUE THREAD

**Issue by randybascue** [eBay/skin#1925]
<strike>Due to the awkwardness of items being cutoff on larger screens, we're updating carousels on extra-large screens to surface the controls in the top-right and not cutoff elements. Instead, the content will use pagination-style functionality to scroll the next set of content into view. 

DOD: The carousel on xl screens (1500+) reveals the tappers above the carousel and inline with the section title. Items don't peek at the end. The tappers that appear on hover on small–large screens are centered on the entirety of the item tile, not the images.</strike>

Updated description to reflect that tappers will not be re-positioned to top right. See https://github.com/eBay/skin/issues/1925#issuecomment-1540724219 for updated mocks.

## Screenshots (outdated)

![image](https://user-images.githubusercontent.com/35155833/200443123-32561350-d788-47a7-afcc-795e712cc95e.png)

![image](https://user-images.githubusercontent.com/35155833/200443190-99715399-8d58-4b5b-a6f3-994e9ae82230.png)

![image](https://user-images.githubusercontent.com/35155833/200443099-dae9bcff-f06a-4480-bec3-2bb16af79c81.png)

**Comment by agliga** [comment]
So most of this seems fine, but couple of questions and concerns we need addressed first

* We do not currently provide a way for users to add a title in the carousel. They can add it, but it's up to them. We can change that by making title required for this change to occur. If they do not pass a title, then we will not shift the paddles. (This is a minor concern)
* What kind of carousel is this for, discrete or continuous? If it's for discrete, then the change where we do not have a peek on large screens should be fine for ebayui only. For continuous, does this paddle change apply in any way without the peek?
* For the last statement about the tapers being centered on the tile and not the image, this is actually how it is currently. We center it on the tile. We have no idea what teams will add in each tile so they are centered already. Just wanted to clarify if there is anything else we need to do on this. 

This could also potentially cause a layout change. I think there might be a way to achieve this change and support the old structure as well though.

**Comment by randybascue** [comment]
- I built it with the section title in Figma to make it easier for designers to drop it in as a composite component (section title + carousel container). In terms of logic, without the title as a property, how would you suggest adding the tapper logic for XL screens? Should we have a name for carousels with a title containing tiles vs. quick filter carousels?
- We didn't intend for the XL version to have peeking content. We want to avoid having stacks of carousels with cutoff items floating in the middle of the screen. 
- Sounds great. I wasn't sure, so I wanted to clarify.

**Comment by randybascue** [comment]
@agliga is this still blocked?

**Comment by ianmcburnie** [comment]
I think so. It needs more discussion.

**Comment by agliga** [comment]
So lets keep focus order the same as we have currently. 
We will tab through the prev paddle, then item tiles, and then next paddle. 
This will keep it consistent across all screens.

**Comment by ianmcburnie** [comment]
> So lets keep focus order the same as we have currently. We will tab through the prev paddle, then item tiles, and then next paddle.

Only potential spanner in the works here is that we might want to keep heading/section-title decoupled from the carousel itself (I think we do that currently). In which case we'd have to have a different Dom structure and more of a traditional top-down, left-to-right TAB order.

**Comment by agliga** [comment]
For this, we are planning on only implementing the size changes and not the paddles.

**Comment by ratinsl** [comment]
@agliga regarding the number of items tiles within the carousel at different breakpoints, it goes something like this:
**1920:** 5 tiles
**1680:** 5 tiles
**1440:** 4.5 tiles
**1280:** 4.5 tiles
**1024:** 4.5 tiles
**768:** 3.5 tiles
**512:** 2.5 tiles (Added this one)
**375:** 1.75 tiles

You can see visuals here in our [core 15 file](https://www.figma.com/file/AppbCyA4MK7s0y10VOUlYu/Evo-Core-15-(Dev)?node-id=689-297631&t=R8vaJItPh0LkZTho-4). Please only refer to the "carousel" section as the "grids" section may be outdated.

![Screenshot 2023-04-24 at 9 22 37 PM](https://user-images.githubusercontent.com/33495986/234384713-37c31ab1-45f4-46e2-8571-a3dc6ecf7555.png)

**Comment by randybascue** [comment]
![image](https://github.com/eBay/skin/assets/35155833/fada7d84-cbde-4936-bdc3-52d11b156ca0)

![image](https://github.com/eBay/skin/assets/35155833/38420ee0-8121-49fb-8914-abad730809c9)

**Comment by randybascue** [comment]
@agliga updated xl screen version to use vertically-centered controls.

**Comment by randybascue** [comment]
@ArtBlue @agliga Do you have a timeline for this adjustment?

**Comment by ianmcburnie** [comment]
Changes to paddle alignment and paddle icon (24 to 12) should go out in upcoming release.

**Comment by ianmcburnie** [comment]
So, paddle icon changes are done and will go out in this release. The alignment is a little tricker but hopefully will be done for this release also.
