### ISSUE TITLE
ebay-lightbox-dialog: standard sizes

### ISSUE THREAD

**Issue by randybascue** [eBay/skin#1937]
We are standardizing the sizes available for ebay-lightbox-dialog. We want to provide two sizes, a regular 616px and a wide 896px. Both are fixed until they reach 100% of the grid width. Once they reach 100% they pin to the left and right. We also want to add a minimum height of 280px and max height of 90% of screen/window height.

DOD: Modals are available in two sizes: a regular 616px and a wide 896px. Min-width is set to 280px.

### Documentation preview
![image](https://user-images.githubusercontent.com/35155833/201786666-8517c6e6-4709-43c3-8156-fff8aa86d1a0.png)

### Responsive animation
https://user-images.githubusercontent.com/35155833/201787773-3fd4cd6d-8f78-4ac9-9c87-90d139561930.mov

**Comment by ArtBlue** [comment]
This issue appears to have conflicts with https://github.com/eBay/skin/issues/1874.

**Comment by agliga** [comment]
Possible breaking. Need to investigate @ArtBlue

**Comment by agliga** [comment]
> @agliga Will the update to the scrolling behavior be a part of this as well?

Yes
