### ISSUE TITLE
Loading button with variant `form` is incorrectly aligned

### ISSUE THREAD

**Issue by darkwebdev** [eBay/skin#1940]
<img width="96" alt="image" src="https://user-images.githubusercontent.com/2737310/202500286-529ab8eb-216c-4f90-9c82-2a1a194db442.png">

<img width="361" alt="image" src="https://user-images.githubusercontent.com/2737310/202500365-70fe9832-5219-4082-a5a1-4f8b7f0eb6c6.png">

reason:
<img width="254" alt="image" src="https://user-images.githubusercontent.com/2737310/202501031-059eb0f7-d94a-44fe-a02c-95235adfe47c.png">

can be fixed by:
```
justify-content: center;
```

**Comment by sharmadhiraj86** [comment]
Hii @agliga @darkwebdev, I would like to contribute to this issue. Could you assign it to me? Thanks.
