### ISSUE TITLE
221201 - Add/Update Avatars

### ISSUE THREAD

**Issue by ratinsl** [eBay/skin#1948]
<img width="806" alt="Screen Shot 2022-12-01 at 8 53 32 PM" src="https://user-images.githubusercontent.com/33495986/205219985-08f57e90-47d8-45da-ae38-a0aa035e16c5.png">
<img width="808" alt="Screen Shot 2022-12-01 at 8 53 24 PM" src="https://user-images.githubusercontent.com/33495986/205219976-37d4534c-0fda-4ec6-9024-a0e23df75c74.png">

We just finished a new avatar framework and documentation. We are introducing a new "default" avatar that will be used when users fail to upload an avatar image. This new default avatar introduces 7 color combinations (background color and text color) to bring color to the experience and to get rid of the current "sad man" default avatar.

Color is randomly assigned to each user, but the color should follow the user across IOS/Android/HTML. Meaning if a user gets the orange color combo based on their username, the orange color should follow them across platforms. To help demonstrate this, @Robin Hamilton-Pennell built a quick html test page for all teams to reference and use the algorithm/setup. If you have any questions about how this works, please reach out to both her and I. The link is provided below.
Also, avatars that currently use the "sad man" default avatar should be updated with this new version.

All avatars are designed at 48px and scaled up or down proportionally from there. The single character within the default avatar (coming from the first character of the username) is using the "large 2 bold" type style (24/32) and is vertically and horizontally centered in the 48px circle.

The new "ebay" and updated "Signed out" avatars also need to be updated for both light/dark modes. They are included as 48px square assets that should be cropped in circles. Unsure if you can update these or if there is a service/other team we need to reach out to in order to make these updates. Please let us know.

Best,
Ryan

**Figma Avatar Documentation:**
https://www.figma.com/file/zEBdEhbonrBOGzZ0fXzWvM/eBay-Design-System?node-id=92847%3A108319&t=CffcRcjrh9RKUp8e-4

**Algorithm/Reference to use across platforms to ensure consistent default avatar color by username (built by @Robin Hamilton-Pennell of IOS):**
https://pages.github.corp.ebay.com/rhamiltonpennell/avatar/avatar.html

**Comment by agliga** [comment]
Looks pretty straightforward.

**Comment by agliga** [comment]
aria-label either user name or signed out
Set colors possibly as css variables. 
See hashing about common usecase for selecting the color. 
Don't use images on figma. Try custom images. Image might need to be clipped.

**Comment by ratinsl** [comment]
@agliga here is the avatar signed out svg:

**Light/dark mode colors:**
Head and body: foreground.secondary
Background circle: background.secondary

![avatar-signed-out](https://user-images.githubusercontent.com/33495986/234681058-9e26e944-cde1-4e7f-bea5-66d2873afac6.svg)
