### ISSUE TITLE
Safari: Background of tourtip fills in the body background 

### ISSUE THREAD

**Issue by don-siu** [eBay/skin#1973]
We found that there’s an UI issue with Safari. The background of the TourTip fills into the body background and makes style of other components break too. Is it expected? Is there a way to fix it? Thanks

https://user-images.githubusercontent.com/42818524/211614932-2291818d-e32d-4b24-8924-d7f3cc2ffe4d.mov

**Comment by ArtBlue** [comment]
This was an interaction-level issue that does not exist in Skin and was solved in ebay ui. Our approach was communicated to help solve it in the react app.
