### ISSUE TITLE
Segmented button - New Component

### ISSUE THREAD

**Issue by hej-wesley** [eBay/skin#1976]
A Segmented button provides closely related choices that affect an object, state or view. This page provides documentation on how and when to use a segmented control.

[FIGMA LINK](https://www.figma.com/file/zEBdEhbonrBOGzZ0fXzWvM/branch/2xzrlkToIUDkkAeLryKxUW/eBay-Design-System?node-id=100107%3A122941&t=ZMYu8n6r18Yn1RKr-1)

**Comment by agliga** [comment]
This will probably use radio under the hood, and possible event extend radio.

**Comment by ianmcburnie** [comment]
> This will probably use radio under the hood, and possible event extend radio.

Yep, we'll definitely need this for when it's used in forms. We _may_ also consider allowing alternate markup (i.e. just divs with appropriate ARIA) when its just switching between two views of a component.

**Comment by agliga** [comment]
Using `aria-current`
Should have buttons.
Background is transparent. Try to darken 4%. 

Possibly rename to `content-swither` or `view-switcher`. Or keep as is.
