### ISSUE TITLE
ebay-listbox-button: update enabled border

### ISSUE THREAD

**Issue by randybascue** [eBay/skin#1977]
The library had the listbox button border set to `color-border-subtle`, and Storybook appears to have it using `color-border-strong`. To improve visibility and consistency, this needs to be updated to use `color-border-default`. The active state will continue using `color-border-strong`.

### Previous
![image](https://user-images.githubusercontent.com/35155833/214126880-5420f1f5-9bd9-4685-8ed8-1e4a87323eb2.png)

### Updated
![image](https://user-images.githubusercontent.com/35155833/214126911-1a85be7a-725d-4c08-9cd1-32bd9421d0c1.png)

**Comment by agliga** [comment]
Images are swapped. 
Will only do this one for non form styling.

**Comment by agliga** [comment]
Closing, this appears to be fixed already. 
<img width="575" alt="Screenshot 2023-09-13 at 10 49 28 AM" src="https://github.com/eBay/skin/assets/1755269/cc0413aa-7f4b-42f7-91a6-a65912324ce1">
https://github.com/eBay/skin/blob/master/src/less/mixins/private/dropdown-mixins.less#L5 (its using `color-stroke-default`)
