### ISSUE TITLE
ebay-filter-menu-button: improve container contrast

### ISSUE THREAD

**Issue by randybascue** [eBay/skin#1985]
**Problem**: The current discrete filter menu button is difficult to discern.

**Solution**: Add a border using `--color-border-default` to the unselected enabled state.

The selected state will continue using `--color-border-strong`. This improvement addresses various accessibility tickets.

### Before
![image](https://user-images.githubusercontent.com/35155833/218205444-1d47c5c3-c947-4ad3-afc3-63668599dd64.png)

### After
![image](https://user-images.githubusercontent.com/35155833/218205503-f6ab0dc0-8fb8-47a8-a527-daacadd6c28c.png)

**Comment by ArtBlue** [comment]
This issue is related to this a11y bug: https://jirap.corp.ebay.com/browse/EBAYUI-624
