### ISSUE TITLE
flyout: update styling

### ISSUE THREAD

**Issue by randybascue** [eBay/skin#1986]
_Also known as flyout_

[Project brief →](https://docs.google.com/document/d/1qYsD0moCMnC8cIB6YYy3fPeWn8jfBKKz_lOup0YBRpw/edit#heading=h.859l5crh4sv0)
[Pattern file →](https://www.figma.com/file/BpmtoAoGKzr8VCF8taGMzq/Popovers?node-id=7%3A116&t=P6l3yRos3cigjXXb-11)
[Latest documentation →](https://www.figma.com/file/BpmtoAoGKzr8VCF8taGMzq/Popovers?node-id=78%3A15303&t=P6l3yRos3cigjXXb-11)

Contacts: Randy Bascue and Wesley Anderson

**Summary**: Popovers are non-modal transient containers that appear above other content. They disclose lists of choices or supplemental information.

### Examples 
![image](https://user-images.githubusercontent.com/35155833/218596490-84d69339-de42-4e1f-af7e-41da47f75f87.png)

**Comment by randybascue** [comment]
Let's focus on the styling update in this issue

**Comment by ArtBlue** [comment]
It doesn't look like there are any dark mode specifications for this. This is blocked until we have those specs and can complete the issue.

Dev note: the current `--bubble-filter` defined in the bubble mixins needs to be moved to tokens to allow light/dark mode switching.

**Comment by randybascue** [comment]
## Dark mode
![image](https://github.com/eBay/skin/assets/35155833/856eeb57-018c-4169-8ac7-095bcc9c944f)

**Comment by randybascue** [comment]
Background fill: background-elevated

**Comment by ArtBlue** [comment]
Oh, we don't have the token, `--color-background-elevated`. I was able to dig it out from somewhere in Figma. I'll add that as well. For future reference, let's please make sure the required tokens exist or call them out in the issue. Thanks!
