### ISSUE TITLE
New: Education notice

### ISSUE THREAD

**Issue by randybascue** [eBay/skin#1987]
**Summary**: Education modules are supplemental, contextual messages that educate users about programs, features and opportunities.

[Documentation →](https://www.figma.com/file/zEBdEhbonrBOGzZ0fXzWvM/eBay-Design-System?node-id=90732%3A97760&t=N2QRCppwp2G1BjRO-11)

**Contacts**: Hannah O'Neill, Randy Bascue

### Examples
![image](https://user-images.githubusercontent.com/35155833/218834249-8e4d038c-d418-4431-970c-37ba27b5bfaa.png)

![image](https://user-images.githubusercontent.com/35155833/218834275-e5ed5ae2-1519-41bd-a98a-122f465de396.png)

![image](https://user-images.githubusercontent.com/35155833/218834313-ab555455-ba9b-4e93-bb77-6eb825b09751.png)

![image](https://user-images.githubusercontent.com/35155833/218834346-bd8950e3-ef00-4111-ac98-bc291f144629.png)

**Comment by agliga** [comment]
Icons can be custom, only 24px icons
Blue or grey. Icon color changes based on blue/grey background. 

Possibly can use existing page-notice, but might be extended in future.
