### ISSUE TITLE
ebay-textbox: add icon for invalid state 

### ISSUE THREAD

**Issue by randybascue** [eBay/skin#1989]
**Problem**: The current component on Skin doesn't postfix an icon for invalid input.

**Expectation**: The spec for invalid input postfixes an icon within the field to enhance its visibility and accessibility.

[Component on Storybook →](https://opensource.ebay.com/ebayui-core/?path=/story/form-input-ebay-textbox--with-label&args=invalid:true)

### Expected appearance
![image](https://user-images.githubusercontent.com/35155833/219126485-54ce6b7c-cfc0-43dc-9097-bed11809ad99.png)

**Comment by agliga** [comment]
Closing, this is no longer valid. We are not doing this treatment anymore. Instead the error icon should be next to to the helper text.
