### ISSUE TITLE
ebay-listbox-button: selected value text is not left aligned with the options

### ISSUE THREAD

**Issue by Vaishnavi-Thiyagaraj** [eBay/skin#1991]
The selected value text is not left aligned with the options. The padding of selected text and chevron icon is not sync with the playbook.

### ebay-listbox-buuton
![Screen Shot 2023-02-17 at 1 05 39 PM](https://user-images.githubusercontent.com/49796069/220430321-091dc7e3-4cba-4a83-9a29-1dba90f9e5cb.png)

### Playbook design
![Screen Shot 2023-02-17 at 3 56 18 PM](https://user-images.githubusercontent.com/49796069/220430180-3b6358a6-d6f7-45fb-b095-693212720db9.png)

**Comment by ArtBlue** [comment]
For some reason, I cannot tag Randy. I sent him a message instead. The component currently intentionally centers the text inside and that is the reason why the button text is not appearing aligned to the button text selections. I want to make sure this is how design wants this component. Waiting for Randy's answer.
