### ISSUE TITLE
ebay-lightbox-dialog: navigation

### ISSUE THREAD

**Issue by randybascue** [eBay/skin#2004]
**Problem**: Modals can include multiple steps to complete a task. A user should be able to move between screens without leaving the context of the modal or base page. 

[Playbook →](https://playbook.corp.ebay.com/PlaybookApp#/product-guidelines/patterns/modals)
[Figma →](https://www.figma.com/file/zEBdEhbonrBOGzZ0fXzWvM/branch/y2WGT8ykNIZUZp1BPbfWi5/eBay-Design-System?node-id=54786%3A86730&t=sdMXvYE6xaXgt4QN-11)

### Specs
![image](https://user-images.githubusercontent.com/35155833/223283204-19c4fdb3-5d55-425c-8007-e814db5e0e5e.png)

### Example
![image](https://user-images.githubusercontent.com/35155833/223284215-42ffd61a-a65f-4130-bb52-1addc9bf6ec7.png)

**Comment by agliga** [comment]
Only an icon.
