### ISSUE TITLE
ebay-infotip: update size of close icon

### ISSUE THREAD

**Issue by randybascue** [eBay/skin#2005]
**Problem**: Users need to be able to close an infotip quickly and easily. A close button clearly provides that affordance. The text is 14pt tall and the current icon is the `close-24`.

**Solution**: balance the visual weight of the icon and the text by using the smaller close 16 icon. 

[Playbook →](https://playbook.corp.ebay.com/PlaybookApp#/product-guidelines/patterns/infotip)

### Current
<img width="309" alt="image" src="https://user-images.githubusercontent.com/35155833/223285045-b76170db-53e8-45d3-bb19-c949f37349b4.png">

### Proposed
![image](https://user-images.githubusercontent.com/35155833/223291778-fcbbba41-80f8-463a-9ffb-d0bbde474843.png)

### Specs
![image](https://user-images.githubusercontent.com/35155833/223291807-58beff6c-dbf4-42b1-9364-9f6a8c612899.png)

**Comment by agliga** [comment]
Is the ask to just update the close button to be 24? It currently is 16 in our code.

**Comment by randybascue** [comment]
@agliga It appeared to be 24 when I created this, but looking on Storybook now it appears to be corrected, so we can close this issue. Thank you
