### ISSUE TITLE
230310 - Skeleton Loading

### ISSUE THREAD

**Issue by ratinsl** [eBay/skin#2007]
We have been working on skeleton loading visual/motion development and documentation for a while and want to get it on the books. This is a follow up from a meeting we had a couple of months back and were working with Taylor on the skeleton documentation before he left.

We have a documentation page talking through the styling/usage of skeleton loaders. Notice the specific section for "desktop".
We have teams building their own skeletons and would like to get this componentized as a source of truth. Native is already beginning to implement them.

You can see how the skeleton animates both in the attached deck and also if you enter "present view" by clicking the play icon in the upper right of Figma - there are GIFs that are placed throughout the page for motion reference.

**Figma Documentation:**
https://www.figma.com/file/zEBdEhbonrBOGzZ0fXzWvM/eBay-Design-System?node-id=86853%3A90125&t=wxqS6A6XpYg5ziq9-4

**Motion Deck**
https://drive.google.com/file/d/1XVTVAgXl-HcROUuch7LjojNagKB7IFyr/view?usp=sharing

Please reach out to both myself and Drew Nelson with any questions.

Best,
Ryan

<img width="1121" alt="Figma_Documentation_Skeleton" src="https://user-images.githubusercontent.com/33495986/224457526-61ad817d-cf00-4995-84c7-3cba8a8641b6.png">

**Comment by randybascue** [comment]
@agliga may need to prioritize this for some of the upcoming AI elements

**Comment by agliga** [comment]
Need more information on the shimmer effect

**Comment by ratinsl** [comment]
Synced with @saiponnada on the side and should be unblocked now.
