### ISSUE TITLE
ebay-lightbox-dialog: New expressive variant

### ISSUE THREAD

**Issue by randybascue** [eBay/skin#2009]
**Problem**: There are important brand moments that use lightbox dialogs for messaging and task completion. The current lightbox treatment is simple and utilitarian, which works for the majority of cases. However, brand moments generally use more expressive imagery to provide an enhanced visual experience, so the current version is lacking for these situations.

**Solution**: Add an "expressive" lightbox presentation that adds a hero image, a "transparent" header with a close button, and moves the title below the image. The dialog also has increased padding (16px -> 24px) to provide visual balance.

**Contacts**: @randybascue @ratinsl

[Figma reference →](https://www.figma.com/file/zEBdEhbonrBOGzZ0fXzWvM/branch/85IVoKQNwETQus1rDBuO1j/eBay-Design-System?node-id=54786%3A86730&t=flcrPg4fvBnsbEWp-11)

### Example
![image](https://user-images.githubusercontent.com/35155833/224839437-693a60d9-17ad-4605-8e19-9dbb376036f9.png)

### Specs
![image](https://user-images.githubusercontent.com/35155833/224839485-27b994a4-2f5c-46ae-aa00-f3902ccfc313.png)

**Comment by agliga** [comment]
This one might be okay. We might want to look at this together with all the dialog resize/rework

**Comment by randybascue** [comment]
We're being asked about this variant. @agliga may need to bump in priority next planning session
