### ISSUE TITLE
icons: additions, deletions, modifications 

### ISSUE THREAD

**Issue by ratinsl** [eBay/skin#2035]
We have added some new icons to the system and have some updates and renames. The mapping spreadsheet has been updated with this ticket. Icons mentioned in notes below are in the attached zip folder.

**[New Additions]**
- **Search similar** (16)
- **Pencil** (20)
- **Sparkline Up** (24, 20, 16)
- **Sparkline Down** (24, 20, 16)
- **Location** (16)
- **Key** (24, 16)
- **Money Back Guarantee** (24, 16) _-this is part of the "new" badge system_
- **Package** (64)
- **Thumb Up** (64)
- **Confirmation** (64)
- **Notification** (64)
- **eBay for Charity** (24, 16)
- **Transaction** (24)
- **eBay Preloved** (24, 16)
- **Selling** (16)
- **Undo** (16)
- **Jet Ski** (24, 16)
- **Snowmobile** (24, 16)

**[Updates]**
- **Search similar** (16)
- **Pencil** (20)
- **eBay Refurbished** (24, 16) _-Is now the AG checkmark_
- **Direct from Brand** (24, 16) _-Is now the AG checkmark_
- **Brand Authorized Seller** (24, 16) _-Is now the AG checkmark_
Updated 12px icons to use 12px artboards:
- **arrow left 12**
- **arrow right 12**
- **chevron down 12**
- **chevron left 12**
- **chevron right 12**
- **chevron up 12**
- **sort 12**
- **sort down 12**
- **sort up 12**

**[Renames]**
Removed **currency-** from the beginning of:
- **Dollar** (24, 16)
- **Euro** (24, 16)
- **Franc** (24, 16)
- **Krona** (24, 16)
- **Peso** (24, 16)
- **Pound** (24, 16)
- **Ringgit** (24, 16)
- **Rupee** (24, 16)
- **Zloty** (24, 16)
- **Won** (24, 16)
- **Yuan** (24, 16)

- Renamed “authenticity-guarantee-fit-” to “authenticity-guarantee-” (24, 16)
- Renamed “brand-authorized-seller-fit-” (24, 16) to “brand-authorized-seller-” (24, 16)
    - Updated artwork to the AG checkmark
- Renamed “direct-from-brand-fit-” (24, 16) to “direct-from-brand-” (24, 16)
    - Updated artwork to the AG checkmark
- Renamed “certified-recycled-fit-” (24, 16) to “certified-recycled-” (24, 16)
- Renamed “ebay-bucks-colored-16” to “ebay-bucks-logo-colored-16”
- Renamed “ebay-international-shipping-fit-” (24, 16) to “ebay-international-shipping-” (24, 16)
- Renamed “ebay-refurbished-fit-” (24, 16) to “ebay-refurbished-” (24, 16)
    - Updated artwork to the AG checkmark
- Renamed “free-warranty-16-fit”  to “free-warranty-16” -removed fit just on 16
- Renamed “nectar-24-colored”  to “nectar-logo-24-colored”
- Renamed “rotate-landscape-left” to “rotate-landscape-left-24”
- Renamed “rotate-landscape-right” to “rotate-landscape-right-24”
- Renamed “rotate-portrait-left” to “rotate-portrait-left-24”
- Renamed “rotate-portrait-right” to “rotate-portrait-right-24”
- Renamed “pause-64-colored” to “pause-filled-64-colored”
- Renamed “play-64-colored” to “play-filled-64-colored”
- Renamed “top-rated-seller-16-fit” to “top-rated-seller-16”
- Renamed “trend-up-16” to “trend-up-16-fit”
- Renamed “trend-down-16” to “trend-down-16-fit”
- Renamed “click-to-call-16-fit” to “click-to-call-16”
- Renamed “priority- (16, 24, 64)” to “attention- (16, 24, 64)”
- Renamed “priority-filled- (16, 24)” to “attention-filled- (16, 24)”
- Renamed “arrow-title-20” to “arrow-right-20” and updated artwork

Removed **social-** from the beginning of:
- **Discord** (24)
- **Facebook** (24)
- **Facebook Messenger** (24)
- **Instagram** (24)
- **Link** (24)
- **Linkedin** (24)
- **Pinterest** (24)
- **Reddit** (24)
- **Twitter** (24)
- **Whatsapp** (24)

- Renamed “arrow-title-20” to “arrow-right-20” and updated the artwork

Please let me know if you have any questions,
Ryan Tinsley

[230606_Icon_Updates.zip](https://github.com/eBay/skin/files/11668554/230606_Icon_Updates.zip)

**Comment by ratinsl** [comment]
Hey @agliga and @ArtBlue this ticket is all updated. I will add add the corresponding icons to remove in the other ticket Andrew set up.

**Comment by ratinsl** [comment]
@agliga I added "undo 16" to this zip.

**Comment by ArtBlue** [comment]
Per Ryan, we're also removing a couple of icons  in lieu of their replacements, 

* `play-filled-16` > `play-filled-16-colored`
* `play-filled-24` > `play-filled-24-colored`
