### ISSUE TITLE
ebay-details: update visual style

### ISSUE THREAD

**Issue by randybascue** [eBay/skin#2036]
## Purpose
We're updating the ebay-details component (aka _Expansion_) to increase the title element's weight to bold and updating the text and icon color to `foreground.primary`. This increases it's contrast with surrounding content and aligns closer to Evo.

## References
[Project brief →](https://www.figma.com/file/48oQSeB23kDibHz9WB1coh/Expansion?node-id=1-58&t=2BzgPEqriX4cgzW5-4)

[Figma reference →](https://www.figma.com/file/48oQSeB23kDibHz9WB1coh/Expansion?node-id=531-64263&t=2BzgPEqriX4cgzW5-11)

[Skin docs →](https://opensource.ebay.com/skin/#details)

## Before/After
![image](https://user-images.githubusercontent.com/35155833/231058241-d1cd4c4e-dbb9-41c1-bbb1-00458436c8c1.png)

![image](https://user-images.githubusercontent.com/35155833/231544525-d52e6a40-e85c-4417-8d2c-0fe3813a81e3.png)

## Specs
![image](https://user-images.githubusercontent.com/35155833/231058192-5c0af0cd-5c2c-4f0b-936a-4f25ae634415.png)

**Comment by randybascue** [comment]
More examples
![image](https://user-images.githubusercontent.com/35155833/231543598-70f9dbc2-36df-409c-a08d-27bcfb564a2e.png)

![image](https://user-images.githubusercontent.com/35155833/231543634-8a3c92d1-1552-49f7-9bcc-5163ce930049.png)

![image](https://user-images.githubusercontent.com/35155833/231543683-9cd89a49-dff7-4e21-a408-60fe57e6270c.png)

**Comment by randybascue** [comment]
![image](https://user-images.githubusercontent.com/35155833/231543921-f6e007e7-6efe-4aac-b6d6-06789397a341.png)

**Comment by agliga** [comment]
Just a simple style change, change the color from blue to black

**Comment by agliga** [comment]
@randybascue is there a hover/focus state on this?

**Comment by randybascue** [comment]
Here are the proposed states
![image](https://github.com/eBay/skin/assets/35155833/9ecc506a-7307-4905-846d-1fc6b465fc71)
