### ISSUE TITLE
Button: icons misaligned when text spacing is increased

### ISSUE THREAD

**Issue by ianmcburnie** [eBay/skin#205]
I was playing around with the [text spacing bookmarklet](https://developer.paciellogroup.com/blog/2018/05/short-note-on-getting-spaced-out-with-sc-1-4-12-text-spacing/) and notice that our icon buttons become misaligned when it is applied.

I didn't do any debugging to see what is causing the issue, so further investigation is required.

I found a few other issues with our modules when increasing text spacing, but we can start with this.

<img width="854" alt="screen shot 2018-05-24 at 10 27 50 am" src="https://user-images.githubusercontent.com/38065/40501690-73c12c7c-5f3d-11e8-86c7-208ecb1ac06e.png">

<img width="570" alt="screen shot 2018-05-24 at 10 31 12 am" src="https://user-images.githubusercontent.com/38065/40501779-b3d5d010-5f3d-11e8-91f4-2f07f7685f12.png">

<img width="573" alt="screen shot 2018-05-24 at 10 31 18 am" src="https://user-images.githubusercontent.com/38065/40501782-b61825d0-5f3d-11e8-90a7-917e0c8ee4ae.png">

**Comment by msendlakowski** [comment]
It looks like this issue has been resolved.  I'm not seeing the misplacement using any of the font size techniques in this bug:
https://github.com/eBay/skin/issues/321
