### ISSUE TITLE
Info icon component - Info icon is not centered in the container

### ISSUE THREAD

**Issue by kimcdesign** [eBay/skin#2050]
The icon in the info icon component is not centered in the container.

Link: https://opensource.ebay.com/ebayui-core/?path=/story/buttons-ebay-infotip--default
![image (3)](https://user-images.githubusercontent.com/107954586/233740943-8f6faf54-179b-4a21-92e3-c4dcfcdf7cf9.png)

**Comment by ArtBlue** [comment]
This likely just needs a `line-height` limitation on the `svg`.
