### ISSUE TITLE
230427 - Update 12px chevron icon and spacing

### ISSUE THREAD

**Issue by ratinsl** [eBay/skin#2053]
Hi All,

As you know we recently updated all the 12px icons that were using 16px artboards to now use 12px artboards. When making this update, the spacing between these updated icons and elements like text will appear "tighter" since the artboard got smaller. We need to go into a couple of components and make sure the spacing is adjusted so the new assets look correct.
The ticket that has the new 12px icons can be [found here](https://github.com/eBay/skin/issues/2035). The icons will need to be added before you can implement this ticket.

We will need to update the icon and spacing on the following (and anywhere else the 12px icons are used):

- [Skin Breadcrumbs](https://opensource.ebay.com/skin/#breadcrumbs)
    - [Updated breadcrumb specs ](https://www.figma.com/file/zEBdEhbonrBOGzZ0fXzWvM/eBay-Design-System?node-id=67130-90874&t=vTA4ahNVU1QNayOG-4)
- [Skin Field dropdowns](https://opensource.ebay.com/skin/#field)
    - [Updated quick filter specs](https://www.figma.com/file/zEBdEhbonrBOGzZ0fXzWvM/eBay-Design-System?node-id=55010-91493&t=vTA4ahNVU1QNayOG-4) 
- [Skin Select](https://opensource.ebay.com/skin/#select)
    - (same as dropdown above)

Please let me know if you have any questions,
Ryan Tinsley

**Comment by agliga** [comment]
Possibly breaking, it might shift layout and sizes.

**Comment by ArtBlue** [comment]
@ratinsl , it looks like the only change that is needed for this is for `breadcrumbs`.

1 - For `breadcrumbs` , the chevron margins were not aligned with the Figma spec. I updated to `6px` margins from `3px`. 
2 and 3 - For the `field` dropdown and `select`, the current spacing already matches the Figma, so no change appears to be needed. See screenshot. In the code, the spacing already matches that. 

Unless something is incorrect in the Figma, I'm going to simply ignore `field` and `select`.

<img width="569" alt="image" src="https://github.com/eBay/skin/assets/1675667/1ea93abe-f22a-4b05-8671-2b4f08cd156d">

**Comment by ratinsl** [comment]
@ArtBlue yes you are correct, looks like the one that was most impacted was the breadcrumbs one. So as long as you are matching the specs across these, then we are good!

**Comment by ArtBlue** [comment]
> @ArtBlue yes you are correct, looks like the one that was most impacted was the breadcrumbs one. So as long as you are matching the specs across these, then we are good!

Thanks! I'll move ahead with the breadcrumbs only spacing tweaks.
