### ISSUE TITLE
Notice: layout issue when text spacing is increased

### ISSUE THREAD

**Issue by ianmcburnie** [eBay/skin#206]
I was playing around with the [text spacing bookmarklet](https://developer.paciellogroup.com/blog/2018/05/short-note-on-getting-spaced-out-with-sc-1-4-12-text-spacing/) and see that our notice module has an issue when it is applied.

I didn't do any debugging, so further investigation is required. Most likely some rejigging of flexbox properties can resolve this. Low priority too.

<img width="1169" alt="screen shot 2018-05-24 at 10 46 12 am" src="https://user-images.githubusercontent.com/38065/40502486-f70f5d9a-5f3f-11e8-9b2b-cd05c81e442a.png">

**Comment by msendlakowski** [comment]
I didn't use the bookmarklet, but I tested using the zoom guidelines in this bug:
https://github.com/eBay/skin/issues/321

The notice component looks good now.  These are various screenshots from Chrome, Safari and Firefox.

![screen shot 2018-08-31 at 10 40 33 am](https://user-images.githubusercontent.com/1562843/44928022-62490c00-ad0b-11e8-90b9-a1b23d5075f4.png)
![screen shot 2018-08-31 at 10 40 41 am](https://user-images.githubusercontent.com/1562843/44928023-62490c00-ad0b-11e8-8699-7da149efe491.png)
![screen shot 2018-08-31 at 10 40 54 am](https://user-images.githubusercontent.com/1562843/44928024-62e1a280-ad0b-11e8-89d0-35f9f5c330e8.png)
![screen shot 2018-08-31 at 10 41 42 am](https://user-images.githubusercontent.com/1562843/44928025-62e1a280-ad0b-11e8-94b9-d76cc4b204cc.png)
![screen shot 2018-08-31 at 10 41 50 am](https://user-images.githubusercontent.com/1562843/44928026-62e1a280-ad0b-11e8-8cea-8f8efe0e415d.png)
