### ISSUE TITLE
listbox: add error state

### ISSUE THREAD

**Issue by randybascue** [eBay/skin#2063]
## Problem
There are cases where a missing value in a listbox throws an error. An error state should be available to account for these situations, especially for use in forms. 

## Solution
Add error state with helper text option below the listbox. 

## Resources
[Playbook →](https://playbook.corp.ebay.com/PlaybookApp#/product-guidelines/patterns/form-fields#options)
[Figma →](https://www.figma.com/file/zEBdEhbonrBOGzZ0fXzWvM/eBay-Design-System?type=design&node-id=25465-6237&t=HT5inLlzQHtkmyYk-11)
[Storybook →](https://opensource.ebay.com/ebayui-core/?path=/story/buttons-ebay-listbox-button--standard)

## Examples
![image](https://github.com/eBay/skin/assets/35155833/39381f1f-3c2c-480f-82dd-ef7afa6477b6)

![image](https://github.com/eBay/skin/assets/35155833/beb169b2-db55-4c2b-ba3c-600841cd2e10)

**Comment by agliga** [comment]
We need to verify accessibility wise how to add this. Mind patterns might need to be updated first.

**Comment by agliga** [comment]
Will use describe by to target the error state

**Comment by ArtBlue** [comment]
@agliga , what does this mean?

> Will use describe by to target the error state

**Comment by agliga** [comment]
> @agliga , what does this mean?
> 
> > Will use describe by to target the error state

So from what I remember is if the listbox is in error state, we will add a `aria-describeby` on the listbox element which targets the error message below it (so the ID of the describeby will be the error message container ID). This way when the user focuses on the listbox with voiceover it'll announce that there is an error.
