### ISSUE TITLE
Dialogs not opening correctly in Safari 13

### ISSUE THREAD

**Issue by mkchang** [eBay/skin#2073]
On the skin page (e.g. https://opensource.ebay.com/skin/#lightbox-dialog), not seeing some dialogs open at all.

Toast, snackbar dialogs open. Fullscreen, lightbox, panel, drawer so far do not. No console log errors. Tested on Safari 13.1.2 via browserstack.

<img width="1123" alt="image" src="https://github.com/eBay/skin/assets/6880917/971805ef-5e32-44ea-a57f-6dfd25b2c957">
<img width="266" alt="image" src="https://github.com/eBay/skin/assets/6880917/2f2f8fc9-02ce-4f73-b937-2465b89e93a0">

We are seeing this trickle down to ebayui-core storybook dialogs opening incorrectly as well (preventing scroll, dialog misplaced, mask not covering the entire screen).
![image (15)](https://github.com/eBay/skin/assets/6880917/8529f406-159c-4482-b1eb-afc11c65ec32)
![image (32)](https://github.com/eBay/skin/assets/6880917/017e0714-79e4-4e4f-bc35-dee7459a0151)

**Comment by ArtBlue** [comment]
Older Safaris probably treat `flex` differently than new ones. Based on some initial brief troubleshooting, it looks like the dialogs may need some explicit styling, specifically, `drawer-dialog--mask-fade` (and other analogous elements for the other impacted components) may need the following mostly redundant/unnecessary styling for newer browsers, but crucial for older ones:

```css
width: 100%;
height: 100%;
bottom: 0;
left: 0;
```

**Comment by mkchang** [comment]
Would it make sense to revert to 
```css
top: 0;
bottom: 0;
left: 0;
right: 0;
```
instead of `inset: 0;` for the dialogs, as changed in https://github.com/eBay/skin/commit/1ac29fec4f7480492bcaf9d248176940ced269c3? Since `inset` does not seem to be supported below Safari 14.

**Comment by ArtBlue** [comment]
@mkchang , thanks for tracking that down. I didn't realize this was a recent change that caused it. You're right, `inset` does not seem to be supported below `Safari 14.1` so that reversion should work. I'll make sure before I create the PR.
