### ISSUE TITLE
Floating Label has a few edge cases with Chrome's autocomplete

### ISSUE THREAD

**Issue by LuLaValva** [eBay/skin#2080]
When a chrome user hovers over an autocomplete option, all potentially effected fields are presented with text which is not actually present in the DOM or detectable by CSS, but is still visible to the user. Floating labels don't rise with this text, so they overlap with the fake text and the experience looks broken.

<img width="692" alt="image" src="https://github.com/eBay/skin/assets/26027232/3cee01c3-ec58-4114-ab99-b003af30c801">

**Comment by ArtBlue** [comment]
This was released in `16.3.0`.
