### ISSUE TITLE
page-notice: bad keyboard focus indicator color on CTA

### ISSUE THREAD

**Issue by ianmcburnie** [eBay/skin#2082]
We should change the keyboard focus outline to white.

![Screen Shot 2023-06-09 at 4 35 20 PM](https://github.com/eBay/skin/assets/38065/3d6d0624-c9c0-4d76-938a-3f5e623b869d)
![Screen Shot 2023-06-09 at 4 35 10 PM](https://github.com/eBay/skin/assets/38065/0ff62132-0daa-4172-a15b-44508d3bcc26)
![Screen Shot 2023-06-09 at 4 34 53 PM](https://github.com/eBay/skin/assets/38065/53f1674c-c5de-441a-a043-79181df7d54f)

**Comment by agliga** [comment]
So only for page notice, the rest should leave as is
