### ISSUE TITLE
ebay-textbox: content not scrolling when swiping

### ISSUE THREAD

**Issue by randybascue** [eBay/skin#2087]
## Problem
The input isn't scrollable to the left-right when typing. It's difficult editing an input value or making a selection.

![IMG_4EE8A1F2F387-1](https://github.com/eBay/skin/assets/35155833/d593067c-d330-424d-b399-5e0218a38289)

Let me know if you need me to wire a prototype.

**Comment by randybascue** [comment]
We prefer opting for a textarea when input has a chance to be long but we can't ensure that'll be the case every time.

**Comment by LuLaValva** [comment]
It looks like this is actually native behavior for the HTML `input` component on Safari, we aren't doing anything special to prevent it. You can check with any other default form, like [the form example on w3schools](https://www.w3schools.com/html/html_forms.asp). One of our core principles is that we don't override any default browser behavior, so even though I am not a fan of the way this works I don't think it should be changed.

**Comment by randybascue** [comment]
@LuLaValva bummer. If it's a browser issue then I guess it's out of our hands, from what I'm understanding. Quite the irritating interaction (or lack thereof) from Safari.

**Comment by LuLaValva** [comment]
I agree, this seems like an unfortunate oversight at the browser level. As much as I'd like to have this fixed, we need to maintain consistency with native components so it is out of our hands. The best we can do is opt for textarea when input has a chance to be long, like you had suggested @randybascue.

**Comment by randybascue** [comment]
@LuLaValva Closed as not planned/won't fix
