### ISSUE TITLE
toast: secondary action has unreadable text on hover

### ISSUE THREAD

**Issue by PrashantAshok** [eBay/skin#2092]
![Screen Shot 2023-07-07 at 1 42 04 PM](https://github.com/eBay/skin/assets/5200733/2a07243d-9b27-47e1-b2a4-d97cf0c1eebc)

Repro: https://opensource.ebay.com/skin/#toast-dialog

**Comment by randybascue** [comment]
@ArtBlue @LuLaValva how are these buttons being styled currently? We should either create a button variant explicitly labeled something like "white" or "on-color", or apply the color-foreground-on-{color} tokens here.

**Comment by LuLaValva** [comment]
Right now we are overriding the colors specifically for buttons that are inside toast dialog to these values, but it looks like this is a case that we didn't take into account. I wasn't able to find this component in Figma, would you mind pointing me in the right direction @randybascue?
