### ISSUE TITLE
Info Tip Style Bug - Dismiss icon is not aligned with header is missing

### ISSUE THREAD

**Issue by Jonaphant** [eBay/skin#2100]
If header is not passed to infotip, the dismiss icon is no longer vertically aligned with the content.

With Header - Incorrectly aligned dismiss button
![Screenshot 2023-07-18 at 2 42 35 PM](https://github.com/eBay/skin/assets/31060063/53772c56-a901-4d22-90e7-7a804277dcd5)

Without Header - Correctly aligned dismiss button
![Screenshot 2023-07-18 at 2 44 01 PM (1)](https://github.com/eBay/skin/assets/31060063/379d28a4-12fa-4de0-b328-6a871b7f5e5f)

**Comment by ArtBlue** [comment]
I checked ebay ui and this code ensures that `span.infotip__heading` is only rendered if a heading is passed in:

```
                <if(heading)>
                    <${heading.as || "span"}
                        ...processHtmlAttributes(heading, ignoredHeaderAttributes)
                        class=[`${input.type}__heading`, input.heading.class]
                        id:scoped="tourtip-label">
                        <${heading.renderBody}/>
                    </>
                </if>
```

Based on an offline discussion, an empty string was being passed in on the implementation side. Closing this as it's not an issue with the component.
