### ISSUE TITLE
feat(textbox, listbox-button): Add error icon to the left of the error message

### ISSUE THREAD

**Issue by randybascue** [eBay/skin#2103]
# Problem
Error states should use more than color to indicate a change in state.

# Solution
Prefix an error icon to the helper text to highlight invalid fields.

# Resources
[Playbook →](https://playbook.corp.ebay.com/PlaybookApp#/product-guidelines/patterns/form-fields#options)
[Figma →](https://www.figma.com/file/zEBdEhbonrBOGzZ0fXzWvM/eBay-Design-System?type=design&node-id=25465-6237&t=HT5inLlzQHtkmyYk-11)
[Storybook →](https://opensource.ebay.com/ebayui-core/?path=/story/form-input-ebay-textbox--with-label)

# Examples
![](https://user-images.githubusercontent.com/35155833/238061206-39381f1f-3c2c-480f-82dd-ef7afa6477b6.png)

![](https://user-images.githubusercontent.com/35155833/238061233-beb169b2-db55-4c2b-ba3c-600841cd2e10.png)

![image](https://github.com/eBay/skin/assets/35155833/08dcd2b5-3681-44d0-aef0-675fa3a6763b)

**Comment by randybascue** [comment]
@ArtBlue It’s any field, so both textbox and listbox

**Comment by randybascue** [comment]
It’s moving the error icon out of the field itself and in the leading position of the helper text.

**Comment by ArtBlue** [comment]
> It’s moving the error icon out of the field itself and in the leading position of the helper text.

Oh, ok. Thanks for the clarifications, @randybascue . 

I don't think we have the error icon inside a field on Skin. Maybe this originated from another team's ad hoc implementation?

**Comment by randybascue** [comment]
It might have been. In that case, it’s adding it instead of moving it from somewhere else.

**Comment by ArtBlue** [comment]
@randybascue , I don't see any state-specific styling (border and text color) for active, hover, and focus. Do we have them? If so, can you provide them? I'm hesitant to use the styling that's applied by default when there is no error state because once the user starts interacting with them, the error indication would vanish - not the best UX.

**Comment by randybascue** [comment]
@ArtBlue I’m unclear on the ask. Do you mean how does hover, focust, active look when a field is invalid?

**Comment by ArtBlue** [comment]
> @ArtBlue I’m unclear on the ask. Do you mean how does hover, focus, active look when a field is invalid?

@randybascue , yes.

**Comment by ArtBlue** [comment]
@randybascue , for now, I simply matched the state colors to those of `textbox` (nothing's needed at the moment), but we should think of having those supported.
