### ISSUE TITLE
New component: chip

### ISSUE THREAD

**Issue by randybascue** [eBay/skin#2108]
## Summary
An input chip component improves the usability, organization, and accessibility of user inputs. It enhances visual feedback, enables flexible interactions, and contributes to a consistent user experience, ultimately enhancing user satisfaction and engagement.

## Resources
[Project brief](https://docs.google.com/document/d/1VQPCdJq1v68yMIEteUnWUJxdUM7jtx2_8HcIcVSZ18s/edit)
[Figma library branch](https://www.figma.com/file/zEBdEhbonrBOGzZ0fXzWvM/eBay-Design-System?type=design&node-id=138990-237371&mode=dev)
[Pattern file](https://www.figma.com/file/Lk953iWSOLa5R4DsxQbgHd/Input-chips?type=design&node-id=741-30431&mode=dev)

## Use cases
1. Selecting multiple features when creating a listing
2. Selecting multiple options when configuring a store

## Examples
![image](https://github.com/eBay/skin/assets/35155833/4b59f18c-28f2-4145-80c1-f63047481244)

![image](https://github.com/eBay/skin/assets/35155833/99a76a62-7482-4222-a2ca-4ffd9c3a9e86)

![image](https://github.com/eBay/skin/assets/35155833/d2239080-b153-4ec8-aee4-789b565e9a88)

![image](https://github.com/eBay/skin/assets/35155833/24273b2f-2dee-4b52-bfe4-b6cf8c75a3e8)

**Comment by LuLaValva** [comment]
Some notes from discussion on August 2nd by eBayUI team:

- If the chips are _inside_ the input, there are some tricky edge cases that will need to be looked into:
    - Should we have line wrapping? If there is no wrapping, then we will have to deal with horizontal scrolling and problems with responsive design.
    - With just a sliver of area available, what happens when the user types past the edge of the screen?
    - **Suggestion**: move the chips _outside_ the input, probably above the textbox. This is much simpler on the engineering side and there also aren't nearly as many edge cases with responsive design.
- If we display the popover with checkboxes underneath, we have duplicated information and it may be tricky to manage for accessibility
    - It would be great to use our existing combobox, but `aria-combobox` has strict requirements which cannot be met by the current design (one of the requirements is that items cannot have a "selected" state)
    - **Suggestion**: when an item is selected from the popover, _remove_ it from the list and add it as a chip. This way, we don't need to display checkboxes and there is also no duplicate information.
- Is there an expected average number of chips; should we put hard limits on the amount?
- We don't love the idea of using a delimiter to create each chip. If some team wants to allow commas, then this component will have inconsistent behavior across the site.
    - **Suggestion**: use the `enter` key instead for this behavior

**Comment by randybascue** [comment]
To recap our last discussion:
- We’ll be removing items from the list menu as they are selected and converted to chips
- No checkboxes
- No horizontal scrolling versions. Cap at a maximum height and scroll vertically.
- Explore having the chips outside of the text field. 
- Enter key submits the value and creates the chip
- Further outline wrapping rules to avoid small type area at end of field

**Comment by randybascue** [comment]
@LuLaValva is my recap above accurate? Anything missing?

**Comment by LuLaValva** [comment]
I think that covers everything, thanks @randybascue!

**Comment by agliga** [comment]
We need to have the tokens used in chips. These are not present in the tokens section in figma and we need those in order to proceed with this issue.

**Comment by randybascue** [comment]
`tertiary` has been added to the [token table](https://www.figma.com/file/zEBdEhbonrBOGzZ0fXzWvM/eBay-Design-System?type=design&node-id=108131-129598&mode=design&t=HlWS898zuz1p4OqN-11).

**Comment by ArtBlue** [comment]
@randybascue , I think we're still missing the tokens for the hover/focus/active of the `x` icon button for both light and dark mode as well as the icon color itself for the button hover/focus/active. We'll discuss offline.

**Comment by ArtBlue** [comment]
This issue tracks the `chip` module, which is just the atomic piece - an individual chip. 

`input chips` is an upcoming module that will utilize this `chip`.

**Comment by randybascue** [comment]
[Latest Figma specs](https://www.figma.com/file/zEBdEhbonrBOGzZ0fXzWvM/branch/iWw6DpoQQvtdUSmAiFTCSI/eBay-Design-System?type=design&node-id=138990-234553&mode=design&t=oLaJnvplvkoqvOKt-11)

Also updated in the first comment
