### ISSUE TITLE
new: education card

### ISSUE THREAD

**Issue by randybascue** [eBay/skin#2117]
## Summary
The education card is a stronger variant of the education notice. They call out programs, features, and opportunities to improve a customer's experience.

## Resources
[Figma specs](https://www.figma.com/file/zEBdEhbonrBOGzZ0fXzWvM/eBay-Design-System?type=design&node-id=144678-255235&mode=dev)

## Use cases
1. Home
2. VI
3. VLP

**Comment by ianmcburnie** [comment]
Currently blocked as Figma currently links through to AI incarnation of education card. Awaiting system-level Figma for education card.

**Comment by agliga** [comment]
@randybascue is this complete or is this different from https://opensource.ebay.com/skin/#education-notice
