### ISSUE TITLE
new: agent color tokens

### ISSUE THREAD

**Issue by randybascue** [eBay/skin#2122]
## Summary
The upcoming agent feature includes a set of new colors. This includes 5 solid colors, 4 opaque gradients, and 3 semi-transparent gradients.

## Resources
[Figma spec](https://www.figma.com/file/zEBdEhbonrBOGzZ0fXzWvM/eBay-Design-System?type=design&node-id=140546-236098&mode=dev)

## Use cases
1. Agent avatar
2. Agent disclaimer
3. Agent M2M
4. Agent modules

**Comment by agliga** [comment]
Will get gradient values from @randybascue

**Comment by randybascue** [comment]
--ai-gradient-full-color-diagonal: linear-gradient(223deg, --ai-yellow 9.79%, --ai-red 26.69%, --ai-purple 41.82%, --ai-blue56.17%, --ai-green 78.48%)

--ai-gradient-green: linear-gradient(270deg, --ai-green 0%, #44CF63 25.00%, --ai-blue 100%)

--ai-gradient-blue: linear-gradient(270deg, --ai-green 0%, --ai-blue 55.62%, #5751EA 75.70%, --ai-purple 100%)

--ai-gradient-violet: linear-gradient(270deg, --ai-purple 0%, --ai-red 100%)

--ai-green: #4EE04B

--ai-blue: #0968F6

--ai-purple: #993EE0

--ai-red: #FF4242

--ai-yellow: #FFD80E

**Comment by randybascue** [comment]
@agliga

**Comment by randybascue** [comment]
Updated color tokens to remove opacity
![image](https://github.com/eBay/skin/assets/35155833/e83cfb73-4150-4b02-8d49-e7066690dbba)

**Comment by randybascue** [comment]
`background: var(--ai-gradient-purple-subtle-light, linear-gradient(270deg, —ai-solid-purple-subtle 0%, —ai-solid-red-subtle 100%));
`
`background: var(--ai-gradient-blue-subtle-light, linear-gradient(270deg, —ai-solid-green-subtle 36%, #EBF3FE 46.87%, —ai-solid-purple-subtle 113%));
`
`background: var(--ai-gradient-green-subtle-light, linear-gradient(270deg, —ai-solid-green-subtle 0%, —ai-solid-blue-subtle 154.5%));
`
