### ISSUE TITLE
Website: layout/icon in site navigation broken on small screens

### ISSUE THREAD

**Issue by ianmcburnie** [eBay/skin#2143]
Probably a quick easy fix, but just tracking it.

<img width="377" alt="Screenshot 2023-08-28 at 12 38 54 PM" src="https://github.com/eBay/skin/assets/38065/2efb6de6-d242-4ff6-8115-1b9d63280ee6">

<img width="371" alt="Screenshot 2023-08-28 at 12 41 10 PM" src="https://github.com/eBay/skin/assets/38065/90e8b8d0-bb24-4f5b-8f68-d7ea0fa9849e">

**Comment by agliga** [comment]
Fixed
