### ISSUE TITLE
Floating Label Textarea: Label overlap with outline

### ISSUE THREAD

**Issue by HenriqueLimas** [eBay/skin#2147]
After #2105, the outline is overlapping with the textarea floating label. This is because of the variant floating-label--opaque class.

![Screen Shot 2023-09-05 at 11 51 12 AM](https://github.com/eBay/skin/assets/2222191/05807444-e1c1-4d4f-929e-e0bbd306e6bf)

**Comment by agliga** [comment]
We need to move the floating label opacity a bit lower from what I remember when we added it.

**Comment by agliga** [comment]
This is working now
