### ISSUE TITLE
Ebay-icon-button: add priority levels

### ISSUE THREAD

**Issue by randybascue** [eBay/skin#2148]
## Summary
**Problem**: Our icon buttons only come in a single visual treatment, leading to issues when icon buttons are adjacent to quick filters or other buttons. 

**Solution**: Add additional levels to the icon button to match other buttons levels. This update adds a primary, secondary, and tertiary styling, and converts the current treatment to a "borderless" level.

## Resources
[Figma spec](https://www.figma.com/file/FOBHLPv0z7oaqUWLbLKqCs/%5Bupdate%5D-icon-button-levels?type=design&node-id=65935-91936&mode=dev) 

## Use cases
1. Watchlist
2. Seller Hub table filtering controls
3. SRP search filter controls
4. BLING filter controls
5. VOD button groups with overflow

![image](https://github.com/eBay/skin/assets/35155833/4c63aaf9-c8d1-4deb-94ef-5779a9d7badb)

**Comment by ArtBlue** [comment]
@randybascue , just a heads up: the smallest spinner button has the spinner icon at `16px`, but we don't have a `16px` spinner icon. Our spinner variations are `20`, `24` and `30`. For that variation, I'll be using the smallest icon we have (`20`) and forcing a `16x16` display using `css`.

**Comment by ArtBlue** [comment]
@randybascue , the variations that have the white background; are they supposed to have a transparent background or white?

**Comment by ArtBlue** [comment]
@randybascue , can you verify the tokens in use for these? Some of the variations look a bit odd in dark mode. 
<img width="159" alt="image" src="https://github.com/eBay/skin/assets/1675667/d63393e8-c944-4909-b79b-c742fb6dd54d">

**Comment by ArtBlue** [comment]
> @randybascue , can you verify the tokens in use for these? Some of the variations look a bit odd in dark mode. 

Actually, I think I may have figured this one out. There was no token defined for the strokes; the color looked to have been hiding in the markup of the stroke. I assume this is just an override on top of the spinner color combinations. 

It looks like the stroke had `#3665F3` defined with an `svg` opacity set on it at 40%, which looks to result in `#3665f366`. This is what it results in:

<kbd><img width="154" alt="image" src="https://github.com/eBay/skin/assets/1675667/04430660-f3e5-4a4c-af85-528572995476"></kbd>


<kbd><img width="162" alt="image" src="https://github.com/eBay/skin/assets/1675667/af4688b3-7151-4445-a7cf-bfdcfdadd823"></kbd>


Please confirm this is accurate. Thanks!

**Comment by randybascue** [comment]
> @randybascue , just a heads up: the smallest spinner button has the spinner icon at `16px`, but we don't have a `16px` spinner icon. Our spinner variations are `20`, `24` and `30`. For that variation, I'll be using the smallest icon we have (`20`) and forcing a `16x16` display using `css`.

Ok, sounds good. I'll submit a ticket on our end
