### ISSUE TITLE
icons: add support for gradient icons and add the first batch

### ISSUE THREAD

**Issue by ArtBlue** [eBay/skin#2149]
## Summary

1. add support for gradient icons
2. add the first batch of gradient icons

## Background

The way we currently use icons relies on using `<symbol>` via a hash ref. Gradients in `svg` require tags like `<linearGradient>` that cannot live inside `<symbol>`. We will need to create a mechanism in our icon generation script to pull out the gradients inside `<defs>` in icons, and move them outside where `<symbol>` would be rendered.

**Comment by ratinsl** [comment]
@ArtBlue here are the AI gradient icons
[230912_Gradient Icons.zip](https://github.com/eBay/skin/files/12591049/230912_Gradient.Icons.zip)
