### ISSUE TITLE
230913 - Update image corner radius scaling

### ISSUE THREAD

**Issue by ratinsl** [eBay/skin#2153]
@saiponnada and I realized that the corner radius of images needs to be adjusted to match our radius strategy.
Currently, it looks like the corner radius is 8px across all images - first spotted on the home page item tiles.

Image Corner Radius should follow:

- Size of 80px and above = 16px radius
- Size of 79px and below = 8px radius

<img width="1366" alt="image" src="https://github.com/eBay/skin/assets/33495986/b4bf4842-c6ff-4270-9ac6-0ac86f067202">

[Link to Figma documentation](https://www.figma.com/file/zEBdEhbonrBOGzZ0fXzWvM/eBay-Design-System?type=design&node-id=91760-102279&mode=design&t=di8kD1zWIlVcAhVd-4).

**Comment by ianmcburnie** [comment]
For fully responsive behavior, this will require CSS container queries, which not all browsers support. However, I think this is something we could consider as a progressive enhancement, i.e. in those browsers that do support it, they will get see the correct border radius as the container size changes, for those browsers that don't they will see a fixed border radius.

https://developer.mozilla.org/es/docs/Web/CSS/CSS_Container_Queries#
