### ISSUE TITLE
New component: input chips

### ISSUE THREAD

**Issue by agliga** [eBay/skin#2159]
Original issue https://github.com/eBay/skin/issues/2108
This will build the input with the chip module that we built from that last issue.

**Comment by ArtBlue** [comment]
This is blocked until the design and interaction is finalized.

**Comment by randybascue** [comment]
[Updated figma doc](https://www.figma.com/file/zEBdEhbonrBOGzZ0fXzWvM/branch/iWw6DpoQQvtdUSmAiFTCSI/eBay-Design-System?type=design&node-id=138990-237104&mode=design&t=jDfuxjtM7gadvZWf-11)
![image](https://github.com/eBay/skin/assets/35155833/8a019ada-ab1c-41e1-a6b4-efee653daa69)
![image](https://github.com/eBay/skin/assets/35155833/6ca25a26-41c4-4ab8-9350-7fd48b9115de)
![image](https://github.com/eBay/skin/assets/35155833/db561261-fe94-48e3-8dcb-f38b56bff6ad)

**Comment by randybascue** [comment]
![image](https://github.com/eBay/skin/assets/35155833/ec5fa659-0d58-4b76-988e-028b5daa502d)

**Comment by randybascue** [comment]
![image](https://github.com/eBay/skin/assets/35155833/4b86df5f-11a9-4858-b3c8-f29711ee82ff)

**Comment by ArtBlue** [comment]
@randybascue , the original Figma link in the original issue seems to be outdated. Can you please paste the new link here? Thanks!

**Comment by randybascue** [comment]
> @randybascue , the original Figma link in the original issue seems to be outdated. Can you please paste the new link here? Thanks!

Updated!
