### ISSUE TITLE
231002 - Icon Removals

### ISSUE THREAD

**Issue by ratinsl** [eBay/skin#2167]
Deprecate/Remove:
Have been updated in the naming spreadsheet.

- Bag 24
Is replaced with Handbag 24 (updated in skin naming spreadsheet)

- click-to-call-24-fit
- ebay-for-charity-24-fit
- ebay-for-charity-16-fit
- ebay-plus-24-fit
- ebay-plus-16-fit
- escrow-24-fit
- escrow-16-fit
- free-warranty-24-fit
- money-back-guarantee-24-fit
- money-back-guarantee-16-fit
- the-ebay-vault-24-fit
- the-ebay-vault-16-fit
- top-rated-seller-24-fit
- verified-condition-24-fit
- verified-condition-16-fit

**Comment by agliga** [comment]
Make sure we verify the deprecated icons other issue https://github.com/eBay/skin/issues/2052 and remove those as well.
