### ISSUE TITLE
Ebay-tourtip: add support for leading image

### ISSUE THREAD

**Issue by randybascue** [eBay/skin#2178]
## Summary
We're adding the ability to add a leading image to tourtips for richer tips.

## Use cases
- Image hotspots
- Motors education
- Motors fitment specialist map

## Resources
[Figma spec](https://www.figma.com/file/zEBdEhbonrBOGzZ0fXzWvM/branch/YOjFdNATscwI7MTPh5O1Yj/eBay-Design-System?type=design&node-id=54797-88595&mode=dev)

## Examples
![image](https://github.com/eBay/skin/assets/35155833/0594c363-2a33-47c4-b279-5c6d43958e4f)

**Comment by ArtBlue** [comment]
@randybascue , a couple of things we need clarification about.

1. I didn't see anything called out in the Figma...are the images supposed to always have rounded corners? All the examples seem to have them, but there's no indication in the Figma.
2. Is the leading image intended to be switched out based on the specific step? This would have interaction implications (ebay ui).

**Comment by ArtBlue** [comment]
@randybascue , one more thing...

3. How is the UI supposed to react to non-square images? Do we just allow whatever image is used? Are there maximum height/width we should be allowing/accounting for? Or is the image always supposed to be constricted to the 88 x 88 square?

**Comment by randybascue** [comment]
@ArtBlue Great callouts. I’ll work on breaking those 3 questions out in the spec

**Comment by LuLaValva** [comment]
Punting this to `17.0.0` or until design has resolved issue comments.

**Comment by ArtBlue** [comment]
Ok, in light of the re-evaluation of the issue, we'll be moving this out of the current release.
