### ISSUE TITLE
ebay-listbox: add support for subline

### ISSUE THREAD

**Issue by randybascue** [eBay/skin#2179]
## Summary
There are cases where options within a listbox menu could use supporting text to further explain the options. This subline is optional and can vary in height per item.

## Resources
[Figma spec](https://www.figma.com/file/zEBdEhbonrBOGzZ0fXzWvM/eBay-Design-System?type=design&node-id=139898-232284&mode=design&t=8JaflxHv1a9AoPeD-11)

## Use cases
1. Choosing quality grades for comics or baseball cards
2. Choosing a service when listing
3. Choosing additional services for motor fitments

## Examples
<img width="964" alt="image" src="https://github.com/eBay/skin/assets/35155833/73cd8988-9187-4cc1-9fb1-c8c72bfc4d95">

**Comment by ianmcburnie** [comment]
There are some a11y concerns here as, if we look at any menu button or listbox button (in your operating system, web email client, or Figma for example), the commands are always one short line of text.

**Comment by randybascue** [comment]
For action menus, this makes sense, but this subline treatment would only be for selection options
