### ISSUE TITLE
New Module: Flags

### ISSUE THREAD

**Issue by ianmcburnie** [eBay/skin#2184]
Required for #1601 

[Flag SVG assets](https://www.figma.com/file/UlIShl5gtABC85JsPLOKym/Country-Flags?type=design&node-id=521-2&mode=design&t=m4SHtwV4ScZf29hU-11)

**Comment by saiponnada** [comment]
@randybascue, waiting for the legal signoff and provide appropriate license to attribute.

**Comment by saiponnada** [comment]
`Flag-icons` uses MIT green license and hence can be used without a formal open-source committee approval.
