### ISSUE TITLE
ebay-toggle-button: missing disabled state

### ISSUE THREAD

**Issue by randybascue** [eBay/skin#2198]
### I verified there's no existing issue for this bug.

- [X] There are no existing issues

### Current behavior

Currently, there is no disabled state available for the ebay-toggle-button. The disabled state is required by teams when certain options aren’t eligible but they want to maintain the layout and recognition of common options in the UI.

### Expected behavior

There is a disabled state available for ebay-toggle-button.

### Steps to reproduce

```bash
1.
2.
3.
...
```

### Additional context

[Figma reference](https://www.figma.com/file/zEBdEhbonrBOGzZ0fXzWvM/eBay-Design-System?type=design&node-id=130426-224910&mode=design&t=Bn5frJtqmV4LuGGa-11)

<img width="1991" alt="image" src="https://github.com/eBay/skin/assets/35155833/af149fd0-72b7-41b8-9a21-b73721e6eb32">

**Comment by agliga** [comment]
This isnt a bug, this is a feature/enhancement. This spec wasn't present when we built this component.

**Comment by randybascue** [comment]
> This isnt a bug, this is a feature/enhancement. This spec wasn't present when we built this component.

My apologies. I’m getting used to the new issue format. I’ll be sure to keep that in mind moving forward. Thank you for the clarification.

**Comment by agliga** [comment]
> > This isnt a bug, this is a feature/enhancement. This spec wasn't present when we built this component.
> 
> My apologies. I’m getting used to the new issue format. I’ll be sure to keep that in mind moving forward. Thank you for the clarification.

No worries! I know it takes time.
