### ISSUE TITLE
ebay-signal has incorrect type size and internal padding. 

### ISSUE THREAD

**Issue by Kevibrown** [eBay/skin#2212]
### I verified there's no existing issue for this bug.

- [X] There are no existing issues

### Current behavior

Storybook component has 12px and it should be 10px with 12px line height.

Internal padding does not align to Figma spec.

**Spec**

<img width="342" alt="Screenshot 2023-11-17 at 3 52 32 PM" src="https://github.com/eBay/skin/assets/151270808/fd5e9f12-5b9b-4d94-ad4e-9df8d96deb67">

### Steps to reproduce

```bash
1.
2.
3.
...
```

**Comment by ArtBlue** [comment]
Technically, this is not a bug, but a misalignment of the spec. The Figma was likely updated since the last Skin update.

**Comment by Kevibrown** [comment]
Good point, is there a better classification you'd prefer for these types of instances in the future?

**Comment by ArtBlue** [comment]
> Good point, is there a better classification you'd prefer for these types of instances in the future?

@Kevibrown , unfortunately, at this point, no one would have a way of knowing whether it's truly a bug or a Figma misalignment. DS has been working on creating versioning and status indicators that should help, but I'm not sure when that's going to roll out. I'm afraid for now, this is the best we can do.
