### ISSUE TITLE
Select: retrofit into DS4

### ISSUE THREAD

**Issue by ianmcburnie** [eBay/skin#222]
Essentially this means renaming `Listbox` to `Select` in DS4.

**Comment by seangates** [comment]
So, this is just like the listbox in DS4, but the combobox is "new" for DS4. Let's discuss how we tackle this divergence.

**Comment by seangates** [comment]
To note: I can't handle a disabled state for the icon properly unless I create a specific Base64 string for the disabled state, which will bloat things. I think it would be best if I put in a PR to add an inline SVG to the component, and then update the DS6 version to support it, too.

**Comment by ianmcburnie** [comment]
All components supports background SVG (default - easiest for CDN users) and foreground SVG (best for coreui).

And yes, the scope of this task is basically renaming the existing DS4 listbox to select.

In a separate task & PR we will add Combobox.

**Comment by seangates** [comment]
Okay. Since the markup changes, though, I've lost the ability to control the disabled state icon (it's a big miss on my part:

![image](https://user-images.githubusercontent.com/105656/42726279-0fe537ae-874f-11e8-9239-4c034c8162de.png)

**Comment by ianmcburnie** [comment]
Its okay to have a specific base64 for disabled state background icon.
