### ISSUE TITLE
ebay-toggle-button--with-image: Without fill placement option images in the ebay toggle button extending outside of the toggle button

### ISSUE THREAD

**Issue by mymadhu** [eBay/skin#2241]
### I verified there's no existing issue for this bug.

- [X] There are no existing issues

### Current behavior
(link removed)

### Expected behavior

When fill placement option is used image displayed in img tag should not be cut off at the bottom in chrome

### Skin version

ebay-skin 16.7.1

### Device/OS/Browser info

Safari, Chrome
![image](https://github.com/eBay/skin/assets/150212906/8170da3a-6fdf-4385-a8f3-2c8fed841355)

### Relevant code block

https://github.corp.ebay.com/adplatform/adsunified/blob/master/src/components/campaign-type/index.marko#L25

### Additional context

![image](https://github.com/eBay/skin/assets/150212906/8170da3a-6fdf-4385-a8f3-2c8fed841355)

Above images in safari(left) vs chrome(right) without using `fillplacement` option for `ebay-toggle-button--with-image`

![image](https://github.com/eBay/skin/assets/150212906/cdb49e82-9b09-4794-838d-f2798f82bea0)

Above image when `fillplacement` is used image is cut off in chrome

**Comment by HimanshuDTU18** [comment]
@mymadhu can i attempt?

**Comment by mymadhu** [comment]
visit https://adsunified.vip.qa.ebay.com/campaign in safari. User: ppl_reco_user, pwd: password

**Comment by ArtBlue** [comment]
@mymadhu , please do NOT post internal links!! This is an open-source project.
