### ISSUE TITLE
tokens: Update to core palette

### ISSUE THREAD

**Issue by randybascue** [eBay/skin#2243]
### Description

We're updating the core color tokens to adhere to our new palette to improve accessibility, flexibility, and brand expression. This includes updates to semantic token references. 

### Screenshots
![image](https://github.com/eBay/skin/assets/35155833/6e6169a2-4f40-4c73-a4a1-a6a7d8d72289)

### Resources

[Migration tables](https://www.figma.com/file/kRncCBxmHGoiSf5imuHNRM/Color-Migration-2024?type=design&node-id=11-23984&mode=design&t=XmqhbCRDXKma2Z2A-11)

[Token table](https://www.figma.com/file/zEBdEhbonrBOGzZ0fXzWvM/eBay-Design-System?type=design&node-id=201652-6820&mode=design&t=4rtSEz8Nin7ttHHW-11)

### Engineering pre-requisites

- [X] Successful design review with Design System Team.
- [X] Supports dark mode.
- [X] Supports responsive design.
- [X] Tokens have been provided (or already exist).
- [ ] Successful accessibility review with Core A11Y Team.
- [ ] Successful frontend review with eBayUI Team.

**Comment by ArtBlue** [comment]
@randybascue , I'm a bit confused. Are we renaming core tokens as well? For example, we currently have this:

`--color-neutral-0: #fff;`

You have that now listed as this:

`color.core.neutral.100: #FFF`

**Comment by randybascue** [comment]
@ArtBlue Correct, the core palette is updated as well

**Comment by ArtBlue** [comment]
@randybascue , I'm not seeing this color in the Figma. 

<img width="255" alt="image" src="https://github.com/eBay/skin/assets/1675667/034ee4f9-ac7e-462e-940a-fe013d9a353d">

Is there some sort of a table or list that has a mapping of current token to new token? That would be really helpful.

**Comment by randybascue** [comment]
Yes! I'll grab that table for you

**Comment by ArtBlue** [comment]
Also, a bit confused about this. The token next to the color is one thing, but the token in the right panel is something else. Which one should we be using?

<img width="1112" alt="image" src="https://github.com/eBay/skin/assets/1675667/0aa60ac2-f2c8-4a96-ba1d-f8d940aa174c">

**Comment by randybascue** [comment]
The visual name is correct. I'm not sure why that file is trying to use variables since it doesn't have access to the core variables

**Comment by ArtBlue** [comment]
Thanks, @randybascue . Any luck on that table? Our code freeze is tomorrow. If we can get that soon, we can get this into the release.

**Comment by randybascue** [comment]
We have a [visual migration table](https://www.figma.com/design/kRncCBxmHGoiSf5imuHNRM/Color-Migration-2024?node-id=74-7554&t=HKuMn6FjHDkaE0cO-11) that shows some of the less intuitive mappings, like `lime` to `avocado`. Didn't want to overload on citrus ;)

**Comment by ArtBlue** [comment]
Thanks, @randybascue ! That's very helpful!

**Comment by ArtBlue** [comment]
@randybascue , is this a mistake or intentional? Two distinct colors are being renamed to a single token with the same color.

<kbd><img width="1193" alt="image" src="https://github.com/eBay/skin/assets/1675667/0cf06df6-f5d3-4c7a-b9c7-0a1cfd4893a6"></kbd>

**Comment by randybascue** [comment]
@ArtBlue I believe it was intentional. Checking with Ryan now

**Comment by ratinsl** [comment]
Yes, that is correct! Those two "green" colors were very close to each other and the closest color was Kiwi 600. Kiwi 500 and Kiwi 700 are both to drastic of a change - which is why they both visually map to the same new color.

The same thing happens in the Lime to Avocado visual migration.

**Comment by ArtBlue** [comment]
@randybascue , @ratinsl , in that case, shouldn't we be using only one of those tokens? it seem very odd to have 2 tokens pointing to the same color.

**Comment by ArtBlue** [comment]
@randybascue , @ratinsl , another questions...

I don't see `lime` in the new core tokens and this transition is only moving only some of the current tokens. Are we sunsetting `lime-1`, `lime-5`, and `lime-6`. 

<kbd><img width="865" alt="image" src="https://github.com/eBay/skin/assets/1675667/be0027fd-1513-4334-a2d0-96a8099145dc"></kbd>

**Comment by ratinsl** [comment]
And yes, lime 1, 5, 6 are no longer going to be used. If you already added the core colors - this visual migration table is meant to help "point" the old colors/names - to their visual partners in the new system.
