### ISSUE TITLE
Venmo icon: Missing borders

### ISSUE THREAD

**Issue by HenriqueLimas** [eBay/skin#2265]
### I verified there's no existing issue for this bug.

- [X] There are no existing issues

### Current behavior

Venmo doesn't have border as the other payment methods

<img width="470" alt="Screen Shot 2024-02-07 at 11 35 15 AM" src="https://github.com/eBay/skin/assets/2222191/06d72c88-ce1b-472b-8414-420be2c9fbc7">

### Expected behavior

Expectation is that Venmo icon has borders in it

### Skin version

17

### Steps to reproduce

```bash
Check Venmo icon on https://opensource.ebay.com/skin/#icon
```

**Comment by ArtBlue** [comment]
The icon we originally got was likely missing `stroke-width` on the rect. The other similar ones that do have the outline visually do have the `stroke-width`; this one icon does not.

To fix this, we simply need to add `stroke-width="1"` to the `rect` to look like this:

```html
<rect x=".5" y=".5" width="49" height="31" rx="1.5" fill="#fff" stroke="#000" stroke-width="1"></rect>
```

**Comment by ratinsl** [comment]
@ArtBlue 
Here is the zip drive with the venmo assets with the stroke.
[240207_venmo_stroke_assets.zip](https://github.com/eBay/skin/files/14201060/240207_venmo_stroke_assets.zip)

**Comment by ArtBlue** [comment]
Thanks, @ratinsl !

**Comment by ArtBlue** [comment]
@ratinsl , I downloaded your zip file, and it looks like the `stroke-width` is still missing from the `rect`. Maybe whatever export issue caused this, caused the original exclusion?

<img width="876" alt="image" src="https://github.com/eBay/skin/assets/1675667/dfcd3354-a608-4a80-bc28-abb548860910">

**Comment by ratinsl** [comment]
@ArtBlue updated package with stroke-width added to all. Please test these.
[240214_venmo_stroke_assets.zip](https://github.com/eBay/skin/files/14285044/240214_venmo_stroke_assets.zip)
