### ISSUE TITLE
new module: education-notice

### ISSUE THREAD

**Issue by randybascue** [eBay/skin#2271]
## Feature Request
Update the education notice visual treatment to differentiate further from the alert notice. Increase sizing and spacing to make it more prominent for feature and recommendation callouts. 

## Description
Education notices are supplemental, contextual messages that educate users about programs, features, and opportunities.
[Figma branch](https://www.figma.com/file/zEBdEhbonrBOGzZ0fXzWvM/branch/rSJeczAN0rQ0jA41TOSJrY/eBay-Design-System?type=design&node-id=90732-97759&mode=design&t=CmHqFcVODBrP7uxl-11)

## Context
1. Seller hub
2. Listings
3. Campaign management
4. Ads
5. Coupon creation

## Screenshots

![image](https://github.com/eBay/ebayui-core/assets/35155833/1d7bdaef-80c9-4c3e-bdc7-33c34b5f5074)
![image](https://github.com/eBay/ebayui-core/assets/35155833/5e1cd9a8-b1c1-4ccd-8317-7dc10d4f1c86)

## Figma link

https://www.figma.com/file/zEBdEhbonrBOGzZ0fXzWvM/branch/rSJeczAN0rQ0jA41TOSJrY/eBay-Design-System?type=design&node-id=90732-97759&mode=design&t=CmHqFcVODBrP7uxl-11

### Engineering pre-requisites

- [X] Successful design review with Design System Team.
- [X] Supports dark mode.
- [X] Supports responsive design.
- [X] Tokens have been provided (or already exist).
- [ ] Successful accessibility review with Core A11Y Team.
- [ ] Successful frontend review with eBayUI Team.

**Comment by randybascue** [comment]
> We actually don't have an `education-notice` module in Skin. We originally built the education visual into section-notice with just an icon flexibility. The Figma on the issue looks fairly different so it's not just an "update visual treatment." We need to create a new module in Skin.

Oh. I see. I wasn't aware of the combination there. Thank you for the clarification

**Comment by randybascue** [comment]
Yeah, it's primarily a layout update.
- Description moves to its own line
- Increases gap spacing
- Increased corner radius
- Title is now **required**
- They can be used in carousels

**Comment by ArtBlue** [comment]
Thanks, @randybascue! Given the many differences as well as anticipated future enhancements, we're going to move forward with upgrading this to its own module.
