### ISSUE TITLE
ebay-calendar, ebay-date-textbox: add docs and story for disabled textbox with disabled icon

### ISSUE THREAD

**Issue by pranaykondekar** [eBay/skin#2284]
Skin should demonstrate the usage of the disabled modules...

* in the docs, add an example for the disabled modules with disabled icon handling
* add a story for the disabled module with the disabled icon

**Comment by agliga** [comment]
Can you provide a screenshot for this?
This is actually an invalid issue since you can pass `disabled` to icon-btn as well and disable it. 

For ebayui we need to add disabled attributes to component, but this seems like a skin issue.

**Comment by ArtBlue** [comment]
After an internal discussion with Luke, it does look like a styling change is not needed in Skin. However, we do need to add documentation/example and a story to demonstrate the feature. We will be repurposing this issue for that purpose.

**Comment by ArtBlue** [comment]
I'm also removing the bug tag as this is not technically a bug, but a missing feature.
