### ISSUE TITLE
icon-button: refactor module and remove overrides in other modules

### ISSUE THREAD

**Issue by ArtBlue** [eBay/skin#2295]
### I verified there's no existing issue for this bug.

- [X] There are no existing issues

### Current behavior

`icon-button` currently has a negative outline-offset: `outline-offset: -10px;`...

![image](https://github.com/eBay/skin/assets/1675667/53f0733e-fcda-430a-a1c1-243214cbafa2)

The modules that use it have to resort to creating overrides to utilize it properly. 

![image](https://github.com/eBay/skin/assets/1675667/48b79063-d450-4662-a3bf-798ce7bf4617)

### Expected behavior

Ideally, there should be no negative offset and except in the rarest of cases. Modules should be able to use `icon-button` with its modifiers to achieve the desired effect.

### Skin version

17.3.0

### Device/OS/Browser info

(all)

### Steps to reproduce

```bash
1. (See details)
```

### Relevant code block

1. Investigate why the negative offset was added in the first place and understand the intent. The negative offset may be needed elsewhere for a more specific use. If so, move it and scope it inside only where needed, if at all.
2. Remote the negative offset.
3. Remove the overrides in other modules that use `icon-button` and see how they each look.
4. Make small adjustments as needed in each module.

**Comment by agliga** [comment]
We need to remove all custom outline offsets and then for transparent modifier to add a custom outline offset so it does not focus on the padding/border area but directly on the icon.
