### ISSUE TITLE
Image: Account for disabled state

### ISSUE THREAD

**Issue by randybascue** [eBay/skin#2319]
## Problem
There are situations where an image is interactive but disabled, or nested within an element that is disabled. This is not currently accounted for within the system.

## Solution
Add a disabled treatment for images to further reinforce its state that desaturates and reduces its opacity.

## Specifications
**Opacity = 0.32 or 32%
Adjustment layer = Desaturation**
We can add a token for the opacity called `opacity.interactive.disabled`?

## Acceptance criteria
A disabled state treatment is available in production that desaturates the image and reduces its opacity.

## Notes
This was discussed in a previous issue.

### Screenshots

![image](https://github.com/eBay/skin/assets/35155833/80f118ba-7b05-4661-a6f3-f2dae9a8c539)

### Engineering pre-requisites

- [X] Successful design review with Design System Team.
- [X] Supports dark mode.
- [X] Supports responsive design.
- [X] Tokens have been provided (or already exist).
- [ ] Successful accessibility review with Core A11Y Team.
- [X] Successful frontend review with eBayUI Team.

**Comment by agliga** [comment]
Probably will add either a token for this, or an `image-disabled` class in util.
