### ISSUE TITLE
lightbox dialog: Title should wrap instead of using ellipses

### ISSUE THREAD

**Issue by LuLaValva** [eBay/skin#2333]
### I verified there's no existing issue for this bug.

- [X] There are no existing issues

### Current behavior

Text in the title of lightbox dialog is truncated with ellipses instead of wrapping

### Expected behavior

Title text should wrap

### Skin version

17.4.1

### Device/OS/Browser info

All devices & browsers

### Steps to reproduce

```bash
Create lightbox dialog with header longer than screen width
```

### Additional context

Text wrap was the initial behavior for this component, but there was a push from design systems team to truncate with ellipses instead. This should not have been approved because, especially after internationalization, there are likely to be cases where the title is impossible to read for some users.

Even in the worst case with text wrapping, the body will still be visible:

![image](https://github.com/eBay/skin/assets/26027232/e0ec37d9-7bf4-418b-b931-a1b3d3150b76)

https://github.com/eBay/skin/assets/26027232/3ada6517-fda4-492d-928a-3d27859b1e00

As such, title should be reverted back from truncation to wrapping.

**Comment by randybascue** [comment]
Agreed. Let's revert to wrapping. We'll update on our end as well
