### ISSUE TITLE
ebay-listbox: add support for secondary text

### ISSUE THREAD

**Issue by randybascue** [eBay/skin#2337]
### Problem
Teams need support for secondary text within listbox options to indicate additional metadata about a value.

### Solution
Add support for secondary text within listbox options.

### Acceptance criteria
- A property is available in ebay-listbox that toggles the visibility of a trailing secondary text layer. 
- The secondary text trails inline with the value title. 
- The secondary text remains visible when the value is selected and added to the ebay-listbox-button
- The secondary text can be toggled for individual options within a listbox, not an all or nothing property.

### Screenshots

![image](https://github.com/eBay/skin/assets/35155833/d233427d-8572-4538-9a92-bed26dcc4e6d)

### Figma link

https://www.figma.com/design/zEBdEhbonrBOGzZ0fXzWvM/branch/JdngVk3p7QZv2ztBhy70ht/eBay-Design-System?node-id=217571-39131&t=gxnxopcxHPwuhUIA-11

### Engineering pre-requisites

- [X] Successful design review with Design System Team.
- [X] Supports dark mode.
- [X] Supports responsive design.
- [X] Tokens have been provided (or already exist).
- [X] Successful accessibility review with Core A11Y Team.
- [X] Successful frontend review with eBayUI Team.

**Comment by agliga** [comment]
Closing, will be ebayui only
