### ISSUE TITLE
Label: improve support for 200% font-size increase

### ISSUE THREAD

**Issue by ianmcburnie** [eBay/skin#234]
Things look a little tight when font-size is increased 200% using custom style sheet:

<img width="382" alt="screen shot 2018-06-21 at 10 10 21 am" src="https://user-images.githubusercontent.com/38065/41734367-8505dee2-753b-11e8-91e9-8c5036327766.png">

To test, create a style-sheet on your local machine with following rule:

```css
html {
    font-size: 200%;
}
```

Then in Safari, go to Preferences -> Advanced - > Style sheet, and select your style sheet.

**Comment by msendlakowski** [comment]
Fixed with https://github.com/eBay/skin/pull/336
