### ISSUE TITLE
Menu: Add primary modifier

### ISSUE THREAD

**Issue by PrashantAshok** [eBay/skin#235]
In order to support having `button` & `menu` side-by-side, menu also needs to support `primary` modifier. 

<img width="312" alt="screen shot 2018-06-20 at 4 41 57 pm" src="https://user-images.githubusercontent.com/5200733/41736882-99f8cf24-7542-11e8-85f0-0cea29b68ea4.png">

The relevant code [lines](https://github.com/eBay/skin/blob/5.1.0/src/less/button/ds6/button-base.less#L117)

EDIT (Ian):

We basically need to replicate the `.expand-btn--primary` and `.expand-btn--secondary` from DS4 into DS6:

![screen shot 2018-06-27 at 1 39 14 pm](https://user-images.githubusercontent.com/38065/41998425-9500d972-7a0f-11e8-8114-1943449e16df.png)

**Comment by ianmcburnie** [comment]
Background SVGs are no longer in doubt. Hooray! So let's do this.
