### ISSUE TITLE
<ebay-date-textbox>: <date format incorrect for fr-CA locale>

### ISSUE THREAD

**Issue by kentokage** [eBay/skin#2369]
### I verified there's no existing issue for this bug.

- [X] There are no existing issues

### Current behavior

I see that the date format is AAAA-MM-JJ for `fr-CA` locale

https://opensource.ebay.com/ebayui-core/?path=/story/form-input-ebay-date-textbox--default&args=disabled:!false;value:1721286000000;locale:fr-CA

But according to our company L10N standards, it should be `dd/mm/yyyy`

Is `AAAA-MM-JJ` date format intended for `fr-CA` locale?

![image](https://github.com/eBay/skin/assets/206663/dbe9396c-dcc2-4c01-8a84-07d29bc48a7c)
![image](https://github.com/eBay/skin/assets/206663/d99e894d-fe64-4f2f-b818-22ae1ff14e94)

### Expected behavior

According to our company L10N standards, it should be `dd/mm/yyyy`

### Skin version

18.0.1

### Steps to reproduce

```bash
https://opensource.ebay.com/ebayui-core/?path=/story/form-input-ebay-date-textbox--default&args=disabled:!false;value:1721286000000;locale:fr-CA
```

**Comment by agliga** [comment]
Closing, this is an ebayui issue.
