### ISSUE TITLE
<ebay-button>: Inconsistent style for secondary href button

### ISSUE THREAD

**Issue by tinxie131** [eBay/skin#2382]
### I verified there's no existing issue for this bug.

- [X] There are no existing issues

### Current behavior

Inconsistent style for secondary href button
 
<img width="1039" alt="Screenshot 2024-07-15 at 10 49 59 AM" src="https://github.com/user-attachments/assets/9dc13221-cf94-4336-ad4f-dcc5924aa6d2">
<img width="1034" alt="Screenshot 2024-07-15 at 10 50 38 AM" src="https://github.com/user-attachments/assets/120ebd97-6c0d-45fe-a1ae-1cb578130d9f">

### Expected behavior

They have same look.

### Steps to reproduce

```bash
1.
2.
3.
...
```

**Comment by agliga** [comment]
Fixed in skin `18.0.6`
