### ISSUE TITLE
docs(tokens): Show semantic tokens before primitive

### ISSUE THREAD

**Issue by LuLaValva** [eBay/skin#2383]
### Description

We should show semantic tokens first since they are recommended, and primitive tokens should be surrounded by a disclaimer that they should not be used unless absolutely needed. It may also be nice to hide primitive tokens behind a `<details>` menu.

### Engineering pre-requisites

- [ ] Successful design review with Design System Team.
- [ ] Supports dark mode.
- [ ] Supports responsive design.
- [ ] Tokens have been provided (or already exist).
- [ ] Successful accessibility review with Core A11Y Team.
- [ ] Successful frontend review with eBayUI Team.

**Comment by agliga** [comment]
Fixed in skin `18.0.6`
