### ISSUE TITLE
ebay-textbox: placeholder variant has issue with border radius

### ISSUE THREAD

**Issue by cgg12345** [eBay/skin#2386]
### I verified there's no existing issue for this bug.

- [X] There are no existing issues

### Current behavior

the background of the input box has right angle corners while the textbox has curved corners. During autofill, the corners of the background overlap with textbox border.

### Expected behavior

No overlap on the corners
<img width="907" alt="Screen Shot 2024-07-17 at 4 28 50 PM" src="https://github.com/user-attachments/assets/cdc0f23c-0fa6-4b0d-ae65-c7b8cbc47921">

### Skin version

"@ebay/ebayui-core@^14":
  version "14.0.0"
"@ebay/skin@^18":
  version "18.0.0"

### Device/OS/Browser info

Latest chrome
<img width="409" alt="Screen Shot 2024-07-17 at 4 28 20 PM" src="https://github.com/user-attachments/assets/9457d013-3bf5-4bba-899e-da06eef70481">

### Steps to reproduce

1. Go to https://opensource.ebay.com/ebayui-core/?path=/story/form-input-ebay-textbox--floating-label-autocomplete and
2.  select something to autofill the textbox

### Additional context

https://ebay-eng.slack.com/archives/CK8AX1L49/p1721258395514349

**Comment by ArtBlue** [comment]
I can't reproduce this. 
<img width="1567" alt="image" src="https://github.com/user-attachments/assets/f843a797-de68-4351-9385-98858648e108">

I did notice that the ebay ui storybook is not getting the options to update the component. For example, changing to input size doesn't make the textbox large. I had to manually add the modifier to try to reproduce this.
