### ISSUE TITLE
textbox: Width of the input not respecting the container size

### ISSUE THREAD

**Issue by HenriqueLimas** [eBay/skin#2404]
### I verified there's no existing issue for this bug.

- [X] There are no existing issues

### Current behavior

Current textbox structure change is not setting the textbox as responsive. There is a min width that is being set (I suppose by the browser). Before `textbox__control--fluid` was adding the `width` to the `input` element, but now the `input` element doesn't have a `width` to it, causing the browser to not respect the width container properly. By adding a `width: 100%` it works as expected

<img width="891" alt="Screenshot 2024-07-29 at 2 10 18 PM" src="https://github.com/user-attachments/assets/2a497402-a366-4f28-93d7-14d67fb4c6bb">

### Skin version

18.0.8

**Comment by ArtBlue** [comment]
Closing issue since PR's been merged.
