### ISSUE TITLE
Floating textbox label not aligned properly on page load

### ISSUE THREAD

**Issue by prabhurangan** [eBay/skin#241]
login to qa.ebay.com & see if you are prompted to new login page (as screenshot attached)
by default the credentials will be pre-filled, if you have saved it
do not click on the browser page, see the floatable text being overlapped.

<img width="335" alt="screen shot 2018-06-27 at 2 59 26 pm" src="https://user-images.githubusercontent.com/16012151/42003015-3de1bed6-7a1e-11e8-8ed4-e8b6710e3ec4.png">

**Comment by prabhurangan** [comment]
1. login to qa.ebay.com & see if you are prompted to new login page (as screenshot attached)
2. by default the credentials will be pre-filled, if you have saved it
3. do not click on the browser page, see the floatable text  being overlapped.

**Comment by ianmcburnie** [comment]
@prabhurangan Thanks, we shall investigate and make sure this is working for you before 5.1.0 final release. I presume this is using the current 5.1.0-0 beta.

**Comment by ianmcburnie** [comment]
This is a javascript issue. The app is responsible for handling this logic and setting HTML class accordingly.

We also have a plugin/module, and this issue is also being tracked here: https://github.com/makeup-js/makeup-floating-label/issues/1

Closing as "invalid"
