### ISSUE TITLE
Item tile: EEK icon size

### ISSUE THREAD

**Issue by fwg001** [eBay/skin#2447]
### Description

Item Tile component displays the Eek icon at a different size from the DS spec. 
The [design system spec](https://www.figma.com/design/zEBdEhbonrBOGzZ0fXzWvM/eBay-Design-System?node-id=127302-223990&m=dev) shows 24px height for Eek Icon whereas [Skin sets its height to 28px](https://github.com/eBay/skin/blob/master/src/sass/eek/eek.scss).
Please update skin to 24px.

### Screenshots

<img width="833" alt="Design spec" src="https://github.com/user-attachments/assets/0824e9c4-1fbe-4271-a23f-a745f57f6b64">

### Figma link

https://www.figma.com/design/zEBdEhbonrBOGzZ0fXzWvM/eBay-Design-System?node-id=127302-223990&m=dev

### Engineering pre-requisites

- [X] Supports dark mode.
- [X] Supports responsive design.
- [X] Tokens have been provided (or already exist).

**Comment by agliga** [comment]
We need the svg asset for the outline arrow in order to fix this.

**Comment by agliga** [comment]
This is the asset we have from design. Its 28px viewbox height. 

https://github.com/eBay/skin/blob/master/src/svg/icon/icon-eek-arrow.svg

**Comment by agliga** [comment]
This also could be a possible breaking change since we are changing the height and need the icon to be swapped out.

**Comment by ratinsl** [comment]
@agliga try this 24px asset out. The original asset looked pretty chopped up on the corners. I adjusted everything to not be chopped off. Let me know how it looks or if I need to make any more adjustments.

![icon-eek-arrow
<img width="877" alt="Screenshot 2024-09-20 at 10 39 23 PM" src="https://github.com/user-attachments/assets/d7470228-208f-4f7c-be1c-6f719ec7d216">
](https://github.com/user-attachments/assets/d593c7ef-9e18-4f3a-80ca-49455fc43e4f)

**Comment by agliga** [comment]
Will be breaking. Will need to add a variant to show smaller size.
