### ISSUE TITLE
Label: Animation has jank in Safari

### ISSUE THREAD

**Issue by seangates** [eBay/skin#245]
When animating the floating label in Safari there is jank while the font of the label scales.

Example video here: https://slack-files.com/T3U2DUYG4-FBG0FJGKS-97f1cb03c4

**Comment by ianmcburnie** [comment]
Using translate and setting transform-origin to left should do the trick, as demoed here:

https://makeup-js.github.io/makeup-floating-label/

**Comment by ianmcburnie** [comment]
Fixed in 5.1.0-1
