### ISSUE TITLE
ebay-filter-menu: search field header

### ISSUE THREAD

**Issue by randybascue** [eBay/skin#2451]
## Problem
We have received requests across multiple teams for a search field to be available as a header option in menus. The search field is preferred when there is a large amount of values in a menu and the list is being launched from a filter menu.

## Solution
Add support for a search field in a header of the menu component. 

## Acceptance criteria
- A property is available to reveal a search field at the top of the menu.
- The search field narrows the list as characters are entered.
- The search field can be cleared quickly with a trailing clear button.
- The search field matches the design specifications.

### Engineering pre-requisites

- [ ] Supports dark mode.
- [ ] Supports responsive design.
- [ ] Tokens have been provided (or already exist).

**Comment by randybascue** [comment]
This is a ticket for discussion. Still needs to go through checks. Will discuss on Wednesday

**Comment by namtheho** [comment]
Related to this — https://www.figma.com/design/fKIKRqbxJF0IuP0yjIJrdC/Brand-Hub?node-id=1377-167641&node-type=frame&t=t3Z0qGXU5pJEwQIF-0

**Comment by agliga** [comment]
Should be good to implement, just need final specs from design.

**Comment by randybascue** [comment]
![image](https://github.com/user-attachments/assets/ac630a9a-cf8b-426a-9f63-ccab8fa7bbea)

**Comment by namtheho** [comment]
Here are some additional context for the requirements pulled from this doc: https://docs.google.com/document/d/1_4pWNKJ-ZnJT6tRht7zibtlukhpzRJSi894-r4-bGUg/edit?tab=t.0

- Multi-Brand selector - functional requirements (designs [here](https://www.figma.com/design/fKIKRqbxJF0IuP0yjIJrdC/Brand-Hub?node-id=1377-167641&node-type=frame&t=9qxU7r1EG42odqkL-0))
- Sort brands alphabetically 
- Allow search for brands 
- Once a brand is being typed, automatically start filtering for brands with each keystroke
- Only update dashboard content when apply button is clicked (i.e. selected brands do not impact the page data until the apply button is clicked)
- If the user has access to only one brand, disable drop-down
- Allow multi-select  (up to 40) 
- Differentiate between parent and children brands (i.e. hyphenation Parent Brand - child brand) 
- Only children should be selectable, but once parent is selected, all children are selected. If Parent is unselected, all children are selected.
- Only show brands that are available in the selected marketplace
- Error state when no brand is found.

**Comment by randybascue** [comment]
![image](https://github.com/user-attachments/assets/0ee9c96e-1d40-44d8-9ed1-0b41e7936a31)

**Comment by randybascue** [comment]
https://github.com/user-attachments/assets/e35c3c1e-d9c1-404a-8b5a-77d6bfb8414f

**Comment by randybascue** [comment]
https://www.figma.com/design/jFbAR0o364WhsjELfxl2SI/Playbook-2.0-%2F-Components?node-id=7939-7963&node-type=frame&t=Oz2rCxRuOGwNIOBw-11
