### ISSUE TITLE
Button: support primary expand-btn in DS6

### ISSUE THREAD

**Issue by yomed** [eBay/skin#249]
A use case came up in https://github.com/eBay/ebayui-core/issues/219 for applying priority to the `expand-btn` as used in the menu case. This is actually supported in the older DS4 styles, but does not work in the new DS6 styles. Can verify by trying to apply `expand-btn--primary` to the `expand-btn` example.

**Comment by ianmcburnie** [comment]
@yomed This was added recently in https://github.com/eBay/skin/pull/243.

Will be releasing this in 5.1.0-1.
