### ISSUE TITLE
Menu: expand button icon override uses same specificity as other icons

### ISSUE THREAD

**Issue by yomed** [eBay/skin#250]
The `svg.expand-btn__icon` CSS overrides were added recently to force a height and width: https://github.com/eBay/skin/pull/240/files#diff-156290700c9ff263b06718dea8f6f7baR268

These carry the same specificity as other icons. Therefore, if the `icon.css` was loaded after `button.css`, these overrides would not correctly apply. In the mean time, I can work around this by switching the loading order, but wanted to check if this is expected.

<img width="319" alt="screen shot 2018-07-03 at 9 59 24 am" src="https://user-images.githubusercontent.com/3595986/42233993-e1a7264a-7ea7-11e8-9707-b85efffa200a.png">

**Comment by yomed** [comment]
Are `expand` and `cta` icons specifically supposed to avoid including the typical `icon` and `icon--name` classes?

**Comment by ianmcburnie** [comment]
Yes.

**Comment by yomed** [comment]
Ok, feel free to close if you're fine with the downstream implications in https://github.com/eBay/ebayui-core/pull/240
