### ISSUE TITLE
Discussion: use BEM to change design system, rather than Lasso

### ISSUE THREAD

**Issue by ianmcburnie** [eBay/skin#255]
If we are moving forward with a guarantee that the markup for ds4 and ds6 *core modules* will be kept in sync (i.e. the *bones* remain the same), then we can perhaps rethink how our Lasso flags work. Instead of using solely a Lasso flag to change design system, we could maybe leverage a BEM modifier.

The recent refactor of the checkbox module is a good example of how we could do this now. All common styles have now been shuffled into a `base` file. The delta styles (icons, colours, etc) that differentiate each design system have been moved into 2 separate files.

The base CSS could always be served to the page, and the delta CSS served only conditionally based on a Lasso flag. BEM modifiers would be required like so:

```html
<span class="checkbox checkbox--ds4">
    <input class="checkbox__control" type="checkbox" name="foo" />
    <span class="checkbox__icon"></span>
</span>
```

```html
<span class="checkbox checkbox--ds6">
    <input class="checkbox__control" type="checkbox" name="foo" />
    <span class="checkbox__icon"></span>
</span>
```

For some modules, with a deep HTML structure, it might require that `--ds4` & `--ds6` modifiers also go on child elements in order to avoid high specificity.

All in all, this would be a big change in design & direction for Skin, but it is one way of allowing ds4 and ds6 (and others) to co-exist on the same page.

By *others*, I mean it also opens the door for custom extensions/themes/experiments, e.g:

```html
<span class="checkbox checkbox--festive">
    <input class="checkbox__control" type="checkbox" name="foo" />
    <span class="checkbox__icon"></span>
</span>
```

In Skin we could document the list of selectors and rules that are open for override (e.g. `checkbox__icon { background-image}`). This becomes even easier when we start using CSS variables. No selectors required then. Just variables.

This might be too big to tackle for v6, but maybe v7...? Or even just hold off altogether until we can start using CSS variables...?

**Comment by senthilp** [comment]
The issue I see here is that on every upgrade, application developers have to do markup changes, which I am not a fan of. With flags, it is more of a configuration, rather than a code change.

**Comment by ianmcburnie** [comment]
@senthilp By "every upgrade", I assume you mean every design system upgrade, right? Like DS4 to DS6? In reality that doesn't happen very often. Every few years maybe. And, as we have witnessed over the last year, seamlessly upgrading from one design system to another is problematic to say the least. Not just for engineering/technical reasons. It may be more practical to have to explicitly opt into a major design system change, and to allow both systems on the page at once.

Again though, this is just a discussion, and I'm not sold either way. I'm playing some devils advocate as usual. So hoping more people chime in with their thoughts.

**Comment by seangates** [comment]
I am of the opinion that we should work hard for a loose coupling of the Design System from the components, thereby allowing us to do what we're doing with DS4 ➡️ DS6 upgrade, where HTML is the same for both, but the styles change.

A la [CSS Zen Garden](http://www.csszengarden.com). The Skin can be "chosen" rather than "enforced". This would also help _Inception_ as it can then move teams forward with components, then later upgrade their Skin.

**Comment by ianmcburnie** [comment]
Yeah, I have always thought of [Bones](https://github.com/ianmcburnie/bones) as a kind of "CSS Zen Garden for widgets". Which reminds me I need to update that project...

**Comment by ianmcburnie** [comment]
Going to close this after our offline discussion.

In summary: it's good that our refactoring can support this different approach if we need it, but we don't need it now.
