### ISSUE TITLE
Menu: svg icon moves slightly on expand/collapse

### ISSUE THREAD

**Issue by yomed** [eBay/skin#261]
I'm looking at SVG icons in the `expand-btn` inside the Menu. This movement seems to be caused by the `border: 0` on `aria-expanded["true"]`, and maybe also related to `align-self: center`.

Typical chevon SVG icon (with rotation manually disabled):
![mov1](https://user-images.githubusercontent.com/3595986/42597256-0de8eee4-850d-11e8-8a75-7a30ccc55ece.gif)

Solo SVG icon in place of label:
![mov2](https://user-images.githubusercontent.com/3595986/42597257-0e039618-850d-11e8-9c07-faca80d39123.gif)

**Comment by yomed** [comment]
This looks like it could be a general issue of sizing these SVGs with flex. In this case, both the settings icon and the chevron toggle become smaller, just due to having more content:
<img width="165" alt="screen shot 2018-07-11 at 2 13 39 pm" src="https://user-images.githubusercontent.com/3595986/42599619-ad022354-8514-11e8-8df4-289ab636fcf6.png">

**Comment by ianmcburnie** [comment]
`flex-shrink` and `flex-grow` usually help with this kind of thing.

**Comment by seangates** [comment]
This is covered in #294.
