### ISSUE TITLE
Checkbox: Change the default checked color according for DS6

### ISSUE THREAD

**Issue by sharma46bhawana** [eBay/skin#267]
Hi! 

According to the https://ebay.invisionapp.com/share/4RDSWVN2D#/309035237_Controls, the default checkboxes when checked, have a fill color of blue instead of black (which is currently in skin).

## Screenshot
![screen shot 2018-07-16 at 4 39 14 pm](https://user-images.githubusercontent.com/6751429/42789203-c89bcc98-8918-11e8-96c8-b561da3a241d.png)

**Comment by ianmcburnie** [comment]
Hmm, this looks like DS4 not DS6. Will try and confirm with design team.

**Comment by seangates** [comment]
@ianmcburnie That screen shot came from design. :wink:

**Comment by ianmcburnie** [comment]
Yep, it's from Invision. But I don't know if this an "update" to DS4 or DS6. Or both. Need to confirm.

**Comment by seangates** [comment]
Checked state for DS4 is blue. Checked state (currently) for DS6 is black. Design wants DS6 checked state to be blue.

**Comment by ianmcburnie** [comment]
Where did you hear this?

**Comment by seangates** [comment]
Conversations with them yesterday, along with @sharma46bhawana. She and I spoke with Greg.

**Comment by ianmcburnie** [comment]
Okay. I wasn't made aware of that. Please put such information in the ticket from now on to avoid churn. There are lot's of invision links and screenshots flying around at the moment, and lot's of churn in general to distract us. I expect we'll see more such potential updates rolling in, but nothing's official until it's official. Let's try and fix our offline process for that and in the meantime we'll keep our focus on the retrofit as that remains #1 priority.

**Comment by msendlakowski** [comment]
Based on the latest design system requirements the blue color is a go.  Fixed in v6.
