### ISSUE TITLE
Button: retrofit/normalize DS6 and DS4

### ISSUE THREAD

**Issue by ianmcburnie** [eBay/skin#268]
Some differences:

* ds4 has `default`, `primary` and `secondary`, whereas ds6 only has `primary` and `secondary`
* ds6 defaults to the default type, whereas ds6 defaults to a "raw" button, with minimal base styles (e.g. height, border, font-family)
* ds6 has CTA buttons (anchor tags)
* ds4 expand button uses arrow-down icon, ds6 uses chevron-down icon
* will add more as I find them...

**Comment by seangates** [comment]
DS4 has `small`, `medium`, `large` and `extra-large` sizes.
