### ISSUE TITLE
Form fields: resize buttons and fields with latest sizes

### ISSUE THREAD

**Issue by ianmcburnie** [eBay/skin#291]
Known issue. We've been planning to address this for a while. Needs doing for v6.

<img width="1024" alt="screen shot 2018-07-29 at 3 16 52 pm" src="https://user-images.githubusercontent.com/38065/43477687-b07b976c-94b0-11e8-93a0-8613a6f73431.png">

**Comment by msendlakowski** [comment]
Will be fixed with https://github.com/eBay/skin/issues/290
