### ISSUE TITLE
ebay-select- ds4- toggle icon is missing

### ISSUE THREAD

**Issue by hramakumar** [eBay/skin#297]
skin 6.0.0-1

ebay-select toggle icon is missing

<img width="272" alt="screen shot 2018-08-06 at 5 08 12 pm" src="https://user-images.githubusercontent.com/13157115/43746822-5db8cb04-999b-11e8-80af-e247e248de54.png">

**Comment by seangates** [comment]
I know why this is happening, and it isn't because of Skin. There is a PR I have to modify the `ebay-select` with slightly different markup for the icon. Therefore, this is a known issue, being tracked here: https://github.com/eBay/ebayui-core/pull/272

**Comment by seangates** [comment]
I will leave this bug here, though, to make sure the PR gets merged.
