### ISSUE TITLE
DS6 Less: Font size variable for 30px should be 1.875rem instead of 1.8625rem

### ISSUE THREAD

**Issue by sharma46bhawana** [eBay/skin#298]
Variable: @ds6-font-size-30

Reference: https://github.com/eBay/skin/blob/master/src/less/less/ds6/variables.less#L62

**Comment by sendlo** [comment]
@seangates   was this a miss or intentional for some weird design reason?

**Comment by seangates** [comment]
I think this was a miss. I did not work on the font sizes, as they were done right before I started on the team.
