### ISSUE TITLE
Docs: Define semantic versioning for CSS

### ISSUE THREAD

**Issue by ianmcburnie** [eBay/skin#3]
We should better define semantic versioning as it pertains to HTML and CSS (reminder: skin does not provide any JavaScript). For example, changes to background and foreground colors. We need to strike a good balance between keeping users up to date with latest design system, but also avoiding any unpleasant surprises.

In the past we were restricted to a kind of hybrid semantic versioning approach, with only the minor and patch numbers to play with. I felt we did a pretty good job, even despite those restrictions. Now though we have major, minor and patch numbers to play with.

To clarify, we **do not** want to stray from the core values of semantic versioning, which are:

* MAJOR version when you make incompatible API changes,
* MINOR version when you add functionality in a backwards-compatible manner, and
* PATCH version when you make backwards-compatible bug fixes.

Rather we should clarify and document what constitutes a "bug fix" and "functionality" and "breaking changes" in HTML and CSS.

Documentation should be placed in README under "Versioning" section.

**Comment by seangates** [comment]
Please take this with a grain of salt, as it's just a free-flow out of my brain, but below are my thoughts.

*Patch:*
- property value changes
- new/removed properties which _do not change_ the basic nature of an component

*Minor:*
- new/removed properties which _do change_ the basic nature of an component
- renaming classes or components
- moving/renaming CSS LESS files
- changing build process/output

*Major:*
- new major changes to the overall underpinnings of the CSS
- new/removed components on a large scale
- new design system

**Comment by seangates** [comment]
@ianmcburnie Thoughts here? Additions / disagreement / agreement?

**Comment by ianmcburnie** [comment]
It's a good start. We should also consider properties that affect layout (shifting the page around) as opposed to those that don't.

**Comment by seangates** [comment]
@ianmcburnie I think we're doing this pretty well, yeah? Could we close this? Or, do you still want to formalize it in some way, like in the README?

**Comment by ianmcburnie** [comment]
I'd definitely like to formalize it in the README.

**Comment by scttdavs** [comment]
my initial thoughts would be a pretty simple. This takes into account only how the user/clients use it, not internal implementation (like changing of file names, directories)
**patch**: bug fixes only
**minor**: new/altered features, for example anything requiring updating of class names to supported features, deprecations (not removals)
**major**: breaking changes, removal of deprecated features

I would say the difference between breaking changes and altered features would be something simple like updating a class name would be altered, but revamping how it is implemented entirely is breaking (like icon fonts to inline svg).

**Comment by oxala** [comment]
Changing top-level class should be considered a breaking-change, imo.

**Comment by seangates** [comment]
@scttdavs I think "breaking changes" is the biggest piece to crack, since we want to clearly define what that means for users of CSS.

What does it mean to "break" things for a CSS user?

**Comment by oxala** [comment]
Well, if i will update skin to latest version and all my `.btn.fake-link` won't work, because you renamed it to `.btn.fake-btn` - that broke my page. :-(

**Comment by seangates** [comment]
Define "won't work"? (Seriously.)

**Comment by ianmcburnie** [comment]
@oxala When we rename classes, we typically leave the old classname in place until the next major version.

**Comment by sendlo** [comment]
Any breaking change is supposed to be a major version change, right?  So a lot of those things in Sean's initial "minor" and "patch" list are not backwards compatible.  You could have a patch change that changes "display: inline" to "display: block" and that would really be a breaking change.

Can we identify a smaller list of exceptions to that rule, which would trigger a major version change.  Like changes to display, visibility, position, float?

I like Scott's approach:

- Patch: Bugfixes only

- Minor: New features where old functionality and structure is not removed. Maybe define a whitelist of property values that are allowed to be changed and still qualify as minor (font-size, padding) or a blacklist (display, float)

- Major: Anything that changes existing class names or DOM structure

If there is a significant change but we aren't ready to release a new skin version, can we make the change backwards compatible until we are ready for a major release.  Like:

.dialog {}
.dialog.sk2 {}

So users that want to use sk2 can just add "sk2" to the dialog class, but the old one isn't effected?  This would result in a little bloated CSS until major versions.  But its better than production surprises.

**Comment by ianmcburnie** [comment]
I've updated the issue statement to better reflect the goals here.

**Comment by mlrawlings** [comment]
> When we rename classes, we typically leave the old classname in place until the next major version.
If this is the case, I'd say renames are fine as minor.  It's like deprecating a feature.  It would be really nice if there were some way to let the user know a selector is deprecated without visually impacting the page...

**Comment by sendlo** [comment]
I can't remember where I saw this, but we could do something like this:

.oldelement::after {
  visibility: hidden;
  content: url(path_to_deprecation_pixel.png?selector=oldelement);
}

Then we could track down all referring urls to that image in the server logs.

**Comment by ianmcburnie** [comment]
I like the simplicity of keeping patch just for bug fixes. But does the following constitute a bug fix:

Changing:

```css
body { 
   font-family: "Market Sans", "Helvetica Neue", Helvetica, Arial, Roboto, sans-serif; 
}
```

to:

```css
body { 
  font-family: "Market Sans", Arial, sans-serif; 
}
```

This was never a "bug", just an evolution of the design system. This is where we blur the lines a little I think because this going out as a patch would have minimum impact/risk (because only the fallback font is changed) and therefore is the easiest and quickest way to get this evolution of the DS out into our pages.

**Comment by seangates** [comment]
Unless ... teams have relied on a certain font, in certain browser versions, and have overridden specific styles to accommodate. (E.g. Overriding container widths or heights based on the font size/width.)

... Which they shouldn't be doing, but still.

I still stand by this being a patch, because the _fallback_ is what is changed. Not the primary property value.

**Comment by ianmcburnie** [comment]
Also, I guess I'm still in the mindset of our previous hybrid semantic versioning, when we only had minor and patch to play with, and so "overloaded" them a little. When I think about it, with true semantic versioning now, this going out as minor can still be consumed as quickly as a patch.

**Comment by seangates** [comment]
Very true.

**Comment by ianmcburnie** [comment]
From the feedback (thanks everyone) it seems that most people are in favour of keeping a patch strictly for bug fixes only, and not for small visual evolutions of the design system. I agree. So I've decided I'm going to keep this simple, and not blur the lines of what constitutes a "patch". A patch will always be for backwards compatible bug fixes only.

Also, given that we have actual version numbers at the playbook component level now (we didn't when this ticket was created), and component visual updates are now typically batched together (rather than done in one-off, isolated cases as they were in the past), it totally makes sense to push those out in minor versions on our side rather than be tempted to put them out as patch releases.

I will update the README with these clarifications. I will also call out some examples of what is a breaking change and what isn't.
