### ISSUE TITLE
textbox: placeholder text color is too light to be seen. 

### ISSUE THREAD

**Issue by hramakumar** [eBay/skin#303]
textbox: the placeholder text color is too light.
Need to increase the color contrast
![screenshot_20180809-152059](https://user-images.githubusercontent.com/13157115/43929072-33f07462-9be8-11e8-99e1-1af6ac41958a.png)

**Comment by seangates** [comment]
This appears to be from Chrome on Android. Is that correct? Could you add whether it's on all browsers?

**Comment by hramakumar** [comment]
yes thats chrome on android

**Comment by seangates** [comment]
So, this only happens in Chrome on Android?

**Comment by seangates** [comment]
Please be specific.

**Comment by msendlakowski** [comment]
Confirmed that the placeholder font color should be #767676 but its #c7c7c7 right now.
Leaving this for Prabhu who's starting on Wednesday.
