### ISSUE TITLE
Expose variables and mixins as SASS/SCSS

### ISSUE THREAD

**Issue by ianmcburnie** [eBay/skin#31]
There has been an interest in supporting SASS, for apps on the react/sass/webpack stack.

We could perhaps expose our variables and mixins using a LESS to SASS [convertor](https://www.npmjs.com/package/less2sass).

Further investigation and discussion needed.

**Comment by senthilp** [comment]
Wow, really? I thought we are on the path of getting rid of CSS preprocessors :smile:

**Comment by ianmcburnie** [comment]
We have to kill IE11 first, right?

**Comment by seangates** [comment]
Not really on the roadmap, and any "interest" has dwindled. Closing.
