### ISSUE TITLE
Some elements don't seem to support text zoom.

### ISSUE THREAD

**Issue by garcialo** [eBay/skin#321]
WCAG 1.4.4 requires that at 200% text zoom, content is conserved, is still perceivable and all interactive elements are still usable.

A few components on http://ebay.github.io/skin/ds6/ did not seem to retain their readability at 200%. Specifically...

- Buttons
- Fluid Pagination
- Selects
- Underline Textbox (Safari only; test string: "kajiji pogo")

To reproduce:

1. Go to: http://ebay.github.io/skin/ds6/
2. Text zoom to 200% (see instructions below)
3. View the sections for the components listed above

- Firefox: View > Zoom and select Zoom Text Only. Zoom to 200%
- Safari: while holding alt/option, View > Make Text Bigger until you get to 200% (do 4 times total)
- Chrome: Go to Chrome Settings, set Font Size to Very Large (note: not quite 200%)

Note: In Chrome, text for some components did not seem to respect the Font Size setting at all...it was more discernible when Font Size was set to Very Small.

**Comment by seangates** [comment]
Thanks, @garcialo!

**Comment by seangates** [comment]
Fixed in #336.
