### ISSUE TITLE
Select: dweb UI does not match design

### ISSUE THREAD

**Issue by msendlakowski** [eBay/skin#325]
The dweb version of the select field is not styled to match the design pattern.  It should be the same as menu and combobox, though it still has to be a `<select>` so mweb devices will use their default behavior.

Current dweb:
<img width="178" alt="screen shot 2018-08-20 at 9 10 59 pm" src="https://user-images.githubusercontent.com/1562843/44411836-43cd5e80-a51c-11e8-99cc-67788a527cfc.png">

**Comment by seangates** [comment]
Tracked in https://github.com/eBay/ebayui-core/issues/365. Closing here as it doesn't currently involve any Skin changes.
