### ISSUE TITLE
BUG: Small icons with background SVGs distorted in IE

### ISSUE THREAD

**Issue by msendlakowski** [eBay/skin#334]
Was "BUG: Select: checked icon for selected item per page option is cut on the bottom in IE 11"

Moved from: https://github.com/eBay/ebayui-core/issues/204

# Bug Report
Checked icon for selected item per page option is cut on the bottom in IE.

## Workaround
Workaround would be to override locally, but that is not desired.

## Screenshots
![_thumb_1171641](https://user-images.githubusercontent.com/11545472/40680358-b33176fe-633a-11e8-88d3-6a7b39b28756.png)

![image 2](https://user-images.githubusercontent.com/11545472/40686448-2ae22994-634c-11e8-8875-28d3a5e09041.png)

**Comment by seangates** [comment]
@msendlakowski Is this DS4 only, or both DS4 and DS6?

**Comment by msendlakowski** [comment]
@seangates it looks like its only DS6 as far as I can tell

**Comment by msendlakowski** [comment]
After a bunch of testing, it looks like this is due to a bug in how IE11 renders the background-size attribute when it comes to small images.  It has an issue calculating the correct size to render the image.  The best solution I found was to make the image larger and then use transform to scale it back down.  But that would add overhead to all browsers.

Since this is only happening in IE11 (not MS Edge) which is on its way out, and its still functional, I think we can close this as "won't fix".

**Comment by msendlakowski** [comment]
From @martin-ebay in slack:
```
found a small bug in Edge with the ebay-select component.  The arrow gets cut off all sorts of funny.  This is at 100% zoom as well.  Only in Edge.  looks like making the icon a couple pixels wider would fix it.
```
```
maybe my edge is in ie11 mode. let me check real quick but didn’t think so
wonder if it is a slightly older edge version or newer. seeing that in Microsoft Edge 41.16299.492.0
just verified that I’m not using windows text zooming either
saw this on both a native windows machine and a VM as well in case that helps
```
```
when I fiddled with the css adjusting the container from 11px to 14 fixed it but I’m guessing it is because IE is rendering that svg thicker

almost like it has an outline on it
```
