### ISSUE TITLE
icon: clear- cannot add custom color

### ISSUE THREAD

**Issue by hramakumar** [eBay/skin#356]
skin - 6.0.0-3
**ebay-icon type="inline" name="clear" style="color:red"**
this color wont work in ds4

![image](https://user-images.githubusercontent.com/13157115/44751130-2c6a1480-aacc-11e8-8cfe-eeb74ca42dee.png)

**EXPECTED**

![image](https://user-images.githubusercontent.com/13157115/44751205-61766700-aacc-11e8-8159-40c0a87e2f00.png)

**Comment by msendlakowski** [comment]
Yeah, we only have to support the standard DS4 features, which didn't include changing colors on icons.  We can loop back on this and maybe create different SVGs if we find there was a lot of icon color customization.
