### ISSUE TITLE
switch: the disabled and off switch - they both look pretty same- we need to have a better color difference

### ISSUE THREAD

**Issue by hramakumar** [eBay/skin#357]
skin 6.0.0-3  and prev versions

the switch off state and off disabled state looks pretty similar.

pls improve the color contrast
![image](https://user-images.githubusercontent.com/13157115/44751753-da29f300-aacd-11e8-8f27-6bff3822dbcd.png)

this looks worse in devices

**Comment by msendlakowski** [comment]
I think these are pretty accurate to the mocks coming from design.

![screen shot 2018-08-28 at 4 14 30 pm](https://user-images.githubusercontent.com/1562843/44756035-9808ad80-aadd-11e8-926f-27353bcb59ce.png)

https://ebay.invisionapp.com/share/CWN9X1JF6MA#/screens/309035237_Controls

**Comment by msendlakowski** [comment]
Yep. I just did a screen grab of the color and its as close as our color palette will get.  So I'm closing this.
