### ISSUE TITLE
Listbox: new DS6 style

### ISSUE THREAD

**Issue by ianmcburnie** [eBay/skin#38]
Design team have expressed a preference to use the native listbox (i.e. the <select> tag) for mWeb, but a custom, more branded, look and feel for dWeb. This will also allow us to display flags in the listbox (a common requirement).

As we all know, the <select> overlay cannot be styled with CSS. In order to retain the features of the <select> tag (e.g. form data, autofill) we would need to hide the actual real listbox and display a facade view instead. This will mean the listbox will be dependent on javascript (like tabs, menu and dialog) but we can at least provide the CSS support in Skin.

At this point in time I believe the facade for the listbox is going to look just like the DS6 menu, therefore we can probably reuse those styles.

**Comment by seangates** [comment]
Going out on a limb ... what about emoji do flags? I know they would roast me for saying it, but almost all OSes and browsers support them now.

**Comment by ianmcburnie** [comment]
Nice idea. Will check with design. They probably want to brand it in other ways than just the flag, but I will check that too.

**Comment by ianmcburnie** [comment]
Listbox will share a lot of styles (if not all) with menu, but has slightly different ARIA semantics which we want to enforce.

Proposal:

Under the hood, both listbox and menu will resolve to a dropdown.css. This file will utilize grouped selectors, for example:

```css
div.menu__item[role^="menuitem"],
div.listbox__item[role="option"] {

}
```

The one area where these might deviate is when we want to allow icons before the item text (e.g. country flags). Or maybe we just support that in both, I don't see why not.

**Comment by seangates** [comment]
Resources:

**https://www.w3.org/TR/wai-aria-practices/examples/listbox/listbox-collapsible.html** *
https://www.w3.org/TR/wai-aria-practices/#Listbox
https://www.w3.org/TR/wai-aria-1.1/#listbox
https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_listbox_role
http://karlgroves-sandbox.com/CheatSheets/Static-ARIA-Examples.html

* the only working example (in Chrome) the I found

**Comment by seangates** [comment]
First pass at things. Should be fairly close to final, though: https://github.com/eBay/skin/commit/a781367aa616606c72a9e2299fd46ed929eed827

**Comment by seangates** [comment]
Cosed via #50.

**Comment by ianmcburnie** [comment]
So I have been doing a lot of digging around and testing of HTML select/listbox and our current ebayui listbox across screen readers and devices. Ultimately what we have is closest to how OS X treats a select element: as a popup button that expands a menu. Yup pretty much like our current menu component. However, this OS X treatment does not follow the W3C specification. Windows does. Windows treats a select as a readonly combobox.

So it's a difficult situation. Windows screen reader users will not be familiar with our popup button based implementation. Likewise, OS X users might find it odd to hear combobox instead of popup button. But my golden rule is to always go with the spec. If the spec ever happens to change to the OS X treatment, we follow suit. But the windows treatment and spec has been around a LONG time.

So, what this means is that the listbox now becomes quite different from the menu. There was also the issue that we can't give the button a label and a value (which a select can do), because a buttons inner value IS the label. So to accomplish this we have to change the button to a readonly textbox:

<label for="foo">Cars</label>
<input id="foo" type="text" role="combobox" value="Saab" readonly />

Pressing up and down arrow cycles through options. Pressing SPACE expands the listbox of options.

This means we also go back to the drawing board in skin to style a textbox to look like the expand button. Hopefully this is straightforward.

We will probably also need to change the roving tab index keyboard nav to active descendant keyboard nav, so that keyboard focus always stays on the textbox element, but pseudo focus (active descendant) is used to move up and down the listbox. But I will confirm on this.

I am going to update the MIND patterns and hopefully put together a quick prototype.

Also, everything I have written above is for single-select only. I'm hoping multi-select can be achieved by using role="listbox" instead of role="combobox", but more investigation is needed.

Related reading: https://github.com/w3c/html/issues/1013

Key piece from spec:

Allowed ARIA role attribute values:
(with NO multiple attribute and NO size attribute having value greater than 1) combobox or (with a multiple attribute or a size attribute having value greater than 1) listbox

**Comment by ianmcburnie** [comment]
I updated the mind pattern example:

http://ianmcburnie.github.io/mindpatterns/input/listbox/

So far support seems good in IE+JAWS, FF+NVDA, Safari+VO, Chrome + Chromevox

**Comment by seangates** [comment]
Thanks, @imcburnie!

**Comment by seangates** [comment]
Current state of things: https://github.com/eBay/skin/commit/7709f1f4a051109ce4ca6d8b176605aa44f16463

**Comment by seangates** [comment]
Done!
