### ISSUE TITLE
Website: Unable to select a new option in Select & Combobox on iPad

### ISSUE THREAD

**Issue by msendlakowski** [eBay/skin#380]
I’m noticing some issues in selecting on iPad. Particularly selecting options in combo boxes as well as `<select>` fields. 

See video here (internal):
https://ebay.enterprise.slack.com/files/W3YMUD78D/FCMPNPV32/image_from_ios.mp4

Also, what’s *really weird* for a `<select>` is that the OS-driven pop-over did not disappear immediately after selecting, I had to tap outside of it.  Then, I was unable to select another option once I‘ve made my first selection.
It’s supposed to be quick. Like this.

See video here (internal):
https://ebay.enterprise.slack.com/files/W3YMUD78D/FCPGX5E5D/image_from_ios.mp4

Not sure if this is just w/ the demo page itself or potentially a general issue.

**Comment by seangates** [comment]
This appears to be isolated to the Skin documentation, and does not specifically related to the eBayUI Components. We can prioritize with this understanding.

**Comment by ianmcburnie** [comment]
This seems fixed now.
