### ISSUE TITLE
Button: text should wrap when fixed width is applied

### ISSUE THREAD

**Issue by ianmcburnie** [eBay/skin#391]
We had a lot of back and forth on this, and for a long time I didn't want to allow text wrapping of buttons (because it looks crap), but given that the native behaviour of an HTML button is to wrap when a fixed width is applied, then I think we should cater for this. Note that because we set a fixed height by default on our buttons (to align properly with other form controls, across browsers) we may need to utilize a modifier to set the height back to auto.

**Comment by msendlakowski** [comment]
That makes sense, since that's the default HTML behavior.  Hopefully apps would modify their design if they saw the button text wrap.  Its better than current behavior though.

![screen shot 2018-09-20 at 12 47 09 pm](https://user-images.githubusercontent.com/1562843/45843042-54b3f000-bcd3-11e8-8445-c5962d8a7002.png)

Maybe confirm with the design team?  
We could also truncate it, but I think that would require a significant change in the button design since I believe it wouldn't work with flex.

**Comment by ianmcburnie** [comment]
Some history:

A long time back, when we were only supporting mobile, we had the height of our buttons defined via padding and font-size alone. This allowed button text to wrap naturally when a fixed width was applied, but it caused problems when it came to desktop and trying to align buttons with selects, comboboxes, menus, etc. on the same line. Cross browser it was a nightmare (especially as we had to consider the older versions of IE then). So we moved to a fixed height for all of these components which made alignment easy, but broke natural text wrapping.

Ideally we could remove the fixed height and have the height computed from padding and font-size, but we'll need to once more review the situation with horizontal alignment. So maybe as the first part of this task we do that review. If the situation is still not great, then I guess we go ahead with using JavaScript to add a modifier.

**Comment by ianmcburnie** [comment]
It's also possible we could flip the paradigm around: have height computed from padding and font-size by default (typical use case for most standalone buttons), and require a modifier for a *fixed* height (i.e. when aligning buttons with other controls on same line). We would be going more with the grain of native HTML button behavior this way.

**Comment by senthilp** [comment]
By "height computed" you mean the natural browser calculation or using JS?

**Comment by ianmcburnie** [comment]
Yes, I mean the natural browser calculation.

**Comment by ianmcburnie** [comment]
The more I think about this, the more it makes sense. Use natural height by default, and for cases when side by side with other controls (such as textboxes and selects, etc), the app developer can add a modifier to keep the button height fixed if they wish. I think it makes sense because textboxes and selects never wrap to multiple lines.

**Comment by msendlakowski** [comment]
Yeah, I like that approach.  I think the more common case is to rely on the height specified by the browser.  And the outlier is trying to get them to align precisely with other form fields. 

The pill may still be a special case though, as it will look odd if it wraps to 3 lines.

**Comment by ianmcburnie** [comment]
On the Skin side, I think we should just let buttons and pills wrap to as many lines as the content needs. On the EbayUI side we can add the logic to truncate/trim if necessary.

**Comment by ianmcburnie** [comment]
Merged to 7.0.0
