### ISSUE TITLE
Icons: explore process to automatically create and import base64 encoded strings.

### ISSUE THREAD

**Issue by seangates** [eBay/skin#405]
## Description

Currently we manually create the base64 encoded strings from the source SVG. Because some of the icons use color it would be nice to be able to add LESS variables to source SVG, and therefore be able to change the base64 string automatically for our dist.

<strike>
## References

Relevant LESS function: http://lesscss.org/functions/#misc-functions-data-uri

## Example

```
data-uri('image/svg+xml;charset=UTF-8', 'image.svg');
```

## Notes

- This may not work with strings, but only files. If that's the case, this could be a non-starter.</strike>

## Update!

@pcanella Is working on a CLI tool that will export all symbols from Sketch source file to a JSON format (containing name, width, height, base64, optimized svg). That would complete the "export" part. We would then need another script and convention for importing that into a suitable LESS file format for Skin

**Comment by pcanella** [comment]
I'm not sure how useful this would be, but what about extending this so that every time we add an SVG, the work is done for us? Automating that 6 step process could be useful.

**Comment by ianmcburnie** [comment]
It would be EXTREMELY useful!

**Comment by ianmcburnie** [comment]
...especially since the icons are being updated again at some point in the near future.

**Comment by seangates** [comment]
Feel free to explore this, yes!

**Comment by pcanella** [comment]
Awesome! Perhaps I will. I did a bit of work on this in my [FishHarmony](https://www.fishharmony.com) side project; all those "fish" in it are SVGs and I parsed a lot of the stuff out after saving the SVGs in Illustrator 😄 .

**Comment by ianmcburnie** [comment]
Thanks to work by @pcanella we now have a way to create SVG and base64 strings from a sketch source

https://github.com/eBay/SketchSVG

I'm going to change the scope of this ticket to reflect the "creation" side and then close it. I'll create another ticket for the "import" side.
