### ISSUE TITLE
Icons: Feedback icons missing

### ISSUE THREAD

**Issue by PrashantAshok** [eBay/skin#412]
**eBay Skin Version: 5.1.0**

1. The DS6 svg module mentions feedback related icons `feedback-positive`etc. , http://ebay.github.io/skin/ds6/#svg, but they are missing from [icons.svg](https://github.com/eBay/skin/blob/v5.1.0/src/svg/ds6/icons.svg). 

2. Shouldn't there feedback related icons in background/inline svg as well? The mixins/classes are missing in [icon.less](https://github.com/eBay/skin/blob/v5.1.0/src/less/icon/ds6/icon.less) as well .

**Comment by ianmcburnie** [comment]
@PrashantAshok Thanks for raising this issue. Is this a blocker or do you have a workaround for now?

**Comment by PrashantAshok** [comment]
@ianmcburnie not a blocker. Workaround is to use DS4 mixins for now. 

let me know i can send a pr.

**Comment by seangates** [comment]
@PrashantAshok Feel free if it's a small set of fixes!

**Comment by ianmcburnie** [comment]
@seangates @PrashantAshok I don't see these feedback icons in the DS6 Sketch source, so I think they are leftovers from DS4 and have not yet been updated for DS6.

![screen shot 2018-10-24 at 10 44 23 am](https://user-images.githubusercontent.com/38065/47450353-e0f57f00-d779-11e8-9208-e6fb865d1aa7.png)

I think it's best maybe if I just remove these references for now. What do you think?

**Comment by seangates** [comment]
Yeah, let's remove them from DS6, as they are not available.

**Comment by PrashantAshok** [comment]
@ianmcburnie , instead of removing, can we get the DS team to port them over to DS6. Our app currently uses those.

**Comment by seangates** [comment]
@PrashantAshok My fault!! My comments were for a different issue entirely.

**Comment by seangates** [comment]
But ... these are purposefully not in DS6. Can you reach out to the DS team to confirm what you should do?

**Comment by ianmcburnie** [comment]
Agree with Sean, they have been purposefully removed. For now I'll remove the reference. If Design Team want them in DS6 we can create a new issue.

**Comment by ianmcburnie** [comment]
Refs removed in 6.1.0-prerebase branch.
