### ISSUE TITLE
Notice: close button icon is missing

### ISSUE THREAD

**Issue by ianmcburnie** [eBay/skin#413]
Version affected: 6.x

Very quick investigation suggests that `.background-icon-base;` might be missing. If so this fix could go out in next patch release.

Screenshot from current website:

![screen shot 2018-10-15 at 1 03 49 pm](https://user-images.githubusercontent.com/38065/46975197-e0befa80-d07a-11e8-9efe-9876e4b7e45a.png)

Screenshot from archive (5.x):

![screen shot 2018-10-15 at 1 05 08 pm](https://user-images.githubusercontent.com/38065/46975250-fb916f00-d07a-11e8-8847-fc79dc8e9957.png)

**Comment by seangates** [comment]
@ianmcburnie Is the close button always present, even for tooltips? Or is this just to fix the icon because the examples all have close buttons?

**Comment by ianmcburnie** [comment]
It should always be present for the generic kind of flyout notice in DS4, but not necessary when flyout notice is placed inside of a Tooltip or Bubble Help.

**Comment by seangates** [comment]
If it's just for DS4, then 👍 it seems fine to me.
