### ISSUE TITLE
Notice: normalize icon placement for ds4 and ds6 page notice

### ISSUE THREAD

**Issue by ianmcburnie** [eBay/skin#415]
In DS4 the icon is always at the top of the page notice. The text is then aligned to the top of that icon for single line text, or the middle of the icon (using a modifier) for multi-line text. DS6 simplified the situation by always having the icon vertically aligned to the middle, and the text always in the same place.

Let's normalize DS4 to match the DS6 behaviour. We would reduce the complexity of our CSS.

OR...

Let's normalize DS6 to match DS4 behaviour.

DS4 single line text, icon aligned middle:

<img width="391" alt="screen shot 2018-10-16 at 12 25 03 pm" src="https://user-images.githubusercontent.com/38065/47041822-ac147700-d13e-11e8-8adf-95f9cf24688a.png">

DS4 multiline, icon aligned top:

<img width="1137" alt="screen shot 2018-10-16 at 12 25 14 pm" src="https://user-images.githubusercontent.com/38065/47041833-b0d92b00-d13e-11e8-8fcf-3cd82f708402.png">

DS6 single and multi:

<img width="836" alt="screen shot 2018-10-16 at 12 25 28 pm" src="https://user-images.githubusercontent.com/38065/47041851-ba629300-d13e-11e8-8502-b1e5b04feb88.png">

**Comment by seangates** [comment]
Does this need design review, or is DS4 simply "open season" at this point?

**Comment by ianmcburnie** [comment]
Not so much open season, but continuing to apply DS6 principles to DS4. Especially where it helps simplify. The DS6 principle for page notice is that the icon is always centered. We should still run this by them during stand up though.

**Comment by seangates** [comment]
Sure. That would be good. I've heard them say things like "we aren't enforcing DS4 patterns because we didn't have a place for DS4 patterns." A la, Skin was where the source of truth lived/lives.

**Comment by ianmcburnie** [comment]
Also, I know they are removing the solid block of colour on the left from DS6 (shame, I like it!), making DS6 a little more like DS4 I guess.

**Comment by ianmcburnie** [comment]
Where I'm trying to get to is a solid set of blueprints, or rules, that become much more set in stone from DS to DS. This would be one such example:

* Page Notice Icon: Always centered vertically.

or

* Page Notice Icon: Can be centered vertically to top or middle.

We just need them to pick one rule and stick to it.

**Comment by seangates** [comment]
> Also, I know they are removing the solid block of colour on the left from DS6 (shame, I like it!), making DS6 a little more like DS4 I guess.

Oh, I didn't know this was coming. It is a shame.

I prefer the second rule, especially if they take away the background color.

**Comment by ianmcburnie** [comment]
After a sneak peak at latest design mocks it looks like we will be standardizing on the 2nd rule.

**Comment by ianmcburnie** [comment]
@msendlakowski This issue and description will need verifying again as part of DS6.5. If you haven't done so already of course.

**Comment by ianmcburnie** [comment]
@agliga I think in DS6.5 the icon is always centered in the middle (as we had in DS6). If so we can move this issue to v10 and see then if we want to update DS4 to act the same way.

**Comment by ianmcburnie** [comment]
Moving to v10 based on feedback from Andrew. In v10 we can always set icon to center for ds4 and remove the classes that allowed alternate placement.

**Comment by ianmcburnie** [comment]
Done in v10
