### ISSUE TITLE
Select: arrow icon not aligned correctly in IE11

### ISSUE THREAD

**Issue by hramakumar** [eBay/skin#431]
ebay-select  - arrow icon ie 11 - position is not right
![image](https://user-images.githubusercontent.com/13157115/47320783-45dc9800-d607-11e8-8131-da846c0b3f67.png)

**Comment by ianmcburnie** [comment]
I think we'll have this as low priority given that IE11 falls under Tier 2 in our browser policy, and this is fit & finish related.

**Comment by hramakumar** [comment]
ok

**Comment by ianmcburnie** [comment]
Closing as wontfix according to browser policy on IE11 (functional bugs only).
