### ISSUE TITLE
New Pattern: Guidance

### ISSUE THREAD

**Issue by seangates** [eBay/skin#452]
The Design System team has updated page notices to include "guidance". These guidance modules are generally at the top of the page, or within the page, and stretch full width.

This may also force us to consider a renaming of the component, but that is not a desired outcome as it would be a breaking change.

![image](https://user-images.githubusercontent.com/105656/48227392-75a5d280-e35f-11e8-86fd-4b21c6317acc.png)

https://playbook.corp.ebay.com/PlaybookApp#/executional-guidelines/product-design-system/patterns/guidance-modules

**Comment by ianmcburnie** [comment]
Given the blurb from the playbook:

`Guidance modules are used to provide tips, guidance & feedback on section level elements`

I propose calling these "section notices" or "region notices". For example:

* `.section-notice .section-notice--attention`
* `.section-notice .section-notice--confirmation`
* `.section-notice .section-notice--information`

Then in coreui we have 3 types:

* `inline`
* `section`
* `page`

**Comment by ianmcburnie** [comment]
I need to review my previous comment and see if it's still relevant in DS6.5.

**Comment by ianmcburnie** [comment]
Let's go with @agliga's idea of using a modifier on the page notice: `page-notice--guidance` which simply removes the border. We'll also need a new `page-notice--light` modifier, or we could possibly just make light the default (i.e. page-notice with no modifiers).

**Comment by ianmcburnie** [comment]
Done in 9.2.0
