### ISSUE TITLE
Dialog header(H2) is broken with latest skin

### ISSUE THREAD

**Issue by RajaRamu** [eBay/skin#455]
Seeing style issues in dialog>h2 in with `skin@6.0.5` & `ebayui@1.0.6`. we do not see this issue in older versions.

Issues
<img width="1669" alt="before fix" src="https://user-images.githubusercontent.com/1137069/48235784-228a4a80-e374-11e8-8997-40680b4c2a1d.png">

If we remove the styles, it works fine.

<img width="1663" alt="after fix" src="https://user-images.githubusercontent.com/1137069/48235783-228a4a80-e374-11e8-94b8-13ace4325aed.png">

**Comment by ianmcburnie** [comment]
@seangates Can you please investigate and see if this is behaving as expected or not from our point of view. I know there were a lot of changes to dialog from v5 to v6 while I was out.

**Comment by seangates** [comment]
@ianmcburnie My first gut reaction is that ... it's pulling in some DS4 CSS because there should't be any `h2:first-of-type` selectors in DS6. That should be reserved for DS4 only.

**Comment by seangates** [comment]
My second thought is that `inception` is pulling in a DS4 version of the dialog for the page, and the global header CSS will need to be scoped (as seen in the screen shot) in order to have the DS6 styles for their particular dialog.

**Comment by seangates** [comment]
Duplicate DS4 and DS6 code on a page because they weren't setting the `skin-ds6` lasso flag. Closing.
