### ISSUE TITLE
Remove @ebay/skin/icon from combo bundle

### ISSUE THREAD

**Issue by trg** [eBay/skin#457]
As of now; the SVG icons in the combo bundle represent 66% of the bytes in that bundle due to being base64 encoded data URIs.

As the combo bundle is intended to be a common module bundle, I think it makes sense to rip out the SVG icons so most users aren't tripling their bundle size if they choose to use the combo bundle.

If users need a specific SVG icon they can either include `@ebay/skin/icon` separately; or copy/paste the icons they need to minimize overhead.

**Comment by seangates** [comment]
I'm not a fan of copy/paste.

**Comment by senthilp** [comment]
I am proposing the below change to `combo.browser.json`. This makes sense in DS6 world and it is also safe as homepage is the only customer of combo.
```json
{
    "dependencies": [
        "@ebay/skin/core",
        "@ebay/skin/dialog",
        "@ebay/skin/form",
        {
            "if-not-flag": "skin-ds6",
            "dependencies": [
                "@ebay/skin/iconfont",
                "@ebay/skin/icon",
                "@ebay/skin/spinner"
            ]
        }
    ]
}
```
If that looks ok, @ianmcburnie please let me know which release I should send this PR to?

**Comment by ianmcburnie** [comment]
Fixing the following issue would help the current situation: https://github.com/eBay/skin/issues/239

**Comment by ianmcburnie** [comment]
@senthilp Could we flip your approach around a little and add something like an `icon-opt-out` flag? If the app doesn't set this, they would continue to get the icon module. This would allow us to stay backwards compatible until we address this properly in version 7.

**Comment by senthilp** [comment]
@trg Will that 👆be ok with you?

**Comment by seangates** [comment]
We should create the v7 issue now in order to track it properly. Want me to write that up?

**Comment by ianmcburnie** [comment]
Yes please, or feel free to keep this as the v7 issue and create a new ticket for the temporary solution.

**Comment by seangates** [comment]
@trg That's an interesting proposal, but that would only be applicable if they were using background icons and not foreground icons (what others call inline SVGs).

Foreground icons get stamped in the page once, and only when used, making the payload much, much better. Most developers will actually go this direction as they will also have more control over SVG styles, too. It's our recommended way to do things.

Therefore, I think making them opt-out now, and removing them from the bundle in v7, is the right way to tackle this.

**Comment by seangates** [comment]
Created the issue for 6.2.0, #460, since this issue relates to removing the icons from the bundle altogether.

**Comment by ianmcburnie** [comment]
Done in 7.0.0 branch. Closing.
