### ISSUE TITLE
Icon: add confirmation icon to DS6 set

### ISSUE THREAD

**Issue by ianmcburnie** [eBay/skin#475]
I've had a lot of people asking for the following icon:

<img width="33" alt="screen shot 2018-12-11 at 10 00 14 am" src="https://user-images.githubusercontent.com/38065/49819989-97fa8980-fd2b-11e8-950a-10c1f88c5928.png">

Currently it is only available in the inline notice module. I think we should add it to the icon set, maybe along with information and priority too:

<img width="38" alt="screen shot 2018-12-11 at 9 57 29 am" src="https://user-images.githubusercontent.com/38065/49819955-7ef1d880-fd2b-11e8-8460-75d1dec137c6.png">
<img width="36" alt="screen shot 2018-12-11 at 9 57 36 am" src="https://user-images.githubusercontent.com/38065/49819956-7ef1d880-fd2b-11e8-8857-e11f657b1ef3.png">

**Comment by pcanella** [comment]
Are there currently SVGs for this that exist somewhere?

**Comment by pcanella** [comment]
Fixed via #558
