### ISSUE TITLE
Website: switch to CSS Grid and Flexbox based layout

### ISSUE THREAD

**Issue by ianmcburnie** [eBay/skin#485]
I would like to ditch the current CSS and JS implementation of our website layout in order to use more modern layout techniques. We can have simple fallbacks for IE11 using the old grid syntax.

Let's also try and avoid JS for layout, and keep it pure CSS.

**Comment by seangates** [comment]
@ianmcburnie Is this closed now given your recent site update?

**Comment by ianmcburnie** [comment]
Fixed in #821
