### ISSUE TITLE
Website: "checked" icon missing in custom checkbox menu items (DS6)

### ISSUE THREAD

**Issue by ianmcburnie** [eBay/skin#486]
DS4:

![screen shot 2018-12-13 at 1 49 53 pm](https://user-images.githubusercontent.com/38065/49969737-23b41780-fede-11e8-8007-1dfcf35b8a30.png)

DS6:

![screen shot 2018-12-13 at 1 50 04 pm](https://user-images.githubusercontent.com/38065/49969749-30d10680-fede-11e8-9e59-60b5e5bf53d5.png)

After a quick look it's probably because DS6 example is using `icon-confirmation` which doesn't exist in DS6:

```html
<svg aria-hidden="true" class="menu__status" focusable="false" height="8" width="8">
  <use xlink:href="#icon-confirmation"></use>
</svg>
```

Related issue #475

**Comment by pcanella** [comment]
fixed in #558
