### ISSUE TITLE
Build: remove "skin-large" adapter

### ISSUE THREAD

**Issue by ianmcburnie** [eBay/skin#488]
Given that the delta of additional styles brought in for large screens is so minuscule in DS4 (only global and card modules bring in "large" styles) and non-existent for DS6, maybe we should retire the concept of the skin-large adapter/conditional, and just always pull in the large styles by default?

Doing this will simplify the build, the docs and the cdn.

On the other hand it might create confusion around whether we advocate an adaptive or responsive approach. To me it seems like a hybrid approach might be best. Being responsive in terms of layout by using media-queries, but perhaps being adaptive for other situations (like touch or non-touch). Or in the case of when a component is *radically different* based on screen size (an image gallery, carousel or calendar might be good examples of this).

**Comment by seangates** [comment]
We need to have a hybrid approach. There is no silver bullet with responsive, and adaptive is sometimes overkill.

**Comment by ianmcburnie** [comment]
Changes merged to 7.0.0 branch. Closing.
