### ISSUE TITLE
Can't install project locally

### ISSUE THREAD

**Issue by darkwebdev** [eBay/skin#5]
I've done `bundle install` and got this error
![image](https://user-images.githubusercontent.com/2737310/29121304-eb5ec4da-7d05-11e7-8dd6-ec4281f852d2.png)

and before that it says:
`Gem::Installer::ExtensionBuildError: ERROR: Failed to build gem native extension.`

**Comment by darkwebdev** [comment]
ok, I've solved it with `bundle config build.nokogiri --use-system-libraries` and then `bundle install` again

**Comment by ianmcburnie** [comment]
This reminds me that I need to update the CONTRIBUTING page to include install instructions for bundler:

https://help.github.com/articles/setting-up-your-github-pages-site-locally-with-jekyll/
