### ISSUE TITLE
New Module: Section-Title (DS6.5)

### ISSUE THREAD

**Issue by ianmcburnie** [eBay/skin#524]
Module has 3 subtypes: arrow, info and overflow:

![screen shot 2019-01-22 at 12 22 01 pm](https://user-images.githubusercontent.com/38065/51563207-9222b880-1e40-11e9-84dd-cbdf7fd6fe67.png)

<img width="974" alt="Screen Shot 2019-09-16 at 5 49 01 PM" src="https://user-images.githubusercontent.com/38065/65002801-509cbd00-d8aa-11e9-91ef-4e2f589b21d6.png">

See design playbook for full specs

**Comment by msendlakowski** [comment]
Consider this for the 9.2.0 release since tabs were pushed out.

**Comment by ianmcburnie** [comment]
Title can have mix of arrow/info and overflow:

<img width="1333" alt="Screen Shot 2019-09-16 at 1 03 09 PM" src="https://user-images.githubusercontent.com/38065/64990978-ca6e7f80-d885-11e9-93be-562338e2c6a7.png">

**Comment by ianmcburnie** [comment]
I wonder if we need to build an `overflow-menu-button` as part of this task?

**Comment by ianmcburnie** [comment]
So, I've been thinking we can split this into two Skin modules: `heading-strip` and `heading-card`.

Both modules would be *layout* modules. Similar to the field module, which is used for laying out form fields in common configurations, these modules would layout the pieces of a heading (text, icon and overflow menu). Flexbox should make it a cinch.

```html
Default

<div class="heading-strip">
  <span class="heading-strip__title">
    <h2>Marketing Type Content Title</h2>
  </span>
</div>

Subtitle

<div class="heading-strip">
  <span class="heading-strip__title">
    <h2>Marketing Type Content Title</h2>
    <span class="heading-strip__subtitle">Recommended for You</span>
  </span>
</div>

Arrow/CTA (background svg)

<div class="heading-strip">
  <span class="heading-strip__title">
    <h2><a href="http://www.ebay.com">Marketing Type Content Title</a></h2>
  </span>
  <span class="heading-strip__cta"></span>
</div>

Arrow/CTA (foreground svg)

<div class="heading-strip">
  <span class="heading-strip__title">
    <h2><a href="http://www.ebay.com">Marketing Type Content Title</a></h2>
  </span>
  <svg class="heading-strip__cta">
    ..
  </svg>
</div>

Info

<div class="heading-strip">
  <span class="heading-strip__title">
    <h2>Marketing Type Content Title</h2>
  </span>
  <span class="heading-strip__info">
    <div class="infotip">
      ..
    </div>
  </span>
</div>

Overflow

<div class="heading-strip">
  <span class="heading-strip__title">
    <h2>Marketing Type Content Title</h2>
  </span>
  <span class="heading-strip__overflow">
    <span class="overflow-menu-button">
      ..
    <span>
  </span>
</div>
```

**Comment by ianmcburnie** [comment]
We are going to rename this `section-title`, in line with latest playbook update.

**Comment by ianmcburnie** [comment]
Will go out in v9.4.0.
