### ISSUE TITLE
Switch: update to latest color

### ISSUE THREAD

**Issue by ianmcburnie** [eBay/skin#532]
Apparently, our DS6 color is out of sync with the playbook.

![screen shot 2019-01-28 at 11 43 48 am](https://user-images.githubusercontent.com/38065/51861840-161dea00-22f2-11e9-965d-155c55ab93f1.png)

**Comment by ianmcburnie** [comment]
The only discrepancy in color I see is the disabled selected state. In skin (below) it's blue, in the playbook (above) it's grey.

<img width="59" alt="screen shot 2019-02-28 at 6 00 09 pm" src="https://user-images.githubusercontent.com/38065/53611284-d5c8ba80-3b82-11e9-8251-349031bcc23b.png">

**Comment by ianmcburnie** [comment]
Personally, I'm not sure we should change this to grey, or it's going to be almost indistinguishable from those other 2 states. Will reach out to designers.

**Comment by seangates** [comment]
Is the circle even the right size?

**Comment by ianmcburnie** [comment]
@seangates Unless it's completely clear what changes need to be made here (it's not to me, at first glance) we can just put this back on the backlog. Switch will be reviewed as part of DS6.5 a few sprints from now.
