### ISSUE TITLE
Icon: css cascade order issue for foreground icons when using `@ebay/skin/icon`

### ISSUE THREAD

**Issue by ianmcburnie** [eBay/skin#540]
Here is the current browser.json for `@ebay/skin/icon`:

```json
{
    "dependencies": [
        "@ebay/skin/icon/background",
        "@ebay/skin/icon/foreground",
        {
            "if-not-flag": "skin-ds6",
            "dependencies": [
                "@ebay/skin/iconfont"
            ]
        }
    ]
}
```

NOTE: In 7.0.0 we are removing iconfont.

Here is `@ebay/skin/icon/background`:

```json
{
    "dependencies": [
        {
            "path": "../dist/icon/background/ds4/background.css",
            "if-not-flag": "skin-ds6"
        },
        {
            "path": "../dist/icon/background/ds6/background.css",
            "if-flag": "skin-ds6"
        },
        "@ebay/skin/icon/common"
    ]
}
```

Here is `@ebay/skin/icon/foreground`:

```json
{
    "dependencies": [
        {
            "path": "../dist/icon/foreground/ds4/foreground.css",
            "if-not-flag": "skin-ds6"
        },
        {
            "path": "../dist/icon/foreground/ds6/foreground.css",
            "if-flag": "skin-ds6"
        },
        "@ebay/skin/icon/common"
    ]
}
```

The lasso resolution will go:

1. background.css
1. common.css
1. foreground.css
1. common.css (but lasso will dedupe this duplicate include)

Users of background icons will be fine, but specific foreground icons will have their width and height trumped due to base foreground.css rules coming *after* common.css.

This is therefore a regression for users of foreground icons.

**Comment by ianmcburnie** [comment]
Going to work on a 6.3.5 patch for this issue. I may have to remove the concept of "common" and just keep background and foreground completely separate.

**Comment by seangates** [comment]
You could still keep the common stuff, but have it be part of the LESS import, and not part of the Lasso bundling.

**Comment by ianmcburnie** [comment]
Shame Lasso doesn't have a "don't deduce this module" ability...or does it. That would be a quick and dirty fix for this, until I could refactor properly in 7.0.0. @DylanPiercey ?

Assuming not, I'm going to do this as a two part fix:

1. "just get it working fix", backwards compatible with minimum refactoring and moving of files
1. "proper fix", breaking change with refactoring and moving some files around
