### ISSUE TITLE
Inline alignment of form elements is off

### ISSUE THREAD

**Issue by seangates** [eBay/skin#546]
During updates for the `btn__cell` in the #543, we found the alignment of the inline elements is broken.

https://github.com/eBay/skin/pull/543#issuecomment-459900062

![image 21](https://user-images.githubusercontent.com/105656/52231972-7e337980-2878-11e9-9155-dbdd2879984c.png)

**Comment by ianmcburnie** [comment]
Done in 7.0.0. Closing.
