### ISSUE TITLE
Combobox: same line alignment issue with other controls

### ISSUE THREAD

**Issue by ianmcburnie** [eBay/skin#554]
From DS6 test page:

![screen shot 2019-02-08 at 2 08 16 pm](https://user-images.githubusercontent.com/38065/52508904-0b453e00-2bab-11e9-90ec-617f13f89d0b.png)

See that the combobox bleeds into the neighboring listbox control.

This issue has been present since v6 (and likely before).

DS4 has same issue:

![screen shot 2019-02-08 at 2 10 21 pm](https://user-images.githubusercontent.com/38065/52508996-57907e00-2bab-11e9-9b24-a07081e1c933.png)

**Comment by seangates** [comment]
This will be fixed with #550.

**Comment by ianmcburnie** [comment]
@seangates This seemed to get worse. Were any last second commits added? This is 7.0.0 branch:

![screen shot 2019-02-13 at 1 23 35 pm](https://user-images.githubusercontent.com/38065/52744957-cfd3b680-2f92-11e9-91fa-c560ae360431.png)
![screen shot 2019-02-13 at 1 23 51 pm](https://user-images.githubusercontent.com/38065/52744958-cfd3b680-2f92-11e9-89a9-1448f27c3332.png)

**Comment by ianmcburnie** [comment]
@seangates My local env must have been out of sync or something, because now I run this locally and both issues are gone! (I blew away my node_modules and rebuilt). If you verify too, we can close :-)

**Comment by seangates** [comment]
Whew! That makes me feel better. I was sure I squashed all these issues.

**Comment by seangates** [comment]
Verifying ...

**Comment by seangates** [comment]
We're good! Closing.
