### ISSUE TITLE
Notice: change "priority" to "attention"

### ISSUE THREAD

**Issue by ianmcburnie** [eBay/skin#559]
The playbook is using "attention" now rather than "alert". I never liked "alert", hence why I used "priority" instead on the dev side. I think "attention" works well, so let's change. I'll keep an alias in for the old term.

**Comment by pcanella** [comment]
I think we can close this now, right?

**Comment by ianmcburnie** [comment]
No, I need to go and update any references to priority:

https://github.com/eBay/skin/blob/7.0.0/docs/_includes/common/notice.html#L21

**Comment by ianmcburnie** [comment]
Done in 7.0.0
