### ISSUE TITLE
Dialog: right panel slide transition is broken in Safari

### ISSUE THREAD

**Issue by ianmcburnie** [eBay/skin#571]
Not sure if this issue is specific to the website, but it requires further investigation.

When clicking the "Right Panel" button, the dialog slides in a little too far and then snaps back into the correct place at edge of screen.

**Comment by seangates** [comment]
@ianmcburnie I believe this is no longer an issue.

**Comment by ianmcburnie** [comment]
It's still reproducible for me when clicking the second button:

![Screen Shot 2019-09-19 at 10 40 56 AM](https://user-images.githubusercontent.com/38065/65267521-08f47c00-daca-11e9-934e-97f11b8b7dbb.png)

**Comment by ianmcburnie** [comment]
Seems to have fixed itself (or was fixed, like Sean said). I see an odd little glitch occasionally but nothing as bad as before. Closing.
