### ISSUE TITLE
Icon: add & fix background versions of attention, confirmation & information

### ISSUE THREAD

**Issue by ianmcburnie** [eBay/skin#577]
Seems like we missed the background versions of these icon classes:

* `.icon--information`
* `.icon--confirmation`
* `.icon--attention`

The base64 LESS variables are there, but don't seem to be rendering correctly, so might need re-encoding.

I stumbled across this when updating the page notice to use the new icons (#499):

![screen shot 2019-03-01 at 9 30 09 am](https://user-images.githubusercontent.com/38065/53655312-a9558280-3c04-11e9-9e7d-226d60e6d46b.png)

**Comment by pcanella** [comment]
Should be fixed 👍
