### ISSUE TITLE
Color: Update to DS6.v2.01

### ISSUE THREAD

**Issue by seangates** [eBay/skin#580]
The current colors in Skin are as follows:

![image](https://user-images.githubusercontent.com/105656/53747400-67c11380-3e60-11e9-9268-933b11ea9632.png)

But, the colors listed in the brand playbook are as follows:

![image](https://user-images.githubusercontent.com/105656/53747460-87f0d280-3e60-11e9-8fe9-29af72eac94d.png)

We are requesting design feedback as the colors in Skin were updated, but with the current discrepancy we need to know if the brand guidelines were updated and not communicated or updated in the design system.

**Note:** The "product colors" from the design system has a much more limited set of the grey colors, and yet again they differ from Skin:

![image](https://user-images.githubusercontent.com/105656/53747615-e5851f00-3e60-11e9-88c7-e63f29271df7.png)

**Comment by ianmcburnie** [comment]
These may have been updated as part of `DS6.v2.01` update.

**Comment by ianmcburnie** [comment]
Oh, they shuffled in a new shade :-( This is the problem with sequential naming system, as it could be a breaking change for anyone relying on the previous grayscale. Might not be able to put this into 7.1.0

**Comment by seangates** [comment]
Yeah, it's as if we updated simply at the wrong time, as the greys changed _right after_ I updated.

**Comment by ianmcburnie** [comment]
I'm checking in with design on this one to see if now is a good time to make this breaking change or wait til DS6.5.
