### ISSUE TITLE
Tabs: focus indicator should fully wrap fake-tab

### ISSUE THREAD

**Issue by ianmcburnie** [eBay/skin#583]
Looks okay in Safari, but In Chrome & Firefox the focus indicator is a bit off:

![screen shot 2019-03-05 at 10 58 01 am](https://user-images.githubusercontent.com/38065/53829729-a379dd00-3f35-11e9-84df-6e781572c24d.png)

**Comment by seangates** [comment]
@ianmcburnie I believe this is no longer an issue.

**Comment by ianmcburnie** [comment]
Still reproducible in production for me.

**Comment by seangates** [comment]
I meant, it was not reproducible for me with 9.2.0. Unless you're having a different experience with it.

**Comment by ianmcburnie** [comment]
In 9.2.0, see how the focus indicator sits above the tab underline. It's minor, so maybe we just close it, but inconistent with regular tab.

<img width="1218" alt="Screen Shot 2019-09-20 at 5 18 16 PM" src="https://user-images.githubusercontent.com/38065/65365011-c1094e00-dbca-11e9-8f80-d47472c9001f.png">

<img width="572" alt="Screen Shot 2019-09-20 at 5 19 47 PM" src="https://user-images.githubusercontent.com/38065/65365031-e1390d00-dbca-11e9-983d-71e07a849b32.png">

**Comment by seangates** [comment]
Here's what I see, it's a little closer.

![image](https://user-images.githubusercontent.com/105656/65439216-0c4a7900-dde4-11e9-9dc5-8cc64b2b319f.png)

I think we should close it as it's gonna takes some pretty significant hacks to get them to match.

**Comment by ianmcburnie** [comment]
Which browser is that?

**Comment by seangates** [comment]
Safari.

**Comment by ianmcburnie** [comment]
Ok, please see the description. Safari is not affected.

**Comment by seangates** [comment]
Chrome looks fine to me, Firefox appears to be the only outlier.

**Comment by ianmcburnie** [comment]
Weird. My screenshots are from Chrome. I'm going to go ahead and close this, given that it's DS4 only.
