### ISSUE TITLE
Badge: button badge clipped in IE11

### ISSUE THREAD

**Issue by seangates** [eBay/skin#587]
The icon button badge is clipped on IE11. The simple fix is to add a `overflow: visible` to the button.

### Before
![image](https://user-images.githubusercontent.com/105656/54411041-8373b780-46b3-11e9-8ff7-214edbfcd31c.png)

### After
![image](https://user-images.githubusercontent.com/105656/54411057-91c1d380-46b3-11e9-8b6f-36a48f69eeb5.png)

**Comment by ianmcburnie** [comment]
Closing as duplicate of #640.
