### ISSUE TITLE
Menu: check mark icon is cut off (IE)

### ISSUE THREAD

**Issue by sharma46bhawana** [eBay/skin#590]
Issue: The ebay-menu selected item's check mark is cut off in IE ( checked IE 11/ Browserstack) and appears lighter in other browsers (chrome/FF) when compared with the design playbook.

Version used: skin@7.0.4

How it looks in IE:
<img width="279" alt="Screen Shot 2019-03-15 at 4 13 37 PM" src="https://user-images.githubusercontent.com/6751429/54556498-34a97480-4976-11e9-9aa1-f87464121148.png">

Chrome:
<img width="235" alt="Screen Shot 2019-03-15 at 4 13 54 PM" src="https://user-images.githubusercontent.com/6751429/54556515-40953680-4976-11e9-8759-d44f9d62eabd.png">

Playbook:
<img width="462" alt="Screen Shot 2019-03-15 at 4 22 10 PM" src="https://user-images.githubusercontent.com/6751429/54556556-54d93380-4976-11e9-824b-724e9e39881f.png">

Possible fix: 
`.menu__status {background-size: contain; height: 6px;}`

**Comment by ianmcburnie** [comment]
Closing as wontfix according to browser policy.
