### ISSUE TITLE
Checkbox: cascading issue with svg checkbox icon size

### ISSUE THREAD

**Issue by melquan** [eBay/skin#592]
Depending on the bundling order of `checkbox.css` and `foreground.css` which is included as part of `ebay-icon`, the checkbox svg size may be too large due to the style in foreground.css taking precedence.

![image](https://user-images.githubusercontent.com/19419138/54646954-fc7d6100-4a5d-11e9-98cc-1616516c0e03.png)

We should add more specificity to `.checkbox__icon svg` so that it takes precedence regardless of the bundling order.

**Comment by ianmcburnie** [comment]
Hi @melquan . Thanks for reporting. Which version of skin is this?

**Comment by melquan** [comment]
This is SKIN v7.0.4.

**Comment by ianmcburnie** [comment]
@melquan Just to clarify, as I'm having trouble reproducing, which style in `foreground.css` is taking precedence?

**Comment by melquan** [comment]
It's `svg.icon--checkbox-checked` and `svg.icon--checkbox-unchecked`.

I think updating `.checkbox__icon svg` to `.checkbox__icon svg.icon--checkbox-checked, .checkbox__icon svg.icon--checkbox-unchecked` in checkbox.css should do it.  I tried it locally and that seemed to fix the problem for me.

**Comment by ianmcburnie** [comment]
Aha, thanks! I believe the classes `icon icon--checkbox-checked` and `icon icon--checkbox-unchecked` are redundant when using foreground SVG for checkbox, as `.checkbox__checked` and `checkbox__unchecked` should be fine for the default icons. Maybe an oversight in our Skin documentation. I will investigate further. If so we can have those removed from the docs and patched in CoreUI too.

**Comment by ianmcburnie** [comment]
This will be a fix in two places:

1. Update documentation on Skin website to remove `icon icon--checkbox-checked`
1. Add `no-skin-classes` boolean to the `<ebay-icon>` tag in `<ebay-checkbox>` (this will remove `icon icon--checkbox-checked` from the rendered output)

**Comment by seangates** [comment]
Merged with #594 and published with eBayUI-Core [2.0.7](https://github.com/eBay/ebayui-core/pull/597). Closing.
