### ISSUE TITLE
Infotip/Tooltip/Tourtip: Arrow alignment in old LESS has incorrect calc()

### ISSUE THREAD

**Issue by seangates** [eBay/skin#596]
When a project has an old less parser the `calc()` is parsed as a less function rather than as being left alone.

![image (26)](https://user-images.githubusercontent.com/105656/55028254-841a2100-4fc4-11e9-91ab-f8903ad74683.png)

**Comment by ianmcburnie** [comment]
How old of a LESS version are we talking about?

**Comment by msendlakowski** [comment]
Spoke to the user who originated this issue and they are on less v2.7.3 which is 2 years old.  They've overridden it locally, so I'm going to close this.
