### ISSUE TITLE
Link: 'fake-link' should be styled like a traditional link

### ISSUE THREAD

**Issue by melquan** [eBay/skin#597]
Currently the fake link looks like this:

![image](https://user-images.githubusercontent.com/19419138/55202454-b8d4d680-5184-11e9-84be-99cc1c44644c.png)

Ideally it should be styled like a traditional one too, so:

1. It shouldn't have an underline by default.
2. It should have an underline only on hover.
3. On hover, the cursor should be a pointer.

**Comment by ianmcburnie** [comment]
Hmm, for 1 and 2, links do have an underline by default and on hover (`text-decoration: underline`). 

For 3 (and this gets confusing), the pointer cursor is a visual affordance that something *behaves* like a link. This is a button tag, so we shouldn't be giving an affordance that it behaves like a link (i.e. a url change).

Where it would get really confusing is if we have a fake link that updates the url via JavaScript. Then I guess we could give it a pointer...but really then a link tag should be used.

Happy to chat incase I'm missing something here!

**Comment by seangates** [comment]
So, for the hover interaction, it looks like we're not presently following what's set forth in the DS6 pattern.

Regarding the pointer, it looks like a default button pointer is still what's to be used (not the hand):

![image](https://user-images.githubusercontent.com/105656/55246607-caf55a00-5202-11e9-88ea-ce593055fa2d.png)

**Comment by ianmcburnie** [comment]
@seangates  Regardless of what's in the design system, anchor tags always show a hand. Button tags always show default. We can file a bug on them if necessary. However, it's hard to tell from that screenshot whether that's a fake link (button tag) or a real link (anchor tag).

@melquan Thanks for clarifying. Sounds like we need an additional modifier for the `fake-link` to turn it into an "action link". Or, like you say, we could just make that the default behaviour for fake links. I'm a little bit wary of doing that incase these fake links are ever included in blocks of paragraph text (in which case they would require an underline). I'll mull it over...

**Comment by seangates** [comment]
I wasn't advocating for a hand, btw. 😉 Just commenting that an "action link" (their description for it) doesn't use a hand.

**Comment by ianmcburnie** [comment]
Added modifier in 7.3.2. Closing.
