### ISSUE TITLE
New Pattern: Expansion (Show more / Show Less)

### ISSUE THREAD

**Issue by szhou1** [eBay/skin#607]
An expansion panel is a lightweight container that may either stand alone or be connected to a larger surface. Content will expand to a larger section, or collapse to original size, by tapping on the expansion controls. Expansion and reduction controls are always paired.

Related module: https://github.com/eBay/skin/issues/610

![image](https://user-images.githubusercontent.com/3683406/56624043-deba9300-65eb-11e9-996a-924ce1dfa8cf.png)

**Comment by seangates** [comment]
@szhou1 Removed the internal link.

**Comment by ianmcburnie** [comment]
From an implementation point of view, and this may have more of an impact on the CoreUI side of things, I think we should avoid an approach that simply sets the CSS height on a DIV. This causes issues for keyboard and screenreader users. In the [YouTube video description](https://www.youtube.com/watch?v=5ljluGA4dQU), for example, I can access all content without clicking the show more button. Sadly, we are also seeing this dev pattern appear on eBay.

**Comment by ianmcburnie** [comment]
Closing, as this can be achieved with a fluid expand button.
