### ISSUE TITLE
Label: grey out on disabled state

### ISSUE THREAD

**Issue by abiyasa** [eBay/skin#608]
Currently, it seems we don't grey out the label for the disabled controls:

![disabled-fields](https://user-images.githubusercontent.com/1072047/56918129-8426a880-6abd-11e9-88b6-148164e87946.png)

Should we gray it out?

We do grey out the disabled floating-label:

![disabled-floating-label](https://user-images.githubusercontent.com/1072047/56918189-a4566780-6abd-11e9-862d-685929eaf10f.png)

Also on Playbook, the labels are grey out on disabled state:

![playbook-on-form-labels](https://user-images.githubusercontent.com/1072047/56918216-b932fb00-6abd-11e9-9da7-fa957a29a12b.png)

**Comment by ianmcburnie** [comment]
The labels are completely independent of the control in skin, so we can't base the style of the label on the state of the control. Maybe adding a new modifier to the field module would help:

```less
.field__label--disabled {
  color: #ccc;
}
```

**Comment by msendlakowski** [comment]
Address with the DS6.5 updates for forms.

**Comment by ianmcburnie** [comment]
Let's see if this is sufficient:

```css
.field__label--disabled {
  color: #c7c7c7;
}
```

Although that does tie users into using the field module. Perhaps this inside of the typography would also help:

```css
.disabled-text {
  color: #c7c7c7;
}

**Comment by ianmcburnie** [comment]
Done in 9.4.0
