### ISSUE TITLE
New Pattern: Details

### ISSUE THREAD

**Issue by szhou1** [eBay/skin#610]
A region of content that can be expanded and collapsed, forcing any adjacent content to be pushed down  the page.
Details are often used to declutter secondary content (e.g. 'Show more'), navigation links or form options.
HTML provides a details tag by default, however it is not supported in Internet Explorer or Edge browsers.
![image](https://user-images.githubusercontent.com/3683406/56935527-600b9d00-6aa6-11e9-965c-0f3409fdf206.png)

**Comment by ianmcburnie** [comment]
Done. Closing. This will go out in Skin v7.3.0.
