### ISSUE TITLE
Dropdown pattern updates

### ISSUE THREAD

**Issue by JeffNixonCreative** [eBay/skin#62]
Dropdown was just published to DSL. 
Attached is a PDF for development.

[Dropdowns_PUB_JN_180216.pdf](https://github.com/eBay/skin/files/1742531/Dropdowns_PUB_JN_180216.pdf)

**Comment by ianmcburnie** [comment]
Seems like we just need to update the colors slightly and add a borderless option to what we currently have. We can probably slot this work in soon.

**Comment by seangates** [comment]
It looks like the SVG for this new pattern was updated, too.

Specifically, the dropdown arrow and the check mark are "heavier" than they were before. Therefore, we need a to get the new SVG paths and update them accordingly.

/cc @JeffNixonCreative

**Comment by seangates** [comment]
Closed via #78.

Tracking new SVG icons via #79.
