### ISSUE TITLE
Combobox: investigate options for adding a distinct expand/collapse button

### ISSUE THREAD

**Issue by ianmcburnie** [eBay/skin#626]
Currently our combobox expand occurs on focus of the textbox. Clicking the chevron icon with mouse or touch simply sets focus on the textbox (which in turn causes the combobox to expand).

<img width="239" alt="Screen Shot 2019-05-17 at 12 13 41 PM" src="https://user-images.githubusercontent.com/38065/57951137-1ab8df00-789e-11e9-8ab9-e8b4e9d1883f.png">

<img width="240" alt="Screen Shot 2019-05-17 at 12 20 17 PM" src="https://user-images.githubusercontent.com/38065/57951169-26a4a100-789e-11e9-8160-603867b614b0.png">

We have a few options regarding adding a separate expand/collapse button element (as defined in MIND patterns and WCAG):

1. Don't add one. Keep the behaviour as is (a button element is not strictly required by WCAG, it is optional).
1. Make the current chevron icon an actual button element (possible discoverability issue though)
1. Create a `no-icon` modifier for the combobox, so that apps can define their own expand/collapse button and behaviour. Or simply just leave out the icon span element from the markup should do it?
1. Create a separate version of combobox which has no icon and a distinct separate button immediately adjacent to the combobox (so there would be white space between the textbox and button).

Option 3 feels like the best to me.

**Comment by ianmcburnie** [comment]
Going to close this until we get further direction from design and more use cases.

Having a separate UI element (a button) to expand/collapse feels like an unnecessary step. Maybe only necessary in some edge cases (as yet unidentified). My feeling is that we should always show combobox dropdown on focus (or on input) for added discoverability & affordance. If we have good suggestions, then let's put them right at the fingertips of our users rather than make them work for it. That's what I'm going to go forward with in MIND patterns.

**Comment by melquan** [comment]
I think this came up from a request from me.  Just wanted to clarify that it not a request to replace the functionality that opens the dropdown on focus, but rather an additional affordance to open/close the dropdown.

We ended up going with option 3 and creating our own wrapper component that combined an ebay-combobox & ebay-button to support this functionality, but we were hoping that this could be promoted into the ebayUI component.

**Comment by ianmcburnie** [comment]
Thanks @melquan Combobox is currently being reviewed as part of 6.5. I'll be sure to raise the question of whether we need a separate button.

**Comment by melquan** [comment]
I also wanted to add that opening the dropdown from this new affordance would open the full list rather than the filtered list by what is in the combobox textbox.

At least that is the requirement we had.

**Comment by ianmcburnie** [comment]
Yeah, that behaviour would have to be reviewed/legitimized as part of the whole system. Thanks for the reminder though. I'm glad that you were able to create your own wrapper for now.
