### ISSUE TITLE
Select & combobox: border colors are lighter than that of textbox / radio button

### ISSUE THREAD

**Issue by melquan** [eBay/skin#627]
Currently the border color for select & combobox is lighter than that of textbox / radio button.

![image](https://user-images.githubusercontent.com/19419138/58111688-cf0c7b00-7ba6-11e9-9584-9600e63498e0.png)

It makes it look somewhat disabled and inconsistent with other elements when they are displayed side-by-side.

Can we get it matched up to the same color?

**Comment by ianmcburnie** [comment]
Thanks for finding & reporting! We can probably sneak this into v7.3.0.

**Comment by ianmcburnie** [comment]
@seangates fixed this for 7.3.0 release. Closing.
