### ISSUE TITLE
Dropdown DS6 CSS is always included even when skin-ds6 is not set

### ISSUE THREAD

**Issue by ethanrubinson** [eBay/skin#63]
https://github.com/eBay/skin/blob/master/listbox.browser.json#L3

This causes the svg arrows to display outside the control: 
![image](https://user-images.githubusercontent.com/5170747/36504462-6de4875c-1705-11e8-9190-57a23ed06cdf.png)

**Comment by ethanrubinson** [comment]
#64

**Comment by ianmcburnie** [comment]
Thank you @ethanrubinson!!! v3.3.2 hot fix has been published.
