### ISSUE TITLE
Textbox: when icon is on the right the cursor blinks to the right of the icon (iOS)

### ISSUE THREAD

**Issue by hramakumar** [eBay/skin#638]
# Bug Report

## Description
the textbox with postfix icon -  
repro-
In IOS device
go to https://go/ebayui/test
click the textbox icon postfix
type a long text 
click done and get the focus out.
Then again click on the icon in textbox

in IOS you will see a blinking cursor on the right of the icon
in Android- you will not see the blinking cursor

## Screenshots
![textbox_cursor](https://user-images.githubusercontent.com/13157115/49769178-0d1a8000-fc94-11e8-825b-f7b83fc6adac.png)

**Comment by ianmcburnie** [comment]
Closing due to priority 4. We can always reopen it if we get the time to look through our 'wontfix' issues.
