### ISSUE TITLE
Dialog: close button size in skin is 16px, while its 21px in ebay-dialog

### ISSUE THREAD

**Issue by bhoomisatasiya** [eBay/skin#642]
# Bug Report

## Description

Close  'X' button size in skin is 16px, while its 21px in ebay-dialog
## Screenshots

<img width="1680" alt="Screen Shot 2019-04-10 at 3 14 37 PM" src="https://user-images.githubusercontent.com/11545472/55917403-0baa8700-5ba4-11e9-9fbb-3d3b86aa51e4.png">
<img width="1680" alt="Screen Shot 2019-04-10 at 3 14 24 PM" src="https://user-images.githubusercontent.com/11545472/55917404-0c431d80-5ba4-11e9-92e0-be5e77a8f5bb.png">

**Comment by ianmcburnie** [comment]
Released in 7.3.1. Closing.
