### ISSUE TITLE
Automate CDN upload step after publishing to NPM

### ISSUE THREAD

**Issue by ianmcburnie** [eBay/skin#644]
Instead of relying on our collectively feeble human brains (which, let's face it, aren't getting any younger) to remember to manually do the CDN upload, let's pass this torch to the machines. Let them take care of it. Of course we will first of all have to program the machines how and when to do this. They aren't that clever. Yet.

**Comment by ianmcburnie** [comment]
We can try and automate the content of this section of the docs too (i.e. the version number in the file path):

<img width="985" alt="Screen Shot 2019-06-10 at 9 28 27 AM" src="https://user-images.githubusercontent.com/38065/59210307-2b3d3c00-8b62-11e9-97eb-2f7cfc6bff2c.png">

**Comment by msendlakowski** [comment]
Progress was made on this, but its not fully automated.

- The docs file (in the comment) is dynamically updated now
- There is an updated script to generate the CDN bundles, but it doesn't upload yet.
- We added a step in the CONTRIBUTING.md file to remember to upload it to CDN

**Comment by ianmcburnie** [comment]
Picking this up again. Step 1 is to create a service account. In progress...

**Comment by ianmcburnie** [comment]
Repeating what Damo said on another thread regarding the API:

"This is way too much of work to upload assets. There must at least be a module exposed in multiple languages that takes care of all this."

I think what we currently have in place is fine, easy to use, and we get very little added benefit from integrating with the "API". Closing. We can maybe re-open if the API features improve.
