### ISSUE TITLE
Notice:  close icon expands when hovered/clicked (DS4)

### ISSUE THREAD

**Issue by hramakumar** [eBay/skin#645]
Skin Version: 7.3.0-0
When I click on the close button. The close icon expands before closing the notice. 
Reproducible in marketplace

**Comment by ianmcburnie** [comment]
I can reproduce on current live ds4 page too. Seems like a bug that crept in sometime after 6.3.0, going by the [archive](https://ebay.github.io/skin/archive/).

**Comment by hramakumar** [comment]
in previous versions, the close icon slightly moved on mouseover which didn't seem very odd.
Now the icon expands in size with 7.3.0 version.

**Comment by hramakumar** [comment]
anyways I dont see it as blocker

**Comment by ianmcburnie** [comment]
Patched for 7.3.2
