### ISSUE TITLE
Fake Menu: link colours are broken (DS4)

### ISSUE THREAD

**Issue by ianmcburnie** [eBay/skin#648]
Looks like a regression crept in at some point for DS4:

<img width="245" alt="Screen Shot 2019-06-11 at 9 52 40 AM" src="https://user-images.githubusercontent.com/38065/59291058-dd423a00-8c2e-11e9-9920-89c5bd25bdd8.png">

**Comment by ianmcburnie** [comment]
Looks like the culprit is here:

https://github.com/eBay/skin/blob/master/src/less/dropdown/base/dropdown.less#L164

**Comment by seangates** [comment]
Actually here 😉 : https://github.com/eBay/skin/blob/288afc373db2caec6b98ce582702df28e7a55661/src/less/dropdown/ds4/dropdown.less#L16

**Comment by ianmcburnie** [comment]
Patched for 7.3.2
