### ISSUE TITLE
Field: add field margin-top 0 (proposal)

### ISSUE THREAD

**Issue by seangates** [eBay/skin#653]
(from a discussion with @melquan)

When the field is a `<div>` Skin has a the following:
```
margin: 16px 0;
```
This causes the first item to have an additional `16px` on the top margin, which needs to be negated, and even the docs show an inline style of `margin-top: 0` to help ensure the first field aligns correctly.

**Proposal**

Add the following:
```
div.field:first-child {
  margin-top: 0;
}
```

**Comment by ianmcburnie** [comment]
The margin top is a "sensible default" to ensure there is always 16px of space above the field. If we set the first one to zero we could have a situation where the first field is squashed up against another element.

I've been trying to go with the flow of CSS and leverage margin-collapse across Skin as much as possible (but it's not totally conistent everywhere I must admit).

**Comment by ianmcburnie** [comment]
Let's review this again when we get to layouts and spacing in 6.5. Closing for now.
