### ISSUE TITLE
DS4 Lisbox- when disabled- hover over changes color

### ISSUE THREAD

**Issue by hramakumar** [eBay/skin#657]
Ebay UI core 2.6.0-1 and skin 7.3.1

DS4 - disabled list box - when we hover over it it changes color from grey to white.
reproducible inmarketplace

**Comment by seangates** [comment]
@hramakumar Can you please provide screen shots with these issues? That helps a lot because we can sometimes triage just by looking at the expected v. actual behavior or style.

**Comment by hramakumar** [comment]
before hover
![image](https://user-images.githubusercontent.com/13157115/59472099-34443c80-8df2-11e9-93bb-bd0678fbfe55.png)
after hover
![image](https://user-images.githubusercontent.com/13157115/59472113-41f9c200-8df2-11e9-97be-c9d1e106a546.png)

**Comment by hramakumar** [comment]
the expected behaviour - hovering over a disabled component should not change the grey color

**Comment by seangates** [comment]
Thanks, those pictures help (albeit, they're HUGE 😉 ).

**Comment by ianmcburnie** [comment]
Patched for 7.3.2
