### ISSUE TITLE
Button: DS4 disabled state allows hover color

### ISSUE THREAD

**Issue by hramakumar** [eBay/skin#658]
# Bug Report

## Description
The disabled buttons have a blue background like a primary disabled button, instead of grey background and the label is also not visible clearly

## Screenshots
![image](https://user-images.githubusercontent.com/105656/59472540-05cb5f00-8dfc-11e9-8408-a7346c75a590.png)

**Comment by ianmcburnie** [comment]
Patched for 7.3.2.
