### ISSUE TITLE
Text Links: New DS6 Pattern

### ISSUE THREAD

**Issue by JeffNixonCreative** [eBay/skin#66]
Attached is a PDF of the design file provided for the DS6 Text Links patterns that is now live on DSL.

[Text Links](https://dsl.ebay.com/ds6/textlinks)

[ds6_link_v1.01.pdf](https://github.com/eBay/skin/files/1749979/ds6_link_v1.01.pdf)

**Comment by ianmcburnie** [comment]
It seems that the only change here from what we currently have in our global styles, is that anchors inside of paragraphs are now the same color as the text, but with a blue underline.

![screen shot 2018-02-27 at 1 17 06 pm](https://user-images.githubusercontent.com/38065/36755266-8e72bcea-1bc0-11e8-9d4e-1d442492ecc6.png)

**Comment by seangates** [comment]
Oh, that's interesting. And not well supported across browsers without some kind of other markup. Ugh.

https://caniuse.com/#search=text-decoration-color

**Comment by ianmcburnie** [comment]
Will definitely not be adding markup. We have to decide whether it's okay to fall back to black underline in non-supported browsers.

**Comment by ianmcburnie** [comment]
Text decoration thickness can not be set in CSS, resulting in a rather wimpy looking underline:


<hr/>
<img width="877" alt="screen shot 2018-02-27 at 2 44 09 pm" src="https://user-images.githubusercontent.com/38065/36759607-cedbb30c-1bcc-11e8-9897-0f73f836a25e.png">

<hr/>

It technically passes accessibility, but is a little too subtle I think.

**Comment by seangates** [comment]
Super-quick experiment: https://codepen.io/seangates/pen/ZrVORe

**Comment by ianmcburnie** [comment]
Nope, sorry, I am not going to use the border property for this (I did already try it though, ha ha) ;-)

**Comment by seangates** [comment]
What's the downside? Are there any accessibility implications?

**Comment by ianmcburnie** [comment]
Collisions with other containing borders perhaps. And we can't use other text-decoration properties, such as `text-decoration-skip` and `text-decoration-skip-ink`... if we wanted to.

**Comment by ianmcburnie** [comment]
I guess I'm not *completely* ruling it out, but feels like the wrong thing to do.

**Comment by seangates** [comment]
Again, back to the caniuse.com link: those `text-decoration` styling rules are just not available in IE.

**Comment by seangates** [comment]
I mean `text-decoration-skip` would be awesome, but ... [reality](https://developer.mozilla.org/en-US/docs/Web/CSS/text-decoration-skip)

![image](https://user-images.githubusercontent.com/105656/36760998-4c627aec-1bda-11e8-9783-e0d9573bcfa4.png)

**Comment by ianmcburnie** [comment]
Yep, skip and skip-ink are still experimental. Here's an interesting article on the subject:

https://medium.design/crafting-link-underlines-on-medium-7c03a9274f9

I vote we keep things simple. The article reminded me of box-shadow though. I remember using it before for this exact same thing, but think I might have ran into some issue. Feel free to investigate.

**Comment by seangates** [comment]
Investigated (ad nauseam on Slack), and I think the best option is to use `text-decoration-color` for those browsers that support it (using [feature queries](https://caniuse.com/#feat=css-featurequeries)), and revert to something else for browsers that don't support it.

Any final thoughts before work on this can begin?

**Comment by ianmcburnie** [comment]
We can also maybe add a couple of utility classes that remove the default underline and have appropriate color and states , e.g. `navigation-link`, `action-link`

**Comment by seangates** [comment]
I like the idea of utility classes. This gives developers lots of flexibility, and even gives design some flexibility.
