### ISSUE TITLE
Textbox: multiline - The first line is moved up towards the top border

### ISSUE THREAD

**Issue by hramakumar** [eBay/skin#665]
ebayui Core 2.6.0-2 and skin 7.3.2

Expected

![image](https://user-images.githubusercontent.com/13157115/59642492-07599780-911a-11e9-8df1-ba9ad42f5208.png)

actual
![image](https://user-images.githubusercontent.com/13157115/59642079-83eb7680-9118-11e9-8287-5b440ca6e11e.png)

**Comment by ianmcburnie** [comment]
Fix published in v7.3.3
