### ISSUE TITLE
Button: separate pill styles into their own module

### ISSUE THREAD

**Issue by ianmcburnie** [eBay/skin#671]
As part of DS6.5, the pill is going to be refined for a more specific set of use cases for filtering only. The concepts of primary and secondary will no longer apply, and there will be other fundamental differences, therefore I think it's a good time to do this separation.

For this task let's just separate the pill styles into their own module with no refactoring, mixins or API changes. Yes, this means there will be a little bit of duplication of styles in the button module and pill module, but this change will just set us up nicely for v9.0.0.

**Comment by seangates** [comment]
We'll call this `filter-button`? (DS team wants to rid all references to "pill" from the system.)

**Comment by ianmcburnie** [comment]
Yeah, if that's the case. Might need a `filter-link` too. Going for more granularity in skin, so keeping button semantics and link semantics separate might make sense too (and then just leveraging mixins).

**Comment by seangates** [comment]
As in separate modules altogether?

**Comment by ianmcburnie** [comment]
@seangates This PR should not be doing any renaming though. This PR is just the separation of the current pill styles out into their own "pill" module.

**Comment by seangates** [comment]
Pre v8.0.0?
