### ISSUE TITLE
Notice: spacing issue

### ISSUE THREAD

**Issue by ianmcburnie** [eBay/skin#684]
Issue found by Sir Jeremy B. He requests, at our earliest convenience, that this spacing:

![eBay_Skin_—_for_DS6](https://user-images.githubusercontent.com/38065/61010420-fc65e180-a32a-11e9-906d-7412ef247c27.png)

Be more like this spacing:

![eBay_Skin_—_for_DS6 (1)](https://user-images.githubusercontent.com/38065/61010432-0851a380-a32b-11e9-9cd0-96eabd935450.png)

**Comment by ianmcburnie** [comment]
@seangates Do you think we should do this as a patch or minor release?

**Comment by ianmcburnie** [comment]
This potentially might not even be an issue. The first example is using paragraph tags, the second example is using a br tag. Punting this back to 8.0.0 as it's non urgent.

**Comment by agliga** [comment]
One fix we could do is to force all paragraphs to have 0 margins and then force content to have 16px padding. This way the items will have the same styles, but each paragraph will not have spacing.

**Comment by ianmcburnie** [comment]
Are we doing notice this sprint??
