### ISSUE TITLE
Combobox, Menu: in IOS when combobox options have long text ..the option list font size is bigger than usual

### ISSUE THREAD

**Issue by hramakumar** [eBay/skin#687]
# Bug Report

## Description
when one of the options in option list has a long text the font size is bigger than expected.
Happens only in IOS

## Screenshots
![660536FE-B08C-4FE8-9E73-D5DC31E6001A](https://user-images.githubusercontent.com/13157115/58275932-061b9180-7d4b-11e9-8bee-f4af5deb9f31.jpeg)

**Comment by seangates** [comment]
Fixed in v7.4.2
