### ISSUE TITLE
Filter Menu Button: new module

### ISSUE THREAD

**Issue by ianmcburnie** [eBay/skin#701]
More info to come. This work will be done alongside the DS6.5 changes to button and pill.

It appears there are going to be two different version of this button.

Version 1. Full page reload. A button that opens a flyout. Flyout contains a fieldset of checkboxes and a submit/apply button. No reload happens until submit/apply button is activated.

Version 2. SPA. A button that opens a flyout. Flyout contains a menu of checkbox menuitems and a button (check all/clear all). Re-render happens immediately upon toggling any checkbox.

**Comment by seangates** [comment]
The filter button is done, but the filter-menu-button is not. Reopening.
