### ISSUE TITLE
Typography: updates for DS6.5

### ISSUE THREAD

**Issue by ianmcburnie** [eBay/skin#702]
No changes to the type ramp.  All changes are additive, so we can keep this sprint to a minor version release.

DS6.5 is introducing guidelines around titles.  We will add utility classes that allow developers to specify that a container is a title, and at what size, and we'll map those classes to the current font types.  Going forward this will allow us to easily update a "large title" from 32px to 34px, for example.

In addition "product titles" are being distinguished from "section titles".  Section titles should be bold.

### Large screen Title sizes mapped to skin classes
Giant = giant-text-1
Large = large-text-2
Medium = large-text-1
Small = medium-text

### Small screen Title sizes mapped to skin classes
Giant = large-text-2
Large = large-text-1
Medium = medium-text
Small = regular-text

### For discussion
* Do we add a section to the existing `typography` module using the following format:
`title-product-giant`?
* Do we use media queries to distinguish between small and large screens?  Or do we create `title-product-giant-dweb` or something to that effect?

**Comment by ianmcburnie** [comment]
It would probably be overkill to make a new "title" module, so yeah maybe just add the following to the typography module:

*  `giant-title`
* `large-title`
* `medium-title`
* `small-title`

Using media queries for these aliases probably does make sense, if design want to lock in these titles based on the screen size.

**Comment by msendlakowski** [comment]
OK.  Unless anyone has an issue, I will create:
- giant-product-title
- large-product-title
- medium-product-title
- small-product-title
- giant-section-title
- large-section-title
- medium-section-title
- small-section-title

I'll use the typography mixins and media queries to account for small and large screens.
