### ISSUE TITLE
Research and possibly fix menu item styles

### ISSUE THREAD

**Issue by seangates** [eBay/skin#71]
When working on creating the eBayUI component for the menu, we noted that the `role="menuitem"` was added to fake menu items, which doesn't adhere to proper accessibility roles.

When we removed this role (and removed the role attribute altogether) the styling broke and the items appeared unstyled in the menu.

This issue is created to track that, and make sure that the styles are still applied when no role is present, specifically in the case of a fake menu.

**Comment by ianmcburnie** [comment]
Did you add class '.fake-menu__item`?

**Comment by seangates** [comment]
Yes, it gets added. Hence my need to "research" what's going on. I have not dug in.

**Comment by ianmcburnie** [comment]
Probably missing a BEM class o using wrong tag somewhere along the line. Probably.

**Comment by ianmcburnie** [comment]
Any progress? Would like to do final release of 3.4.0 on Friday.

**Comment by seangates** [comment]
No progress. Let me look at it.

**Comment by seangates** [comment]
Not an issue.
