### ISSUE TITLE
Listbox / menu: border colors are lighter than that of textbox / radio button

### ISSUE THREAD

**Issue by melquan** [eBay/skin#733]
(copied from #627) 

Currently the border color for listbox & menu is lighter than that of textbox / radio button.

From https://ebay.github.io/skin/test/misc/ds6/alignment-controls-inline.html

![image](https://user-images.githubusercontent.com/19419138/62148453-98419800-b2ae-11e9-8156-7bae7fcfd414.png)

It makes it look somewhat disabled and inconsistent with other elements when they are displayed side-by-side.

Can we get it matched up to the same color?

**Comment by msendlakowski** [comment]
This will be fixed in v8.0.0
