### ISSUE TITLE
New Module: Page Titles

### ISSUE THREAD

**Issue by JeffNixonCreative** [eBay/skin#74]
This pattern is now live on DSL and can be found here:
https://dsl.ebay.com/ds6/page-titles

Here is a PDF for reference:
[PageTitles_180228_v1.pdf](https://github.com/eBay/skin/files/1772841/PageTitles_180228_v1.pdf)

**Comment by ianmcburnie** [comment]
I don't think there's anything we actually need to do here, in terms of skin. Seems like our typography will cover this. @seangates thoughts?

**Comment by seangates** [comment]
Well, we don't actually specify any H1-H6 styles. Would that be worthwhile in Skin for DS6?

For example, it's currently there in DS4:
https://github.com/eBay/skin/blob/master/src/less/global/ds4/global.less#L10-L44
https://github.com/eBay/skin/blob/master/src/less/global/ds4/global-large.less#L3-L37

Personally, I like the fact the H1-H6 were tied to a certain font-size and I didn't have to "think about it". I think it is at least worth a quick discussion.

**Comment by ianmcburnie** [comment]
I guess a page title would always be an H1 though?

Regarding the h1-h6, yeah we could set some sensible defaults on those in the global module (like we do in ds4) for margin and font-size. Although most of the time we do find that the font-sizes still get overridden by app teams.

**Comment by ianmcburnie** [comment]
Going to close this one, as it doesn't seem to be part of the new playbook. We can always reopen if necessary.
