### ISSUE TITLE
button small: size=small does not work

### ISSUE THREAD

**Issue by hramakumar** [eBay/skin#763]
Small button is of the size of any other regular button
https://www.loom.com/share/bb2f057276a24c28bec94cef0e96bd32

**Comment by msendlakowski** [comment]
Small, medium, and extra-large buttons are no longer supported as of skin 9, for DS4 and DS6.  We only have the default size (previously medium) and large.

Here are the requirements we followed.  Let me know if you want me to clean them up.  They changed a few times.
https://github.com/eBay/skin/issues/700
