### ISSUE TITLE
checkbox: box area is grey

### ISSUE THREAD

**Issue by hramakumar** [eBay/skin#764]
the check box is grey in color.
not sure if this is expected. so filing it as question. pls change it to bug if you think so
![image](https://user-images.githubusercontent.com/13157115/63129244-e40d6600-bf6b-11e9-8cd9-a2f69def591a.png)

**Comment by msendlakowski** [comment]
Looks like it was a merge error from master.  I'm looking into it, but I'm going to take a bit to make sure I didn't miss anything else.

**Comment by seangates** [comment]
Oh shoot. Let me know if you need any help, @msendlakowski.
