### ISSUE TITLE
Notice: alignment bug (edge case)

### ISSUE THREAD

**Issue by ianmcburnie** [eBay/skin#77]
One last thing for the 3.4.0 release is to fix alignment issue when a button is added.

<img width="373" alt="screen shot 2018-03-02 at 3 48 41 pm" src="https://user-images.githubusercontent.com/38065/36927273-604e0cca-1e31-11e8-8402-430c8877f669.png">

**Comment by ianmcburnie** [comment]
DS4 also has the same issue. We should quickly figure out whether a markup change is needed (i.e. a breaking change) or whether this can be solved with CSS alone with current markup (i.e a patch).

<img width="335" alt="screen shot 2018-03-03 at 9 48 22 pm" src="https://user-images.githubusercontent.com/38065/36942647-d35a496c-1f2c-11e8-8e59-30d42347609a.png">

**Comment by ianmcburnie** [comment]
Ideally this can be fixed with some tweaks to the current flex box approach, if not here is another possible approach, where we basically just ditch flex box and jam the icon into the beginning of the first paragraph.

```html
<div class="inline-notice inline-notice--confirmation">
    <p>
        <span class="inline-notice__status" aria-label="Confirmation" role="img"></span>
        Delivered on May 1, 2017 <button class="btn btn--primary">Button</button>
    </p>
</div>
```
<img width="298" alt="screen shot 2018-03-03 at 10 15 10 pm" src="https://user-images.githubusercontent.com/38065/36942796-5dd24fce-1f30-11e8-9ee9-1dadcd3ec0d5.png">



<img width="921" alt="screen shot 2018-03-03 at 10 10 11 pm" src="https://user-images.githubusercontent.com/38065/36942772-dcc24e84-1f2f-11e8-991e-1b384c498db0.png">

I think it looks a little weird having a button in an inline notice though (links look much better), especially in the double line example as shown below. So we prob need to verify this with design.

```html
<div class="inline-notice inline-notice--confirmation">
    <p>
        <span class="inline-notice__status" aria-label="Confirmation" role="img"></span>
        Delivered on May 1, 2017 <button class="btn btn--primary">Button</button>
    </p>
    <p>Tracking number: <a href="#">93878473859376898908657567</a></p>
</div>
```
<img width="388" alt="screen shot 2018-03-03 at 10 12 52 pm" src="https://user-images.githubusercontent.com/38065/36942782-1b32ad30-1f30-11e8-9e7d-297720aaf7d0.png">

**Comment by seangates** [comment]
Yeah, that multiline example looks as bad (to me) as the reported bug.

**Comment by sharma46bhawana** [comment]
The problem here is that for an inline notice with 2 or more paragraph tag the icon is aligned to the top, whereas in an inline notice with one paragraph + button (which has a line-height of 40px) because the icon is top we get the bug. The icon can be center-aligned easily with the use of flex 
`display: flex`
`justify-content: center`
`align-items: center`

 (that aligns it in the middle with 2 or more paragraph as well)

I agree it's not a pattern that will be used and if we do have a button in the same line it should have the look like a link

**Comment by sharma46bhawana** [comment]
@ianmcburnie The problem with adding a span inside the paragraph is that then inline-notice__content is no longer a black box for us, and then we will be governing the content in the core component.

**Comment by ianmcburnie** [comment]
As it's not part of the pattern, I'm going to add this to backlog until further updates/insights from design system. If it becomes an actual issue, I think we can address it in a backwards compatible way without markup changes.

For now, when inline notice content doesn't wrap to two lines, then `align-items: center` works well, and I guess teams can use that if they need. It doesn't work so well when wrapping to two lines with a button in there, because I think icon should always be at the top for wrapped text.... but it doesn't look terrible either.

**Comment by ianmcburnie** [comment]
Closing this as wont fix (for now at least)
