### ISSUE TITLE
disabled filter button pressed- text is not bold

### ISSUE THREAD

**Issue by hramakumar** [eBay/skin#786]
the disabled filter button in the pressed state does not have text bold and also the button size is not as pressed. only the background color is blue. 
Please let me know if this is expected

![image](https://user-images.githubusercontent.com/13157115/63476996-f9850300-c437-11e9-9548-d544bd9d3135.png)

**Comment by msendlakowski** [comment]
I just confirmed with the design team.  No bold is fine in the disabled case.
