### ISSUE TITLE
Pagination: Update DS6 arrow icons with new DS6.5 16x16 arrow

### ISSUE THREAD

**Issue by seangates** [eBay/skin#805]
The new 16x16 arrow is more bold, and has replaced the old 18x18 arrow in the pagination component, per the DS team and Zeplin.

We should update accordingly.

See also: https://github.com/eBay/ebayui-core/issues/839

**Comment by msendlakowski** [comment]
Looks like pagination isn't on the road map.  I can take this for the 9.1.0 release.

**Comment by seangates** [comment]
Pagination fell under that "lightning" round from earlier, right?

**Comment by msendlakowski** [comment]
Right. I did a search in the roadmap and didn't see it.  And forgot about that small change that was made there.
