### ISSUE TITLE
Pagination: implement new DS6 pattern

### ISSUE THREAD

**Issue by ianmcburnie** [eBay/skin#81]
@JeffNixonCreative Can you please add the DS6 pagination pattern?

**Comment by JeffNixonCreative** [comment]
[Pagination_SKIN_v1.pdf](https://github.com/eBay/skin/files/1812973/Pagination_SKIN_v1.pdf)

**Comment by sharma46bhawana** [comment]
The PR for this issue has been merged, so closing this issue.

**Comment by seangates** [comment]
Way to go, @sharma46bhawana! Great stuff.
