### ISSUE TITLE
BUG: Field's browser.json doesn't have DS6 dependencies added

### ISSUE THREAD

**Issue by sharma46bhawana** [eBay/skin#815]
Version: 8.0.1

Happens when creating stories in storybook, adding the field dependency in `browser.json` doesn't add the DS6 styles.

**Comment by seangates** [comment]
@sharma46bhawana Can you share the version and other relevant information?

**Comment by ianmcburnie** [comment]
Just spotted this one. We should try and get it into 9.2.0

**Comment by seangates** [comment]
After review, this is related to Storybook/Webpack, and not Marko/Lasso. Closing. We'll follow up with you in other mediums, @sharma46bhawana.
