### ISSUE TITLE
Menu: incorrect font on fake menu button

### ISSUE THREAD

**Issue by yomed** [eBay/skin#83]
In the fake menu case where buttons and links are mixed together as menu items, there are some minor style differences:
- The button does not get the correct font (seems it should have value `inherit`?)
- Hovering over a link menu item shows an underline, while a button does not.

In this screenshot, item 2 is a button, while items 1 and 3 are links. Item 1 is being hovered.
<img width="173" alt="screen shot 2018-03-05 at 4 34 05 pm" src="https://user-images.githubusercontent.com/3595986/37007618-0cfa3792-2093-11e8-8215-fce8c625b299.png">

**Comment by ianmcburnie** [comment]
`Hovering over a link menu item shows an underline, while a button does not.`

This is intentional. It gives visual affordance that this item acts like a hyperlink. This behaviour is probably not documented anywhere, but we can fix that ;-)

**Comment by seangates** [comment]
@ianmcburnie We should bring this up with design as well, because I don't think they know there is a difference.

**Comment by ianmcburnie** [comment]
Yep, we now have the bandwidth to raise and tackle these kind of issues. In the past, not so much...

**Comment by JeffNixonCreative** [comment]
When using a button and link together in a drop menu, the patterns should be consistent. So, the button should be modified to emulate the same styles as the link.

**Comment by ianmcburnie** [comment]
@JeffNixonCreative The underline is what gives a user the affordance this is a link, as opposed to a button.

**Comment by ianmcburnie** [comment]
First part of this issue (The button does not get the correct font) is fixed in 5.0.0. I will split these issues in two for easier tracking.
