### ISSUE TITLE
Notice: fix up and simplify test page

### ISSUE THREAD

**Issue by ianmcburnie** [eBay/skin#840]
The DS4 tests look fine, but DS6 has a few issues. I think we can probably reduce and simplify the amount of tests now too.

![Screen Shot 2019-09-18 at 10 30 31 AM](https://user-images.githubusercontent.com/38065/65171329-6ff92e80-d9ff-11e9-9dcd-79fde59a172f.png)

**Comment by seangates** [comment]
@agliga Did this get handled with #847?

**Comment by agliga** [comment]
> @agliga Did this get handled with #847?

@seangates  Yes!

**Comment by seangates** [comment]
Sweet. Closing.
