### ISSUE TITLE
Selected radio button should be blue instead of black

### ISSUE THREAD

**Issue by BhavinPatel04** [eBay/skin#859]
The selected radio button in the latest version is black instead of blue.

![image](https://user-images.githubusercontent.com/6559211/65630696-c7ad1200-df8a-11e9-8083-02e7cf514127.png)

**Comment by ianmcburnie** [comment]
@BhavinPatel04 Not sure if you've started on this or not. I'm assuming not, so I'm passing it to @agliga just so we can get it out in time for next week's release.

**Comment by BhavinPatel04** [comment]
@ianmcburnie I did start. I was going through the code since this is my first change in the code. But  it seems we need to it get it out next week so its fine if @agliga takes over.

**Comment by ianmcburnie** [comment]
@BhavinPatel04 No worries! Thanks for the update.

**Comment by ianmcburnie** [comment]
Fix merged to 9.2.0-1
