### ISSUE TITLE
Color: add palette colours

### ISSUE THREAD

**Issue by ianmcburnie** [eBay/skin#872]
For certain "branded" modules, experience server is sending down a schema such as:

```
"textColors": {
  "headline": "Y1",
  "callToAction": "O1",
  "subHeadline": "Y2",
  "finePrint": "Y3"
},
```

There is a request to expose our color variables so that they can be more easily consumed as "atomic css" on the frontend (i.e rather than app having to parse our LESS variables and create their own classes). For example:

```
<h1 class="color-y1">Headline</h1>
<a class="color-o1">Link></a>
```

**Comment by seangates** [comment]
Would this only apply to the `color` rule for fonts?

**Comment by ianmcburnie** [comment]
In the above example yes, they are all textColors.

**Comment by bhoomisatasiya** [comment]
Hi @ianmcburnie , thank you for creating this task. We have requirement for background color as well. 
```{ "backgroundColor": "M7" }```

**Comment by ianmcburnie** [comment]
@bhoomisatasiya Any preference on syntax of these classes? I've listed a few suggestions above. Open to others too.

**Comment by ianmcburnie** [comment]
After more thought, because adding this right now would dramatically increase the size of the color module, I think we should do it in a more modular way in next major version:

* @ebay/skin/color
  * @ebay/skin/color/palette
  * @ebay/skin/color/product
  * @ebay/skin/color/grayscale

**Comment by ianmcburnie** [comment]
This requirement went away. Going to close. We can always revisit.
