### ISSUE TITLE
DS6 site on IE11 is ... broken

### ISSUE THREAD

**Issue by seangates** [eBay/skin#90]
Funny as heck. Should we fix it?

![image](https://user-images.githubusercontent.com/105656/37237995-d3dea94e-23d9-11e8-9093-40aef3eb6bbb.png)

**Comment by ianmcburnie** [comment]
How on earth???? Yes, we should fix. PR should go straight into master.

**Comment by ianmcburnie** [comment]
But won't your new design fix this?

**Comment by seangates** [comment]
No, that _is_ the new design. I just don't want to fight with it, honestly. Hence my tag "discussion".

**Comment by seangates** [comment]
Basically, there are some css rules around grid that I would have to redo.

**Comment by ianmcburnie** [comment]
Ah, I see. Yes, it should be fixed.

**Comment by seangates** [comment]
[sigh] Sure. Will do so ...

**Comment by seangates** [comment]
Fixed. https://github.com/eBay/skin/pull/89/commits/6738a892363bf5d0f8a2ad98c7d11669f87002e7
