### ISSUE TITLE
Filter-Menu: merge into Menu?

### ISSUE THREAD

**Issue by ianmcburnie** [eBay/skin#900]
UPDATE: see comment https://github.com/eBay/skin/issues/900#issuecomment-656472598

OLD DESCRIPTION:

Currently, our standalone menu looks as if it was just yanked apart from the button. Which it was. 

<img width="316" alt="Screen Shot 2019-11-04 at 3 56 12 PM" src="https://user-images.githubusercontent.com/38065/68167813-ae996880-ff1b-11e9-8476-0fd3ca91ce10.png">

This was a good first step, but to make it a little more useful for mweb, we need some changes:

1. Remove the border (done in v10 branch)
2. Create a variant that has a radio button icon on the left, instead of a check mark on the right
3. Review hover/focus states

Once we do this, we can actually probably drop the filter-menu and use the updated menu in its place.

Goal:

<img width="371" alt="Screen Shot 2019-11-04 at 3 57 30 PM" src="https://user-images.githubusercontent.com/38065/68167849-d4bf0880-ff1b-11e9-9f86-bd3773c05ebb.png">

We should do similar for checkbox items too.

<img width="370" alt="Screen Shot 2019-11-04 at 3 54 53 PM" src="https://user-images.githubusercontent.com/38065/68167772-87db3200-ff1b-11e9-9f6b-c4d739017c85.png">

**Comment by seangates** [comment]
Interesting! I like this.

**Comment by ianmcburnie** [comment]
Going to do the first part if this only in v10 (remove border).

**Comment by ianmcburnie** [comment]
Okay, so this can now technically be done using the filter-menu (after I added single select variant #1158). Basically, filter-menu behaves identically to regular menu, it just has different icons, and the icons are on the left. We should look into merging the two modules given how similar they are. I will update the title of this issue to reflect this.

**Comment by ianmcburnie** [comment]
Moving to super backlog
