### ISSUE TITLE
Infotip: too much space between 'i' icon and layer when pointer='top-left'

### ISSUE THREAD

**Issue by melquan** [eBay/skin#906]
Version: 9.4.0

![image](https://user-images.githubusercontent.com/19419138/68437457-dbe15300-0175-11ea-810c-385797bc0fc9.png)

**Comment by melquan** [comment]
May be related to/duplicated by https://github.com/eBay/ebayui-core/issues/911.

**Comment by ianmcburnie** [comment]
@seangates Any thoughts on what the issue might be? (I've not spent any time looking yet)

**Comment by seangates** [comment]
When we redid the icons, we likely didn't make some minor adjustments here. Since we hard code some values for the location of the overlay (we have a map of top/right/left/bottom location values in Core) we just need to make those adjustments in the Skin docs as well.

**Comment by ianmcburnie** [comment]
Fix will go out in 9.5.0
