### ISSUE TITLE
Listbox: add borderless variant for DS6

### ISSUE THREAD

**Issue by zzhan223** [eBay/skin#92]

**Comment by zzhan223** [comment]
<img width="370" alt="screen shot 2018-04-02 at 11 47 55 am" src="https://user-images.githubusercontent.com/12809183/38210243-b4e25f32-366b-11e8-8faa-475d5e5b7385.png">
@ianmcburnie

**Comment by seangates** [comment]
The borderless select is almost completed for Skin, currently slated for v4.0.0.
