### ISSUE TITLE
 Combobox: overlay position not aligned correctly (Safari)

### ISSUE THREAD

**Issue by ianmcburnie** [eBay/skin#936]
This one's been bugging me for a while. Left and right edges should be flush with textbox. It's fine in Chrome & Firefox though, hence the P3.

<img width="267" alt="Screen Shot 2019-11-27 at 2 30 01 PM" src="https://user-images.githubusercontent.com/38065/69763580-7eac4200-1122-11ea-98d4-efcd80fca73b.png">

**Comment by ianmcburnie** [comment]
Some initial explorations make me think that combobox needs some specific styles different from our other dropdowns (e.g. menu-button & listbox-button, that have a width that grows with content). Setting `left: 0; width: calc(100% - 4px)`

<img width="216" alt="Screen Shot 2020-01-07 at 12 07 15 PM" src="https://user-images.githubusercontent.com/38065/71925599-49920700-3146-11ea-8a40-f91b40955a9a.png">

**Comment by stevedoty** [comment]
Hey, here are two solutions. It should be resolved. If these solutions don't work for you, please let me know.

**Comment by ianmcburnie** [comment]
Issue fixed in 10.3.0 branch. Thanks @stevedoty !
