### ISSUE TITLE
Combobox: option wraps with large line height

### ISSUE THREAD

**Issue by seangates** [eBay/skin#937]
The options should look closer together. Presently, the line height of `2.5` forces them to have a weird wrap:

![image](https://user-images.githubusercontent.com/105656/69985367-42009200-14f8-11ea-8d85-195bca106ef0.png)

**Comment by ianmcburnie** [comment]
@seangates I can look at this in v10 if there's no hurry.

**Comment by seangates** [comment]
I just came across it with my work with the ID. No pressing need as of yet.

**Comment by ianmcburnie** [comment]
Looks like line-height should be dropped in favor of padding:

![Screen Shot 2020-01-07 at 10 57 28 AM](https://user-images.githubusercontent.com/38065/71920895-9a9cfd80-313c-11ea-88af-29358f972fad.png)
