### ISSUE TITLE
ebay-carousel: pill :hover state has a different color than #2b0eaf

### ISSUE THREAD

**Issue by BhavinPatel04** [eBay/skin#945]
# Bug Report

## Description
ebay-carousel pills have different color on hover than #2b0eaf

## Workaround
Overwrite styles in application code

## Screenshots
![image](https://user-images.githubusercontent.com/6559211/70348038-ab451580-1816-11ea-9e80-4d231c33c804.png)

EXPECTED: The button and pill hover color should match

**Comment by ianmcburnie** [comment]
Fixed in 9.5.0. Thanks @BhavinPatel04
