### ISSUE TITLE
New module: Pagination 

### ISSUE THREAD

**Issue by sharma46bhawana** [eBay/skin#99]

**Comment by ianmcburnie** [comment]
@sharma46bhawana Please use this existing issue: https://github.com/eBay/skin/issues/81

**Comment by ianmcburnie** [comment]
Actually, if it's easier for you to use this one, just closer the other :-)

**Comment by sharma46bhawana** [comment]
Oh I couldn't find the issue, so I created one. Sorry I will close this.
